import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluateCommercialDecision} from '../commercial-decision-engine.js';

function product(){return {name:'Car sunglasses magnetic visor holder',commercialHardening:{gates:{pricingVerified:true,supplierVerified:true,reviewVerified:true,salesVerified:false}},romaniaDemand:{readyForTestDemandGate:true},salesEstimation:{status:'ESTIMATED_HIGH_CONFIDENCE',estimatedUnits30d:120,confidence:100},launchScore:{enoughEvidence:true},evidenceCoverage:{evidenceReady:true},competitors:{evidenceMarkets:2},dataConfidence:{overall:70},trendIntelligence:{status:'RISING'},profitEngineV2:{derivedSalePrice:44.74}};}
function baseState(){return {supplierRecords:{},supplierOffers:[],observations:[],landedCosts:{'car sunglasses magnetic visor holder':{productName:'Car sunglasses magnetic visor holder',confirmed:true,landedPerUnit:2}},testExecutions:[]};}
function measured(status,metrics={sellThroughPct:75,returnRatePct:5,netMarginPct:22,contributionProfitRon:132}){return {productName:'Car sunglasses magnetic visor holder',status:'MEASURED',measuredAt:'2026-08-24T06:00:00.000Z',unitsReceived:20,unitsSold:15,outcome:{status,automaticBuy:false,metrics}};}

test('latest measured TEST_PASS_CANDIDATE satisfies the real BUY gate only after commercial gates are healthy',()=>{const s=baseState();s.testExecutions=[measured('TEST_PASS_CANDIDATE')];const d=evaluateCommercialDecision(product(),s);assert.equal(d.status,'BUY');assert.equal(d.buyGate.completedRealTest,true);assert.equal(d.buyGate.source,'TEST_EXECUTION');assert.equal(d.buyGate.testOutcome,'TEST_PASS_CANDIDATE');assert.equal(d.buyGate.sellThroughPct,75);});

test('latest measured TEST_FAIL blocks BUY even if an older legacy test appears positive',()=>{const s=baseState();s.testExecutions=[measured('TEST_FAIL',{sellThroughPct:40,returnRatePct:0,netMarginPct:20,contributionProfitRon:50})];s.observations=[{productName:'Car sunglasses magnetic visor holder',kind:'COMMERCIAL_TEST',verified:true,payload:{completedAt:'2026-08-20T00:00:00.000Z',quantity:20,unitsSold:20,unitLandedCostRon:2,salePriceRon:40,adSpendRon:0,returnCostRon:0}}];const d=evaluateCommercialDecision(product(),s);assert.equal(d.status,'TEST_BUY');assert.equal(d.buyGate.completedRealTest,false);assert.equal(d.buyGate.source,'TEST_EXECUTION');assert.equal(d.buyGate.testOutcome,'TEST_FAIL');});

test('PLANNED or RUNNING test execution never counts as completed real test',()=>{const s=baseState();s.testExecutions=[{productName:'Car sunglasses magnetic visor holder',status:'RUNNING',outcome:null}];const d=evaluateCommercialDecision(product(),s);assert.equal(d.status,'TEST_BUY');assert.equal(d.buyGate.completedRealTest,false);});

test('legacy COMMERCIAL_TEST remains fallback only when there is no measured Test Execution',()=>{const s=baseState();s.observations=[{productName:'Car sunglasses magnetic visor holder',kind:'COMMERCIAL_TEST',verified:true,payload:{completedAt:'2026-08-20T00:00:00.000Z',quantity:20,unitsSold:15,unitLandedCostRon:2,salePriceRon:40,adSpendRon:10,returnCostRon:0}}];const d=evaluateCommercialDecision(product(),s);assert.equal(d.status,'BUY');assert.equal(d.buyGate.source,'LEGACY_COMMERCIAL_TEST');});
