import assert from "node:assert/strict";
import {access,readFile,readdir} from "node:fs/promises";
import {constants} from "node:fs";
import test from "node:test";

test("only the canonical Netlify Functions are present",async()=>{const entries=(await readdir("netlify/functions",{recursive:true})).filter(entry=>entry.endsWith(".mjs")).sort();assert.deepEqual(entries,["_billing-mutation-idempotency.mjs","_billing-webhook-claim.mjs","_billing-workspace-access.mjs","_readiness-auth.mjs","_security-ops.mjs","_workspace-access.mjs","beta-analytics.mjs","beta-participants.mjs","billing-cancel.mjs","billing-change-plan.mjs","billing-checkout.mjs","billing-journey-snapshot.mjs","billing-readiness.mjs","billing-resume.mjs","billing-status.mjs","billing-webhook.mjs","closed-beta-scorecard.mjs","commercial-discover.mjs","commercial-radar.mjs","free-top25.mjs","launch-readiness.mjs","legal-readiness.mjs","paid-beta-runtime-readiness.mjs","radar-data.mjs","radar-health.mjs","radar-scan-background.mjs","radar-schedule.mjs","radar-sync.mjs","radar-trigger.mjs","sandbox-preflight-readiness.mjs","top25-history.mjs","top25-refresh.mjs"]);});

function workspaceFetch({plan='RADAR',role='OWNER'}={}){return async url=>{const u=String(url);if(u.includes('/auth/v1/user'))return Response.json({id:'u1'});if(u.includes('/rest/v1/workspace_members'))return Response.json([{workspace_id:'w1',user_id:'u1',role}]);if(u.includes('/rest/v1/workspaces'))return Response.json([{id:'w1',name:'Workspace',plan,owner_id:'u1'}]);if(u.includes('/rest/v1/api_rate_limit_events'))return new Response(null,{status:201});return new Response(null,{status:404});};}

test("radar-data requires explicit workspace and exposes live data only to Radar entitlement",async()=>{const {createRadarDataHandler}=await import("../netlify/functions/radar-data.mjs");const values=new Map([["latest",JSON.stringify({updatedAt:"2026-08-10T00:00:00Z",products:[{name:"Live"}]})],["scan-status",JSON.stringify({status:"completed"})]]);const handler=createRadarDataHandler({getStore:()=>({get:key=>values.get(key)}),fetch:workspaceFetch(),env:{SUPABASE_URL:'https://example.supabase.co',SUPABASE_ANON_KEY:'anon'}});const missing=await handler(new Request('https://radar.example/api/radar/data',{headers:{authorization:'Bearer token'}}));assert.equal(missing.status,400);const response=await handler(new Request('https://radar.example/api/radar/data',{headers:{authorization:'Bearer token','x-mpr-workspace-id':'w1'}}));assert.equal(response.status,200);const body=await response.json();assert.equal(body.workspaceId,'w1');assert.equal(body.plan,'RADAR');assert.equal(body.live,true);});

test("radar trigger requires owner/admin workspace context before invoking protected background route",async()=>{const {createTriggerHandler}=await import("../netlify/functions/radar-trigger.mjs");const writes=new Map();let outbound;const fetchImpl=async(url,options)=>{const u=String(url);if(u.includes('/auth/v1/user'))return Response.json({id:'u1'});if(u.includes('/rest/v1/workspace_members'))return Response.json([{workspace_id:'w1',user_id:'u1',role:'OWNER'}]);if(u.includes('/rest/v1/workspaces'))return Response.json([{id:'w1',name:'W',plan:'RADAR',owner_id:'u1'}]);if(u.includes('/rest/v1/api_rate_limit_events')||u.includes('/rest/v1/security_audit_events'))return new Response(null,{status:201});outbound={url,options};return new Response(null,{status:202});};const handler=createTriggerHandler({env:{RADAR_INTERNAL_SECRET:'server-only',SUPABASE_URL:'https://example.supabase.co',SUPABASE_ANON_KEY:'anon',SUPABASE_SERVICE_ROLE_KEY:'service'},getStore:()=>({set:(key,value)=>writes.set(key,value)}),fetch:fetchImpl});const unauthorized=await handler(new Request('https://radar.example/api/radar/trigger',{method:'POST'}));assert.equal(unauthorized.status,401);const response=await handler(new Request('https://radar.example/api/radar/trigger',{method:'POST',headers:{authorization:'Bearer token','x-mpr-workspace-id':'w1'}}));assert.equal(response.status,202);assert.match(outbound.url,/\/api\/radar\/scan\?scanId=/);assert.equal(outbound.options.headers['x-radar-secret'],'server-only');const scan=JSON.parse(writes.get('scan-status'));assert.equal(scan.workspaceId,'w1');assert.equal(JSON.stringify(await response.json()).includes('server-only'),false);});

test("background scan rejects missing server secret before calling paid services",async()=>{const previous=process.env.RADAR_INTERNAL_SECRET;delete process.env.RADAR_INTERNAL_SECRET;try{const {default:scan}=await import("../netlify/functions/radar-scan-background.mjs");const response=await scan(new Request("https://radar.example/api/radar/scan",{method:"POST"}));assert.equal(response.status,403);}finally{if(previous===undefined)delete process.env.RADAR_INTERNAL_SECRET;else process.env.RADAR_INTERNAL_SECRET=previous;}});

test("cloud sync is disabled without server secret and rejects wrong secret",async()=>{const {createRadarSyncHandler}=await import("../netlify/functions/radar-sync.mjs");let touched=false;const disabled=createRadarSyncHandler({env:{},getStore:()=>{touched=true;return{};}});const noSecret=await disabled(new Request("https://radar.example/api/radar/sync"));assert.equal(noSecret.status,503);assert.equal(touched,false);const protectedHandler=createRadarSyncHandler({env:{RADAR_SYNC_SECRET:'correct'},getStore:()=>{touched=true;return{};}});const wrong=await protectedHandler(new Request("https://radar.example/api/radar/sync",{headers:{'x-radar-sync-secret':'wrong'}}));assert.equal(wrong.status,401);assert.equal(touched,false);});

test("static build source excludes private supplier/RFQ artifacts",async()=>{const source=await readFile('scripts/build-site.mjs','utf8');assert.doesNotMatch(source,/copyNested\s*\(/);assert.match(source,/PRIVATE_STATIC_ARTIFACT_EXPOSED/);assert.doesNotMatch(source,/supplier-candidates\/car-sunglasses-magnetic-visor-holder\.json'\s*,/);});

test("frontend normalization and economics handle untrusted malformed live fields",async()=>{const {economics,isBuyZone,normalizeProducts}=await import("../app.js");const [product]=normalizeProducts([{name:"<img onerror=alert(1)>",cat:null,landed:"50",sell:"200",score:"90",sourcing:"bad"}]);assert.equal(product.name,"<img onerror=alert(1)>");assert.deepEqual(product.sourcing,[]);assert.ok(economics(product).profit>0);assert.equal(isBuyZone(product),true);});

test("root-level duplicate functions are absent",async()=>{for(const file of ["radar-data.mjs","radar-scan-background.mjs","radar-schedule.mjs"])await assert.rejects(access(file,constants.F_OK));});

test("products.json has the frontend's required shape",async()=>{const products=JSON.parse(await readFile("products.json","utf8"));const required=["name","cat","chinaMin","chinaMax","landed","sell","gap","score","markets"];assert.ok(Array.isArray(products));assert.ok(products.length>0);for(const product of products){assert.deepEqual(required.filter(field=>!(field in product)),[]);for(const field of ["chinaMin","chinaMax","landed","sell","gap","score"])assert.equal(Number.isFinite(product[field]),true,`${product.name}: ${field}`);}});
