import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs/promises';
import {SAAS_CONFIG,isSaasConfigured} from '../saas-config.js';
import {workspaceSlug} from '../workspace-client.js';
import {hasFeature,planByCode,usageRemaining} from '../billing-plans.js';
import {CLOUD_DATASETS} from '../cloud-sync.js';

test('Radar 7 uses live Supabase with publishable browser credentials only',()=>{assert.equal(SAAS_CONFIG.mode,'LIVE');assert.equal(isSaasConfigured(SAAS_CONFIG),true);assert.match(SAAS_CONFIG.supabaseUrl,/^https:\/\/.+\.supabase\.co$/);assert.match(SAAS_CONFIG.supabaseAnonKey,/^sb_publishable_/);assert.doesNotMatch(SAAS_CONFIG.supabaseAnonKey,/service[_-]?role/i);});
test('workspace slug is stable and tenant safe',()=>{assert.equal(workspaceSlug('Red Commerce România'),'red-commerce-romania');assert.ok(workspaceSlug('***').length>0);});
test('commercial subscription tiers are deterministic, preserve aliases and follow the validated funnel',()=>{assert.equal(planByCode('FREE').monthlyPriceEur,0);assert.equal(planByCode('DISCOVER').monthlyPriceEur,17.9);assert.equal(planByCode('RADAR').monthlyPriceEur,29);assert.equal(planByCode('LAUNCH').monthlyPriceEur,89);assert.equal(planByCode('PRO').code,'RADAR');assert.equal(hasFeature('FREE','SUPPLIERS'),false);assert.equal(hasFeature('DISCOVER','TRENDING'),true);assert.equal(hasFeature('DISCOVER','SUPPLIERS'),false);assert.equal(hasFeature('DISCOVER','ROMANIA_GAP'),false);assert.equal(hasFeature('RADAR','ROMANIA_GAP'),true);assert.equal(hasFeature('RADAR','SUPPLIERS'),false);assert.equal(hasFeature('LAUNCH','SUPPLIERS'),true);assert.equal(hasFeature('LAUNCH','PERSONALIZED_SHORTLIST'),true);assert.equal(usageRemaining('FREE',2),1);});
test('Supabase schema contains workspace tenant boundary, supplier offers and RLS',async()=>{const sql=await fs.readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8');assert.match(sql,/workspace_members/);assert.match(sql,/supplier_offers/);assert.match(sql,/enable row level security/);assert.match(sql,/is_workspace_member/);assert.match(sql,/revoke execute on function public\.handle_new_user/);assert.doesNotMatch(sql,/service[_ -]?role/i);});
test('cloud-first sync maps all eight operational workspace datasets including private RFQ state',()=>{assert.equal(CLOUD_DATASETS.length,8);assert.deepEqual(CLOUD_DATASETS.map(x=>x.table),['suppliers','supplier_offers','rfq_dispatch_states','landed_costs','purchases','portfolio_items','feedback_events','discovery_candidates']);const rfq=CLOUD_DATASETS.find(x=>x.key==='megaRadarRfqDispatchV1');assert.equal(rfq?.shape,'array');assert.equal(rfq?.table,'rfq_dispatch_states');});
test('cloud-first sync preserves map datasets and current V6 storage keys',()=>{const byKey=Object.fromEntries(CLOUD_DATASETS.map(x=>[x.key,x]));for(const key of ['megaRadarSupplierRecordsV1','megaRadarLandedCostRecordsV1','megaRadarPurchaseRecordsV1','megaRadarDiscoveryRecordsV1'])assert.equal(byKey[key]?.shape,'map');assert.equal(byKey.megaRadarPortfolioV6?.legacyKey,'megaRadarPortfolioV1');assert.equal(byKey.megaRadarFeedbackV6?.legacyKey,'megaRadarFeedbackV1');assert.equal(byKey.megaRadarSupplierMatrixV6?.table,'supplier_offers');assert.equal(byKey.megaRadarRfqDispatchV1?.table,'rfq_dispatch_states');});
test('cloud-first implementation preserves map keys and installs autosync',async()=>{const js=await fs.readFile(new URL('../cloud-sync.js',import.meta.url),'utf8');assert.match(js,/__radarKey/);assert.match(js,/installCloudAutosync/);assert.match(js,/latestTime/);assert.match(js,/pushDatasetToCloud/);});
