import { getStore } from '@netlify/blobs';

const STORE_NAME='mega-radar-owner-sync',KEY='owner-backup',MAX_BYTES=900000;
function corsHeaders(){return{'Cache-Control':'no-store','Content-Type':'application/json; charset=utf-8'};}
function serverSecret(env=process.env){return String(env.RADAR_SYNC_SECRET||'').trim();}
function authorized(req,env){const expected=serverSecret(env),received=String(req.headers.get('x-radar-sync-secret')||'');return Boolean(expected)&&received===expected;}
export function createRadarSyncHandler({getStore:getStoreImpl=getStore,env=process.env}={}){return async req=>{const headers=corsHeaders(),secret=serverSecret(env);if(!secret)return new Response(JSON.stringify({ok:false,error:'Cloud sync is not configured on the server.'}),{status:503,headers});if(!authorized(req,env))return new Response(JSON.stringify({ok:false,error:'Unauthorized'}),{status:401,headers});try{const store=getStoreImpl({name:STORE_NAME,consistency:'strong'});if(req.method==='GET'){const raw=await store.get(KEY);return new Response(raw||JSON.stringify({ok:true,empty:true}),{status:200,headers});}if(req.method==='POST'){const text=await req.text();if(!text||new TextEncoder().encode(text).length>MAX_BYTES)return new Response(JSON.stringify({ok:false,error:'Invalid backup size'}),{status:400,headers});const parsed=JSON.parse(text);if(!parsed||typeof parsed!=='object'||!parsed.data||typeof parsed.data!=='object')return new Response(JSON.stringify({ok:false,error:'Invalid backup payload'}),{status:400,headers});const payload={ok:true,version:String(parsed.version||'5.7'),updatedAt:new Date().toISOString(),data:parsed.data};await store.set(KEY,JSON.stringify(payload));return new Response(JSON.stringify({ok:true,updatedAt:payload.updatedAt}),{status:200,headers});}return new Response(JSON.stringify({ok:false,error:'Method not allowed'}),{status:405,headers});}catch(error){return new Response(JSON.stringify({ok:false,error:String(error?.message||error)}),{status:500,headers});}};}
export default createRadarSyncHandler();
export const config={path:'/api/radar/sync'};
