const SEEN_KEY='megaRadarAlertSeenV1';
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const key=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export function buildAlerts(discovery={products:[]},radar={products:[]}){const out=[];for(const p of discovery.products||[]){const a=p.discoveryAnalysis||{},q=a.quality?.level||p.sourceStatus,score=n(a.score),d7=p.trendWindows?.d7;if(q==='LIVE'&&score>=84)out.push({id:`discovery-buy-${key(p.name)}-${p.checkedAt||discovery.updatedAt||''}`,type:'DISCOVERY',severity:'HIGH',title:`BUY CANDIDATE: ${p.name}`,body:`Discovery ${score}/100 • verifică furnizorul și landed cost-ul înainte de bani.`,at:p.checkedAt||discovery.updatedAt});if(q==='LIVE'&&d7&&n(d7.scoreDelta)>=6)out.push({id:`discovery-accel-${key(p.name)}-${d7.to||''}`,type:'TREND',severity:'MEDIUM',title:`Accelerează: ${p.name}`,body:`Scor +${n(d7.scoreDelta)} în fereastra de 7 zile.`,at:d7.to});}for(const p of radar.products||[]){const score=n(p.megaScore||p.score),action=String(p.megaAnalysis?.action||p.action||p.verdict||'').toUpperCase();if(score>=84&&['BUY','BUY ZONE'].includes(action))out.push({id:`radar-buy-${key(p.name)}-${p.lastChecked||radar.updatedAt||''}`,type:'RADAR',severity:'HIGH',title:`Radar BUY: ${p.name}`,body:`MEGA ${score}/100 • Supplier Verification rămâne obligatoriu.`,at:p.lastChecked||radar.updatedAt});}return out.sort((a,b)=>Date.parse(b.at||0)-Date.parse(a.at||0)).slice(0,30);}
function seenSet(){try{return new Set(JSON.parse(localStorage.getItem(SEEN_KEY)||'[]'));}catch{return new Set();}}
function saveSeen(set){localStorage.setItem(SEEN_KEY,JSON.stringify([...set].slice(-200)));}
async function registerSw(){if(!('serviceWorker'in navigator))throw new Error('Service Worker indisponibil în acest browser.');return navigator.serviceWorker.register('./sw.js',{scope:'./'});}
export async function enableRadarNotifications(){if(!('Notification'in window))throw new Error('Notificările web nu sunt disponibile.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Permisiunea pentru notificări nu a fost acordată.');await registerSw();return true;}
async function showNewAlerts(alerts){if(!('Notification'in window)||Notification.permission!=='granted'||!('serviceWorker'in navigator))return 0;const reg=await navigator.serviceWorker.ready,seen=seenSet(),fresh=alerts.filter(a=>!seen.has(a.id)).slice(0,3);for(const alert of fresh){await reg.showNotification(alert.title,{body:alert.body,tag:alert.id,data:{url:'./discovery-inbox.html'},icon:'./icon-192.png'}).catch(()=>reg.showNotification(alert.title,{body:alert.body,tag:alert.id,data:{url:'./discovery-inbox.html'}}));seen.add(alert.id);}saveSeen(seen);return fresh.length;}
async function loadJson(path){try{const r=await fetch(`${path}?t=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():{};}catch{return{};}}
export async function refreshAlerts(){const [discovery,radar]=await Promise.all([loadJson('discovery-live.json'),loadJson('radar-live.json')]),alerts=buildAlerts(discovery,radar);const count=document.querySelector('#alertCount'),list=document.querySelector('#alertList');if(count)count.textContent=String(alerts.length);if(list)list.innerHTML=alerts.length?alerts.slice(0,5).map(a=>`<div class="alertitem"><b>${a.title.replace(/[<>&]/g,'')}</b><small>${a.body.replace(/[<>&]/g,'')}</small></div>`).join(''):'<div class="alertitem"><small>Nicio alertă puternică acum.</small></div>';await showNewAlerts(alerts);return alerts;}
if(typeof document!=='undefined'){document.querySelector('#enableNotifications')?.addEventListener('click',()=>enableRadarNotifications().then(()=>refreshAlerts()).then(()=>{const e=document.querySelector('#notificationStatus');if(e)e.textContent='Notificări active';}).catch(err=>{const e=document.querySelector('#notificationStatus');if(e)e.textContent=err.message;}));refreshAlerts();}
