const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let products=[],tab='all',historyData={products:{}};
const WATCH_KEY='megaRadarWatchlistV1',BUDGET_KEY='megaRadarBuyingBudgetV1',ECON_KEY='megaRadarEconomicsV2';
export const ECON_DEFAULTS={vatRate:21,marketplaceRate:17,adsRate:8,returnsRate:3,fulfillment:6,packaging:2,extraImport:0};
const n=v=>Number.isFinite(Number(v))?Number(v):0,clamp=(v,min=0,max=100)=>Math.max(min,Math.min(max,n(v)));
const money=v=>`${n(v).toLocaleString('ro-RO',{maximumFractionDigits:2})} lei`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const keyOf=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
export function profitWithSettings(p,settings=ECON_DEFAULTS){const sell=n(p.sell),landed=n(p.landed),vat=clamp(settings.vatRate,0,99)/100,market=clamp(settings.marketplaceRate)/100,ads=clamp(settings.adsRate)/100,returns=clamp(settings.returnsRate)/100,fulfillment=Math.max(0,n(settings.fulfillment)),packaging=Math.max(0,n(settings.packaging)),extraImport=Math.max(0,n(settings.extraImport));const netSale=sell/(1+vat),marketplace=sell*market,adCost=sell*ads,returnReserve=sell*returns,totalCost=landed+extraImport+marketplace+adCost+returnReserve+fulfillment+packaging,profit=netSale-marketplace-adCost-returnReserve-fulfillment-packaging-landed-extraImport;return{profit,margin:sell?profit/sell*100:0,roi:(landed+extraImport)?profit/(landed+extraImport)*100:0,netSale,marketplace,adCost,returnReserve,fulfillment,packaging,extraImport,totalCost};}
export function economics(p){return profitWithSettings(p,ECON_DEFAULTS);}
export function isBuyZone(product){const e=economics(product);return n(product.megaScore||product.score)>=82&&e.profit>=50&&e.margin>=20&&(!isKids(product)||String(product.kidsGate||'').toUpperCase()==='PASS');}
export function normalizeProducts(value){return Array.isArray(value)?value.filter(x=>x&&typeof x==='object'&&String(x.name||'').trim()).map(x=>({...x,name:String(x.name),cat:String(x.cat||'Fără categorie'),evidence:String(x.evidence||''),chinaMin:n(x.chinaMin),chinaMax:n(x.chinaMax),landed:n(x.landed),sell:n(x.sell),score:n(x.score),megaScore:n(x.megaScore||x.score),sourcing:Array.isArray(x.sourcing)?x.sourcing:[]})):[];}
function isKids(p){return /kids|copii|3.?6|0.?6/i.test(`${p.cat||''} ${p.age||''}`);}
function loadSettings(){if(typeof localStorage==='undefined')return{...ECON_DEFAULTS};try{return{...ECON_DEFAULTS,...JSON.parse(localStorage.getItem(ECON_KEY)||'{}')};}catch{return{...ECON_DEFAULTS};}}
function uiSettings(){if(typeof document==='undefined')return loadSettings();const g=id=>n($('#'+id)?.value);return{vatRate:g('vatRate'),marketplaceRate:g('marketplaceRate'),adsRate:g('adsRate'),returnsRate:g('returnsRate'),fulfillment:g('fulfillment'),packaging:g('packaging'),extraImport:g('extraImport')};}
function saveSettings(){if(typeof localStorage!=='undefined')localStorage.setItem(ECON_KEY,JSON.stringify(uiSettings()));}
function currentEconomics(p){return profitWithSettings(p,uiSettings());}
function hasLiveSignal(p){return String(p.sourceStatus||'').toUpperCase()==='WEB_SIGNAL'&&n(p.marketScout?.checks)>=3&&n(p.marketScout?.foreignPresence)>=1;}
function fallbackAnalysis(p){const e=economics(p),foreign=n(p.marketScout?.foreignPresence),ro=n(p.marketScout?.romaniaPresence),china=n(p.marketScout?.chinaSourcingPresence),social=n(p.marketScout?.socialPresence),score=n(p.megaScore||p.score),gap=clamp(55+foreign*12+china*8-ro*25),sat=ro?58:90,margin=clamp(e.margin*1.7+e.roi*.25),demand=clamp(40+foreign*18),viral=clamp(n(p.social)||45+social*18);let action=String(p.action||p.verdict||'WATCH').toUpperCase();if(action==='BUY ZONE')action='BUY';if(action==='SAMPLE'||action==='VALIDATE')action='TEST';if(!['BUY','TEST','WATCH','REJECT'].includes(action))action=score>=82?'BUY':score>=76?'TEST':'WATCH';return{score,action,lifecycle:p.lifecycle||'WATCH',components:{demand,trend:55,romaniaGap:gap,saturation:sat,margin,viral,supplier:china?72:45,logistics:n(p.logistics)||78,compliance:n(p.compliance)||78}};}
function analysis(p){return p.megaAnalysis||fallbackAnalysis(p);}
function actionOf(p){const action=analysis(p).action||'WATCH';return isKids(p)&&String(p.kidsGate||'').toUpperCase()!=='PASS'&&action==='BUY'?'TEST':action;}
function historyOf(p){return p.historyPoints||historyData.products?.[keyOf(p.name)]?.points||[];}
function historyDelta(p){const pts=historyOf(p);return pts.length>1?n(pts.at(-1).score)-n(pts[0].score):0;}
export function supplierVerification(p){const s=p.supplierIntel||{},coverage=n(s.coverage),score=n(p.megaAnalysis?.components?.supplier||p.supplier||0),moq=n(s.moq),sampleCost=n(s.sampleCost),rating=n(s.rating),years=n(s.years),tradeAssurance=s.tradeAssurance===true,certs=Array.isArray(s.certifications)?s.certifications:[];let verdict='VERIFY',reason='Prezență de sourcing detectată, dar MOQ, sample, rating și termenii nu sunt confirmați.';if(coverage<=0){verdict='REJECT';reason='Nu există încă o sursă China detectată.';}else if(coverage>=1&&moq>0&&rating>=4.3&&years>=2&&(tradeAssurance||certs.length>0)){verdict='SUPPLIER OK';reason='Furnizorul are date comerciale minime confirmate; termenii finali trebuie reconfirmați înainte de plată.';}else if(score<35&&coverage<2){verdict='REJECT';reason='Semnalul de sourcing este prea slab pentru comandă.';}return{verdict,reason,coverage,score,moq,sampleCost,rating,years,tradeAssurance,certifications:certs};}
export function buyingDecision(p,settings=ECON_DEFAULTS){const a=analysis(p),e=profitWithSettings(p,settings),comp=p.competitorIntel||{},hist=historyDelta(p),reviewSources=n(p.reviewIntel?.sourceCount),supplier=n(a.components?.supplier),supplierCheck=supplierVerification(p),compliance=n(a.components?.compliance),gap=n(a.components?.romaniaGap),sat=n(a.components?.saturation),viral=n(a.components?.viral),score=n(a.score||p.score),competitionRisk=clamp(n(comp.resultProxy)*8),historyRisk=hist<0?clamp(Math.abs(hist)*8):0,reviewRisk=reviewSources?20:55,supplierRisk=supplierCheck.verdict==='REJECT'?85:supplierCheck.verdict==='VERIFY'?45:10;const killScore=Math.round(clamp((100-score)*.24+competitionRisk*.15+(100-supplier)*.13+(100-compliance)*.13+historyRisk*.10+reviewRisk*.08+supplierRisk*.17)),historyStrength=clamp(50+hist*5),profitStrength=clamp(e.margin*1.4+e.roi*.18),readiness=Math.round(clamp(score*.31+gap*.14+profitStrength*.18+supplier*.10+sat*.07+viral*.05+historyStrength*.05+(reviewSources?75:45)*.03+(supplierCheck.verdict==='SUPPLIER OK'?90:supplierCheck.verdict==='VERIFY'?55:15)*.07));let decision='WAIT',units=0;if(actionOf(p)==='REJECT'||supplierCheck.verdict==='REJECT'||killScore>=70||e.profit<10)decision='KILL';else if(actionOf(p)==='BUY'&&supplierCheck.verdict==='SUPPLIER OK'&&readiness>=76&&killScore<42&&e.profit>=35){decision='ORDER NOW';units=24;}else if(['BUY','TEST'].includes(actionOf(p))&&supplierCheck.verdict!=='REJECT'&&readiness>=62&&killScore<60&&e.profit>=20){decision='SMALL TEST';units=8;}return{decision,readiness,killScore,units,investment:units*(n(p.landed)+n(settings.extraImport)),revenue:units*n(p.sell),profitPotential:units*e.profit,historyDelta:hist,supplierVerdict:supplierCheck.verdict,economics:e};}
function link(site,name){const q=encodeURIComponent(name);return site==='Alibaba'?`https://www.alibaba.com/trade/search?SearchText=${q}`:site==='1688'?`https://s.1688.com/selloffer/offer_search.htm?keywords=${q}`:site==='eMAG'?`https://www.emag.ro/search/${q}`:`https://www.amazon.de/s?k=${q}`;}
function tone(a){return a==='BUY'||a==='ORDER NOW'||a==='SUPPLIER OK'?'buy':a==='TEST'||a==='SMALL TEST'||a==='VERIFY'?'test':a==='REJECT'||a==='KILL'?'reject':'watch';}
function component(label,value){const v=Math.round(clamp(value));return `<div class="component"><div><span>${esc(label)}</span><b>${v}</b></div><div class="bar"><i style="width:${v}%"></i></div></div>`;}
function watchSet(){try{return new Set(JSON.parse(localStorage.getItem(WATCH_KEY)||'[]'));}catch{return new Set();}}
function watched(p){return typeof localStorage!=='undefined'&&watchSet().has(p.name);}
function toggleWatch(name){const set=watchSet();set.has(name)?set.delete(name):set.add(name);localStorage.setItem(WATCH_KEY,JSON.stringify([...set]));render();}
function budgetValue(){return typeof document==='undefined'?3000:Math.max(0,n($('#buyingBudget')?.value)||3000);}
function deltaText(v,suffix=''){if(v==null)return'baseline';const x=n(v);return`${x>0?'+':''}${x}${suffix}`;}
function sparkline(points){if(!Array.isArray(points)||points.length<2)return'<div class="nohistory">Istoricul se acumulează la scanările următoare.</div>';const vals=points.map(x=>clamp(x.score)),coords=vals.map((v,i)=>`${i*(100/(vals.length-1))},${38-v*.32}`).join(' ');return `<svg class="spark" viewBox="0 0 100 40" preserveAspectRatio="none"><polyline points="${coords}"/></svg>`;}
function supplierBox(p){const s=supplierVerification(p);return `<div class="intelbox"><div><small>Supplier Verification</small><b class="txt-${tone(s.verdict)}">${esc(s.verdict)}</b></div><span>${s.coverage}/2 surse China • score ${Math.round(s.score)}/100</span><em>${esc(s.reason)}</em><span>MOQ ${s.moq||'—'} • Sample ${s.sampleCost?money(s.sampleCost):'—'} • Rating ${s.rating||'—'} • Ani ${s.years||'—'}</span></div>`;}
function historyBox(p){const pts=historyOf(p),first=pts[0],last=pts.at(-1),delta=pts.length>1?n(last.score)-n(first.score):null;return `<div class="historybox"><div class="historyhead"><div><small>Istoric real</small><b>${pts.length} scanări</b></div><strong>${deltaText(delta,' pct')}</strong></div>${sparkline(pts)}<span>${pts.length?`MEGA ${n(first.score)} → ${n(last.score)}`:'Colectare în curs'}</span></div>`;}
function costBreakdown(p){const e=currentEconomics(p);return `<div class="intelbox"><div><small>Profit Calculator Pro</small><b>${money(e.profit)}/buc.</b></div><span>Marjă ${e.margin.toFixed(1)}% • ROI ${e.roi.toFixed(0)}%</span><em>Comision ${money(e.marketplace)} • Ads ${money(e.adCost)} • retururi ${money(e.returnReserve)} • fulfillment ${money(e.fulfillment)} • ambalare ${money(e.packaging)} • extra import ${money(e.extraImport)}</em></div>`;}
function decisionBox(p){const d=buyingDecision(p,uiSettings());return `<div class="decisionbox ${tone(d.decision)}box"><div><span class="decisionbadge ${tone(d.decision)}">${esc(d.decision)}</span><strong>Readiness ${d.readiness}/100</strong></div><div class="decisionmetrics"><span>Kill <b>${d.killScore}/100</b></span><span>Supplier <b>${esc(d.supplierVerdict)}</b></span></div>${d.units?`<p>${d.units} buc. • investiție ${money(d.investment)} • profit potențial ${money(d.profitPotential)}</p>`:`<p>${d.decision==='KILL'?'Nu aloca buget acum.':'Așteaptă sau validează furnizorul înainte de comandă.'}</p>`}</div>`;}
function card(p){const a=analysis(p),e=currentEconomics(p),d=buyingDecision(p,uiSettings()),checked=p.marketScout?.checkedAt||p.lastChecked,encoded=encodeURIComponent(p.name);return `<article class="card ${tone(actionOf(p))}card"><div class="top"><div><div class="name">${esc(p.name)}</div><div class="cat">${esc(p.cat)} • ${esc(a.lifecycle||'WATCH')}</div><span class="badge ${tone(actionOf(p))}">${esc(actionOf(p))}</span> <span class="decisionbadge ${tone(d.decision)}">${esc(d.decision)}</span></div><div class="score"><small>MEGA 4.1</small>${Math.round(n(a.score||p.score))}<span>/100</span></div></div><div class="hero-metrics"><div><small>Readiness</small><b>${d.readiness}/100</b></div><div><small>Kill Score</small><b>${d.killScore}/100</b></div><div><small>Profit real simulat</small><b>${money(e.profit)}</b><em>ROI ${e.roi.toFixed(0)}%</em></div><div><small>Supplier</small><b>${esc(d.supplierVerdict)}</b></div></div>${decisionBox(p)}<details><summary>Analiză completă</summary><div class="components">${component('Demand',a.components?.demand)}${component('Trend',a.components?.trend)}${component('Romania Gap',a.components?.romaniaGap)}${component('Saturation',a.components?.saturation)}${component('Margin',a.components?.margin)}${component('Viral',a.components?.viral)}${component('Supplier',a.components?.supplier)}${component('Logistics',a.components?.logistics)}${component('Compliance',a.components?.compliance)}</div><div class="intelgrid">${supplierBox(p)}${costBreakdown(p)}${historyBox(p)}<div class="intelbox"><div><small>Competitor RO</small><b>${n(p.competitorIntel?.resultProxy)} proxy</b></div><span>${esc(p.competitorIntel?.status||'BASELINE')}</span><em>Proxy web, nu număr verificat de selleri.</em></div></div></details><div class="metrics"><div class="metric"><small>Cost China</small><b>${money(p.chinaMin)} – ${money(p.chinaMax)}</b></div><div class="metric"><small>Landed</small><b>${money(p.landed)}</b></div><div class="metric"><small>Preț RO</small><b>${money(p.sell)}</b></div><div class="metric"><small>Marjă simulată</small><b>${e.margin.toFixed(1)}%</b></div></div>${checked?`<div class="validated">Ultima verificare: ${esc(new Date(checked).toLocaleString('ro-RO'))} • ${hasLiveSignal(p)?'semnal web live':'validare parțială'}</div>`:''}<div class="actions"><button class="watchbtn ${watched(p)?'active':''}" data-watch="${esc(encoded)}">${watched(p)?'★ În Watchlist':'☆ Watchlist'}</button><a target="_blank" rel="noopener" href="${link('Alibaba',p.name)}">Alibaba ↗</a><a target="_blank" rel="noopener" href="${link('1688',p.name)}">1688 ↗</a><a target="_blank" rel="noopener" href="${link('eMAG',p.name)}">eMAG ↗</a></div></article>`;}
function buyingPortfolio(budget){const settings=uiSettings(),candidates=products.map(p=>({p,d:buyingDecision(p,settings)})).filter(x=>['ORDER NOW','SMALL TEST'].includes(x.d.decision)).sort((x,y)=>y.d.readiness-x.d.readiness||x.d.killScore-y.d.killScore);let remaining=budget;const items=[];for(const x of candidates){if(items.length>=10||remaining<=0)break;const unitCost=n(x.p.landed)+n(settings.extraImport);if(unitCost<=0)continue;const maxByCap=Math.floor(Math.min(remaining,budget*.32)/unitCost),units=Math.min(x.d.units,maxByCap),min=x.d.decision==='ORDER NOW'?5:3;if(units<min)continue;const e=profitWithSettings(x.p,settings),investment=units*unitCost;items.push({...x,units,investment,profitPotential:units*e.profit});remaining-=investment;}return{remaining,investment:items.reduce((s,x)=>s+x.investment,0),profitPotential:items.reduce((s,x)=>s+x.profitPotential,0),items};}
function renderBuyingPlan(){const plan=buyingPortfolio(budgetValue());$('#allocated').textContent=money(plan.investment);$('#portfolioProfit').textContent=money(plan.profitPotential);$('#portfolioCount').textContent=plan.items.length;$('#budgetLeft').textContent=money(plan.remaining);$('#buyingPlan').innerHTML=plan.items.length?plan.items.map((x,i)=>`<div class="buyrow"><span>#${i+1}</span><div><b>${esc(x.p.name)}</b><small>${esc(x.d.decision)} • Readiness ${x.d.readiness} • ${esc(x.d.supplierVerdict)}</small></div><div class="buyqty"><b>${x.units} buc.</b><small>${money(x.investment)}</small></div><strong>+${money(x.profitPotential)}</strong></div>`).join(''):'<div class="alertempty">Nu forțăm o comandă: validează costurile/furnizorii sau așteaptă semnale mai bune.</div>';}
function render(){const q=$('#search').value.trim().toLowerCase(),cat=$('#category').value,sort=$('#sort').value,settings=uiSettings();let a=products.filter(p=>(!cat||p.cat===cat)&&(!q||`${p.name} ${p.cat}`.toLowerCase().includes(q)));if(tab==='watchlist')a=a.filter(watched);else if(tab==='order')a=a.filter(p=>buyingDecision(p,settings).decision==='ORDER NOW');else if(tab==='smalltest')a=a.filter(p=>buyingDecision(p,settings).decision==='SMALL TEST');else if(tab==='kill')a=a.filter(p=>buyingDecision(p,settings).decision==='KILL');a.sort((x,y)=>sort==='profit'?profitWithSettings(y,settings).profit-profitWithSettings(x,settings).profit:sort==='kill'?buyingDecision(x,settings).killScore-buyingDecision(y,settings).killScore:buyingDecision(y,settings).readiness-buyingDecision(x,settings).readiness);$('#grid').innerHTML=a.length?a.map(card).join(''):'<div class="empty">Nu există produse pentru filtrele selectate.</div>';$('#total').textContent=products.length;$('#orderNow').textContent=products.filter(p=>buyingDecision(p,settings).decision==='ORDER NOW').length;$('#smallTest').textContent=products.filter(p=>buyingDecision(p,settings).decision==='SMALL TEST').length;$('#killCount').textContent=products.filter(p=>buyingDecision(p,settings).decision==='KILL').length;renderBuyingPlan();}
async function load(){const btn=$('#refresh');btn.disabled=true;$('#status').textContent='Se actualizează…';try{let live=null;const [lr,hr]=await Promise.all([fetch(`radar-live.json?t=${Date.now()}`,{cache:'no-store'}),fetch(`radar-history.json?t=${Date.now()}`,{cache:'no-store'}).catch(()=>null)]);if(lr.ok)live=await lr.json();if(hr?.ok)historyData=await hr.json();if(live?.live&&normalizeProducts(live.products).length){products=normalizeProducts(live.products);$('#source').textContent=`${live.engine||'Radar LIVE'} • ${n(live.successfulChecks)} checks`;$('#updated').textContent=new Date(live.updatedAt).toLocaleString('ro-RO');}else{const r=await fetch(`products.json?t=${Date.now()}`);products=normalizeProducts(await r.json());$('#source').textContent='Bază fallback';}$('#status').innerHTML='<span class="good">Online</span>';const cats=[...new Set(products.map(p=>p.cat))].sort();$('#category').innerHTML='<option value="">Toate categoriile</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('');render();}catch(e){$('#status').innerHTML=`<span class="error">Eroare: ${esc(e.message)}</span>`;}finally{btn.disabled=false;}}
if(typeof document!=='undefined'){const s=loadSettings();for(const [k,v] of Object.entries(s)){const el=$('#'+k);if(el)el.value=v;}const saved=n(localStorage.getItem(BUDGET_KEY));if(saved>0)$('#buyingBudget').value=saved;$('#search').addEventListener('input',render);$('#category').addEventListener('change',render);$('#sort').addEventListener('change',render);$('#refresh').addEventListener('click',load);$('#buyingBudget').addEventListener('input',()=>{localStorage.setItem(BUDGET_KEY,String(budgetValue()));renderBuyingPlan();});$$('[data-econ]').forEach(el=>el.addEventListener('input',()=>{saveSettings();render();}));$('#resetEconomics').addEventListener('click',()=>{for(const [k,v] of Object.entries(ECON_DEFAULTS))$('#'+k).value=v;saveSettings();render();});$('#grid').addEventListener('click',e=>{const b=e.target.closest('[data-watch]');if(b){e.preventDefault();toggleWatch(decodeURIComponent(b.dataset.watch));}});$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');tab=b.dataset.tab;render();}));load();}
