const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let products=[],tab='all',historyData={products:{}};
const WATCH_KEY='megaRadarWatchlistV1',BUDGET_KEY='megaRadarBuyingBudgetV1';
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const clamp=(v,min=0,max=100)=>Math.max(min,Math.min(max,n(v)));
const money=v=>`${n(v).toLocaleString('ro-RO',{maximumFractionDigits:2})} lei`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const keyOf=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
export function economics(p){const sell=n(p.sell),landed=n(p.landed),profit=sell/1.21-sell*.17-sell*.08-landed;return{profit,margin:sell?profit/sell*100:0,roi:landed?profit/landed*100:0};}
export function isBuyZone(product){const e=economics(product);return n(product.megaScore||product.score)>=82&&e.profit>=50&&e.margin>=20&&(!isKids(product)||String(product.kidsGate||'').toUpperCase()==='PASS');}
export function normalizeProducts(value){return Array.isArray(value)?value.filter(x=>x&&typeof x==='object'&&String(x.name||'').trim()).map(x=>({...x,name:String(x.name),cat:String(x.cat||'Fără categorie'),evidence:String(x.evidence||''),chinaMin:n(x.chinaMin),chinaMax:n(x.chinaMax),landed:n(x.landed),sell:n(x.sell),score:n(x.score),megaScore:n(x.megaScore||x.score),sourcing:Array.isArray(x.sourcing)?x.sourcing:[]})):[];}
function isKids(p){return /kids|copii|3.?6|0.?6/i.test(`${p.cat||''} ${p.age||''}`);}
function hasLiveSignal(p){return String(p.sourceStatus||'').toUpperCase()==='WEB_SIGNAL'&&n(p.marketScout?.checks)>=3&&n(p.marketScout?.foreignPresence)>=1;}
function fallbackAnalysis(p){const e=economics(p),foreign=n(p.marketScout?.foreignPresence),ro=n(p.marketScout?.romaniaPresence),china=n(p.marketScout?.chinaSourcingPresence),social=n(p.marketScout?.socialPresence),score=n(p.megaScore||p.score);const gap=clamp(55+foreign*12+china*8-ro*25),sat=ro?58:90,margin=clamp(e.margin*1.7+e.roi*.25),demand=clamp(40+foreign*18),trend=55,viral=clamp(n(p.social)||45+social*18);let action=String(p.action||p.verdict||'WATCH').toUpperCase();if(action==='BUY ZONE')action='BUY';if(action==='SAMPLE'||action==='VALIDATE')action='TEST';if(!['BUY','TEST','WATCH','REJECT'].includes(action))action=score>=82?'BUY':score>=76?'TEST':'WATCH';return{score,action,lifecycle:p.lifecycle||'WATCH',components:{demand,trend,romaniaGap:gap,saturation:sat,margin,viral,supplier:china?72:45,logistics:n(p.logistics)||78,compliance:n(p.compliance)||78},trendVelocity:{percent:null,label:'BASELINE'},economics:{...e,landed:n(p.landed),sell:n(p.sell)},testPlan:null};}
function analysis(p){return p.megaAnalysis||fallbackAnalysis(p);}
function actionOf(p){if(isKids(p)&&String(p.kidsGate||'').toUpperCase()!=='PASS'&&analysis(p).action==='BUY')return'TEST';return analysis(p).action||'WATCH';}
function historyOf(p){return p.historyPoints||historyData.products?.[keyOf(p.name)]?.points||[];}
function historyDelta(p){const pts=historyOf(p);return pts.length>1?n(pts.at(-1).score)-n(pts[0].score):0;}
export function buyingDecision(p){const a=analysis(p),e=a.economics||economics(p),comp=p.competitorIntel||{},hist=historyDelta(p),reviewSources=n(p.reviewIntel?.sourceCount),supplier=n(a.components?.supplier),compliance=n(a.components?.compliance),gap=n(a.components?.romaniaGap),sat=n(a.components?.saturation),viral=n(a.components?.viral),score=n(a.score||p.score);const competitionRisk=clamp(n(comp.resultProxy)*8),historyRisk=hist<0?clamp(Math.abs(hist)*8):0,reviewRisk=reviewSources?20:55;const killScore=Math.round(clamp((100-score)*.28+competitionRisk*.18+(100-supplier)*.18+(100-compliance)*.14+historyRisk*.12+reviewRisk*.10));const historyStrength=clamp(50+hist*5),profitStrength=clamp(e.margin*1.4+e.roi*.18);const readiness=Math.round(clamp(score*.34+gap*.15+profitStrength*.16+supplier*.11+sat*.08+viral*.06+historyStrength*.06+(reviewSources?75:45)*.04));let decision='WAIT',units=0;if(actionOf(p)==='REJECT'||killScore>=70||e.profit<10)decision='KILL';else if(actionOf(p)==='BUY'&&readiness>=76&&killScore<42&&e.profit>=35){decision='ORDER NOW';units=24;}else if(['BUY','TEST'].includes(actionOf(p))&&readiness>=64&&killScore<58&&e.profit>=20){decision='SMALL TEST';units=8;}const plan=a.testPlan;if(plan?.units&&decision==='ORDER NOW')units=Math.min(30,Math.max(12,n(plan.units)));if(plan?.units&&decision==='SMALL TEST')units=Math.min(10,Math.max(5,n(plan.units)));return{decision,readiness,killScore,units,investment:units*n(e.landed||p.landed),revenue:units*n(e.sell||p.sell),profitPotential:units*n(e.profit),historyDelta:hist};}
function link(site,name){const q=encodeURIComponent(name);return site==='Alibaba'?`https://www.alibaba.com/trade/search?SearchText=${q}`:site==='1688'?`https://s.1688.com/selloffer/offer_search.htm?keywords=${q}`:site==='eMAG'?`https://www.emag.ro/search/${q}`:site==='Amazon'?`https://www.amazon.de/s?k=${q}`:`https://www.trendyol.com/sr?q=${q}`;}
function tone(action){return action==='BUY'?'buy':action==='TEST'?'test':action==='REJECT'?'reject':'watch';}
function decisionTone(d){return d==='ORDER NOW'?'buy':d==='SMALL TEST'?'test':d==='KILL'?'reject':'watch';}
function component(label,value){const v=Math.round(clamp(value));return `<div class="component"><div><span>${esc(label)}</span><b>${v}</b></div><div class="bar"><i style="width:${v}%"></i></div></div>`;}
function watchSet(){try{return new Set(JSON.parse(localStorage.getItem(WATCH_KEY)||'[]'));}catch{return new Set();}}
function saveWatch(set){localStorage.setItem(WATCH_KEY,JSON.stringify([...set]));}
function watched(p){return typeof localStorage!=='undefined'&&watchSet().has(p.name);}
function toggleWatch(name){const set=watchSet();set.has(name)?set.delete(name):set.add(name);saveWatch(set);render();}
function budgetValue(){if(typeof document==='undefined')return 3000;const v=n($('#buyingBudget')?.value);return Math.max(0,v||3000);}
function saveBudget(){if(typeof localStorage!=='undefined')localStorage.setItem(BUDGET_KEY,String(budgetValue()));}
function deltaText(v,suffix=''){if(v==null)return'baseline';const x=n(v,-999,999);return`${x>0?'+':''}${x}${suffix}`;}
function sparkline(points){if(!Array.isArray(points)||points.length<2)return'<div class="nohistory">Istoricul începe la următoarele scanări.</div>';const vals=points.map(x=>clamp(x.score)),coords=vals.map((v,i)=>`${i*(100/(vals.length-1))},${38-v*.32}`).join(' ');return `<svg class="spark" viewBox="0 0 100 40" preserveAspectRatio="none" aria-label="Evoluție MEGA Score"><polyline points="${coords}"/></svg>`;}
function signals(p){const s=p.marketScout?.signals;if(!s)return'';const keys=[['amazonDE','Amazon DE',''],['allegroPL','Allegro PL',''],['trendyolTR','Trendyol',''],['emagRO','eMAG RO','ro'],['alibabaCN','Alibaba',''],['1688CN','1688',''],['tiktok','TikTok','social'],['pinterest','Pinterest','social'],['youtube','YouTube','social']];return `<div class="signals">${keys.map(([k,l,c])=>s[k]?`<span class="signal ${s[k]?.present?(c||'on'):''}">${esc(l)} ${s[k]?.present?'✓':'–'}</span>`:'').join('')}</div>`;}
function supplierBox(p,a){const s=p.supplierIntel||{},coverage=n(s.coverage),readiness=s.readiness||'NEVALIDAT';return `<div class="intelbox"><div><small>Supplier Intelligence</small><b>${esc(readiness)}</b></div><span>${coverage}/2 surse China • Alibaba ${n(s.alibabaResults)} • 1688 ${n(s.results1688)}</span><em>Supplier Score ${Math.round(n(a.components?.supplier))}/100. MOQ, rating, preț final și termeni se confirmă înainte de comandă.</em></div>`;}
function reviewBox(p){const r=p.reviewIntel||{},count=n(r.sourceCount),status=r.status||'NO REVIEW DATA';return `<div class="intelbox"><div><small>Review Intelligence</small><b>${esc(status)}</b></div><span>${count} surse • ${n(r.evidenceCount)} rezultate proxy</span><em>${esc(r.note||'Sentimentul nu este estimat fără citirea review-urilor.')}</em></div>`;}
function competitorBox(p){const c=p.competitorIntel||{},delta=c.delta;return `<div class="intelbox"><div><small>Competitor RO</small><b>${n(c.resultProxy)} proxy</b></div><span>${esc(c.status||'BASELINE')} • Δ ${deltaText(delta)}</span><em>${esc(c.note||'Proxy web, nu număr verificat de selleri.')}</em></div>`;}
function historyBox(p){const pts=historyOf(p),first=pts[0],last=pts.at(-1),delta=pts.length>1?n(last.score)-n(first.score):null;return `<div class="historybox"><div class="historyhead"><div><small>Istoric real</small><b>${pts.length} scanări</b></div><strong>${deltaText(delta,' pct')}</strong></div>${sparkline(pts)}<span>${pts.length?`MEGA ${n(first.score)} → ${n(last.score)}`:'Se colectează de la Faza 3'}</span></div>`;}
function decisionBox(p){const d=buyingDecision(p);return `<div class="decisionbox ${decisionTone(d.decision)}box"><div><span class="decisionbadge ${decisionTone(d.decision)}">${esc(d.decision)}</span><strong>Readiness ${d.readiness}/100</strong></div><div class="decisionmetrics"><span>Kill Score <b>${d.killScore}/100</b></span><span>Istoric <b>${deltaText(d.historyDelta,' pct')}</b></span></div>${d.units?`<p>${d.units} buc. • investiție ${money(d.investment)} • profit potențial ${money(d.profitPotential)}</p>`:`<p>${d.decision==='KILL'?'Nu aloca buget acestui produs acum.':'Așteaptă semnale mai puternice înainte de comandă.'}</p>`}</div>`;}
function why(p,a){const e=a.economics||economics(p),d=buyingDecision(p),items=[];if(d.readiness>=75)items.push(`Buying Readiness ${d.readiness}/100`);if(a.components?.romaniaGap>=70)items.push(`Romania Gap ${Math.round(a.components.romaniaGap)}/100`);if(a.components?.margin>=70)items.push(`profit ${money(e.profit)}/buc.`);if(p.supplierIntel?.coverage>=2)items.push('Alibaba + 1688 detectate');if(d.killScore<40)items.push(`Kill Score redus ${d.killScore}/100`);return items.slice(0,3).join(' • ')||'Necesită validare suplimentară înainte de comandă.';}
function alertMarkup(p){const a=p.radarAlert;if(!a?.active)return'';return `<div class="radar-alert"><b>🚨 ${esc(a.type||'ALERT')}</b><span>${esc(a.message||'Schimbare importantă detectată')}</span></div>`;}
function card(p){const a=analysis(p),e=a.economics||economics(p),action=actionOf(p),checked=p.marketScout?.checkedAt||p.lastChecked,isWatched=watched(p),encoded=encodeURIComponent(p.name),comp=p.competitorIntel||{},d=buyingDecision(p);return `<article class="card ${tone(action)}card">${alertMarkup(p)}<div class="top"><div><div class="name">${esc(p.name)}</div><div class="cat">${esc(p.cat||'Fără categorie')} • ${esc(a.lifecycle||'WATCH')}</div><span class="badge ${tone(action)}">${esc(action)}</span> <span class="decisionbadge ${decisionTone(d.decision)}">${esc(d.decision)}</span></div><div class="score"><small>MEGA 4.0</small>${Math.round(n(a.score||p.score))}<span>/100</span></div></div>
<div class="hero-metrics"><div><small>Buying Readiness</small><b>${d.readiness}/100</b></div><div><small>Kill Score</small><b>${d.killScore}/100</b></div><div><small>Profit / buc.</small><b>${money(e.profit)}</b><em>ROI ${n(e.roi).toFixed(0)}%</em></div><div><small>Competiție RO</small><b>${n(comp.resultProxy)} proxy</b><em>${esc(comp.status||'BASELINE')}</em></div></div>${decisionBox(p)}
<details><summary>Analiză completă</summary><p class="why">${esc(why(p,a))}</p><div class="components">${component('Demand',a.components?.demand)}${component('Trend',a.components?.trend)}${component('Romania Gap',a.components?.romaniaGap)}${component('Saturation',a.components?.saturation)}${component('Margin',a.components?.margin)}${component('Viral',a.components?.viral)}${component('Supplier',a.components?.supplier)}${component('Logistics',a.components?.logistics)}${component('Compliance',a.components?.compliance)}</div><div class="intelgrid">${supplierBox(p,a)}${competitorBox(p)}${reviewBox(p)}${historyBox(p)}</div></details>
<div class="metrics"><div class="metric"><small>Cost China</small><b>${money(p.chinaMin)} – ${money(p.chinaMax)}</b></div><div class="metric"><small>Landed</small><b>${money(e.landed||p.landed)}</b></div><div class="metric"><small>Preț RO</small><b>${money(e.sell||p.sell)}</b></div><div class="metric"><small>Marjă</small><b>${n(e.margin).toFixed(1)}%</b></div></div>${signals(p)}${checked?`<div class="validated">Ultima verificare: ${esc(new Date(checked).toLocaleString('ro-RO'))} • ${hasLiveSignal(p)?'semnal web live':'validare parțială'}</div>`:''}<div class="actions"><button class="watchbtn ${isWatched?'active':''}" data-watch="${esc(encoded)}">${isWatched?'★ În Watchlist':'☆ Watchlist'}</button><a target="_blank" rel="noopener" href="${link('Alibaba',p.name)}">Alibaba ↗</a><a target="_blank" rel="noopener" href="${link('1688',p.name)}">1688 ↗</a><a target="_blank" rel="noopener" href="${link('eMAG',p.name)}">eMAG ↗</a><a target="_blank" rel="noopener" href="${link('Amazon',p.name)}">Amazon ↗</a></div></article>`;}
function buyingPortfolio(budget){const candidates=products.map(p=>({p,d:buyingDecision(p)})).filter(x=>['ORDER NOW','SMALL TEST'].includes(x.d.decision)).sort((x,y)=>y.d.readiness-x.d.readiness||x.d.killScore-y.d.killScore);let remaining=budget;const items=[];for(const x of candidates){if(items.length>=10||remaining<=0)break;const landed=n(analysis(x.p).economics?.landed||x.p.landed),profit=n(analysis(x.p).economics?.profit||economics(x.p).profit),sell=n(analysis(x.p).economics?.sell||x.p.sell);if(landed<=0)continue;const cap=Math.max(landed*3,budget*.32),maxByCap=Math.floor(Math.min(remaining,cap)/landed),minUnits=x.d.decision==='ORDER NOW'?5:3,units=Math.min(x.d.units,maxByCap);if(units<minUnits)continue;const investment=units*landed;items.push({p:x.p,d:x.d,units,investment,revenue:units*sell,profitPotential:units*profit});remaining-=investment;}return{budget,remaining,investment:items.reduce((s,x)=>s+x.investment,0),revenue:items.reduce((s,x)=>s+x.revenue,0),profitPotential:items.reduce((s,x)=>s+x.profitPotential,0),items};}
function renderBuyingPlan(){const box=$('#buyingPlan');if(!box)return;const plan=buyingPortfolio(budgetValue());$('#allocated').textContent=money(plan.investment);$('#portfolioProfit').textContent=money(plan.profitPotential);$('#portfolioCount').textContent=plan.items.length;$('#budgetLeft').textContent=money(plan.remaining);box.innerHTML=plan.items.length?plan.items.map((x,i)=>`<div class="buyrow"><span>#${i+1}</span><div><b>${esc(x.p.name)}</b><small>${esc(x.d.decision)} • Readiness ${x.d.readiness} • Kill ${x.d.killScore}</small></div><div class="buyqty"><b>${x.units} buc.</b><small>${money(x.investment)}</small></div><strong>+${money(x.profitPotential)}</strong></div>`).join(''):'<div class="alertempty">Bugetul sau semnalele actuale nu produc încă o comandă recomandată. Nu forțăm o achiziție slabă.</div>';}
function normalize(a){return normalizeProducts(a);}
function renderTop(){const top=[...products].map(p=>({p,d:buyingDecision(p)})).sort((a,b)=>b.d.readiness-a.d.readiness).slice(0,3);$('#top3').innerHTML=top.map((x,i)=>`<div class="topitem"><span>#${i+1}</span><div><b>${esc(x.p.name)}</b><small>${esc(x.d.decision)} • Readiness ${x.d.readiness} • Kill ${x.d.killScore}</small></div><strong>${Math.round(n(analysis(x.p).score))}</strong></div>`).join('');}
function renderAlerts(){const alerts=products.filter(p=>p.radarAlert?.active).sort((a,b)=>n(analysis(b).score)-n(analysis(a).score)).slice(0,5);$('#alerts').innerHTML=alerts.length?alerts.map(p=>`<div class="alertitem"><b>${esc(p.name)}</b><span>${esc(p.radarAlert.message)}</span></div>`).join(''):'<div class="alertempty">Nicio alertă majoră la ultima scanare.</div>';}
function render(){const q=$('#search').value.trim().toLowerCase(),cat=$('#category').value,sort=$('#sort').value;let a=products.filter(p=>(!cat||p.cat===cat)&&(!q||`${p.name} ${p.cat}`.toLowerCase().includes(q)));if(tab==='watchlist')a=a.filter(watched);else if(tab==='order')a=a.filter(p=>buyingDecision(p).decision==='ORDER NOW');else if(tab==='smalltest')a=a.filter(p=>buyingDecision(p).decision==='SMALL TEST');else if(tab==='kill')a=a.filter(p=>buyingDecision(p).decision==='KILL');else if(tab!=='all')a=a.filter(p=>actionOf(p).toLowerCase()===tab);a.sort((x,y)=>sort==='readiness'?buyingDecision(y).readiness-buyingDecision(x).readiness:sort==='kill'?buyingDecision(x).killScore-buyingDecision(y).killScore:sort==='gap'?n(analysis(y).components?.romaniaGap)-n(analysis(x).components?.romaniaGap):sort==='profit'?n(analysis(y).economics?.profit)-n(analysis(x).economics?.profit):n(analysis(y).score)-n(analysis(x).score));$('#grid').innerHTML=a.length?a.map(card).join(''):'<div class="empty">Nu există produse pentru filtrele selectate.</div>';$('#total').textContent=products.length;$('#orderNow').textContent=products.filter(p=>buyingDecision(p).decision==='ORDER NOW').length;$('#smallTest').textContent=products.filter(p=>buyingDecision(p).decision==='SMALL TEST').length;$('#killCount').textContent=products.filter(p=>buyingDecision(p).decision==='KILL').length;renderTop();renderAlerts();renderBuyingPlan();}
async function load(){const btn=$('#refresh');btn.disabled=true;$('#status').textContent='Se actualizează…';try{let live=null;try{const [lr,hr]=await Promise.all([fetch(`radar-live.json?t=${Date.now()}`,{cache:'no-store'}),fetch(`radar-history.json?t=${Date.now()}`,{cache:'no-store'})]);if(lr.ok)live=await lr.json();if(hr.ok)historyData=await hr.json();}catch{}if(live?.live&&normalize(live.products).length){products=normalize(live.products);$('#source').textContent=`${live.engine||'Radar LIVE'} • ${n(live.successfulChecks)} checks`;$('#updated').textContent=live.updatedAt?new Date(live.updatedAt).toLocaleString('ro-RO'):'—';$('#status').innerHTML='<span class="good">Online</span>';}else{const r=await fetch(`products.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);products=normalize(await r.json());$('#source').textContent='Bază fallback';$('#updated').textContent='date de bază';$('#status').innerHTML='<span class="good">Online</span>';}const cats=[...new Set(products.map(p=>p.cat).filter(Boolean))].sort();$('#category').innerHTML='<option value="">Toate categoriile</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('');render();}catch(e){$('#status').innerHTML=`<span class="error">Eroare: ${esc(e.message)}</span>`;$('#grid').innerHTML='<div class="empty">Datele nu s-au putut încărca. Apasă Refresh.</div>';}finally{btn.disabled=false;}}
if(typeof document!=='undefined'){const saved=typeof localStorage!=='undefined'?n(localStorage.getItem(BUDGET_KEY)):0;if(saved>0)$('#buyingBudget').value=saved;$('#search').addEventListener('input',render);$('#category').addEventListener('change',render);$('#sort').addEventListener('change',render);$('#refresh').addEventListener('click',load);$('#buyingBudget').addEventListener('input',()=>{saveBudget();renderBuyingPlan();});$('#grid').addEventListener('click',e=>{const b=e.target.closest('[data-watch]');if(b){e.preventDefault();toggleWatch(decodeURIComponent(b.dataset.watch));}});$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');tab=b.dataset.tab;render();}));load();}
