const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let products=[],tab='all',historyData={products:{}};
const WATCH_KEY='megaRadarWatchlistV1';
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const clamp=(v,min=0,max=100)=>Math.max(min,Math.min(max,n(v)));
const money=v=>`${n(v).toLocaleString('ro-RO',{maximumFractionDigits:2})} lei`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const keyOf=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
export function economics(p){const sell=n(p.sell),landed=n(p.landed),profit=sell/1.21-sell*.17-sell*.08-landed;return{profit,margin:sell?profit/sell*100:0,roi:landed?profit/landed*100:0};}
export function isBuyZone(product){const e=economics(product);return n(product.megaScore||product.score)>=82&&e.profit>=50&&e.margin>=20&&(!isKids(product)||String(product.kidsGate||'').toUpperCase()==='PASS');}
export function normalizeProducts(value){return Array.isArray(value)?value.filter(x=>x&&typeof x==='object'&&String(x.name||'').trim()).map(x=>({...x,name:String(x.name),cat:String(x.cat||'Fără categorie'),evidence:String(x.evidence||''),chinaMin:n(x.chinaMin),chinaMax:n(x.chinaMax),landed:n(x.landed),sell:n(x.sell),score:n(x.score),megaScore:n(x.megaScore||x.score),sourcing:Array.isArray(x.sourcing)?x.sourcing:[]})):[];}
function isKids(p){return /kids|copii|3.?6|0.?6/i.test(`${p.cat||''} ${p.age||''}`);}
function hasLiveSignal(p){return String(p.sourceStatus||'').toUpperCase()==='WEB_SIGNAL'&&n(p.marketScout?.checks)>=3&&n(p.marketScout?.foreignPresence)>=1;}
function fallbackAnalysis(p){const e=economics(p),foreign=n(p.marketScout?.foreignPresence),ro=n(p.marketScout?.romaniaPresence),china=n(p.marketScout?.chinaSourcingPresence),social=n(p.marketScout?.socialPresence),score=n(p.megaScore||p.score);const gap=clamp(55+foreign*12+china*8-ro*25),sat=ro?58:90,margin=clamp(e.margin*1.7+e.roi*.25),demand=clamp(40+foreign*18),trend=55,viral=clamp(n(p.social)||45+social*18);let action=String(p.action||p.verdict||'WATCH').toUpperCase();if(action==='BUY ZONE')action='BUY';if(action==='SAMPLE'||action==='VALIDATE')action='TEST';if(!['BUY','TEST','WATCH','REJECT'].includes(action))action=score>=82?'BUY':score>=76?'TEST':'WATCH';return{score,action,lifecycle:p.lifecycle||'WATCH',components:{demand,trend,romaniaGap:gap,saturation:sat,margin,viral,supplier:china?72:45,logistics:n(p.logistics)||78,compliance:n(p.compliance)||78},trendVelocity:{percent:null,label:'BASELINE'},economics:{...e,landed:n(p.landed),sell:n(p.sell)},testPlan:null};}
function analysis(p){return p.megaAnalysis||fallbackAnalysis(p);}
function actionOf(p){if(isKids(p)&&String(p.kidsGate||'').toUpperCase()!=='PASS'&&analysis(p).action==='BUY')return'TEST';return analysis(p).action||'WATCH';}
function link(site,name){const q=encodeURIComponent(name);return site==='Alibaba'?`https://www.alibaba.com/trade/search?SearchText=${q}`:site==='1688'?`https://s.1688.com/selloffer/offer_search.htm?keywords=${q}`:site==='eMAG'?`https://www.emag.ro/search/${q}`:site==='Amazon'?`https://www.amazon.de/s?k=${q}`:`https://www.trendyol.com/sr?q=${q}`;}
function tone(action){return action==='BUY'?'buy':action==='TEST'?'test':action==='REJECT'?'reject':'watch';}
function component(label,value){const v=Math.round(clamp(value));return `<div class="component"><div><span>${esc(label)}</span><b>${v}</b></div><div class="bar"><i style="width:${v}%"></i></div></div>`;}
function watchSet(){try{return new Set(JSON.parse(localStorage.getItem(WATCH_KEY)||'[]'));}catch{return new Set();}}
function saveWatch(set){localStorage.setItem(WATCH_KEY,JSON.stringify([...set]));}
function watched(p){return typeof localStorage!=='undefined'&&watchSet().has(p.name);}
function toggleWatch(name){const set=watchSet();set.has(name)?set.delete(name):set.add(name);saveWatch(set);render();}
function historyOf(p){return p.historyPoints||historyData.products?.[keyOf(p.name)]?.points||[];}
function deltaText(v,suffix=''){if(v==null)return'baseline';const x=n(v,-999,999);return`${x>0?'+':''}${x}${suffix}`;}
function sparkline(points){if(!Array.isArray(points)||points.length<2)return'<div class="nohistory">Istoricul începe la următoarele scanări.</div>';const vals=points.map(x=>clamp(x.score)),coords=vals.map((v,i)=>`${i*(100/(vals.length-1))},${38-v*.32}`).join(' ');return `<svg class="spark" viewBox="0 0 100 40" preserveAspectRatio="none" aria-label="Evoluție MEGA Score"><polyline points="${coords}"/></svg>`;}
function signals(p){const s=p.marketScout?.signals;if(!s)return'';const keys=[['amazonDE','Amazon DE',''],['allegroPL','Allegro PL',''],['trendyolTR','Trendyol',''],['emagRO','eMAG RO','ro'],['alibabaCN','Alibaba',''],['1688CN','1688',''],['tiktok','TikTok','social'],['pinterest','Pinterest','social'],['youtube','YouTube','social']];return `<div class="signals">${keys.map(([k,l,c])=>s[k]?`<span class="signal ${s[k]?.present?(c||'on'):''}">${esc(l)} ${s[k]?.present?'✓':'–'}</span>`:'').join('')}</div>`;}
function supplierBox(p,a){const s=p.supplierIntel||{},coverage=n(s.coverage),readiness=s.readiness||'NEVALIDAT';return `<div class="intelbox"><div><small>Supplier Intelligence</small><b>${esc(readiness)}</b></div><span>${coverage}/2 surse China • Alibaba ${n(s.alibabaResults)} • 1688 ${n(s.results1688)}</span><em>Supplier Score ${Math.round(n(a.components?.supplier))}/100. MOQ, rating, preț final și termeni se confirmă înainte de comandă.</em></div>`;}
function reviewBox(p){const r=p.reviewIntel||{},count=n(r.sourceCount),status=r.status||'NO REVIEW DATA';return `<div class="intelbox"><div><small>Review Intelligence</small><b>${esc(status)}</b></div><span>${count} surse • ${n(r.evidenceCount)} rezultate proxy</span><em>${esc(r.note||'Sentimentul nu este estimat fără citirea review-urilor.')}</em></div>`;}
function competitorBox(p){const c=p.competitorIntel||{},delta=c.delta;return `<div class="intelbox"><div><small>Competitor RO</small><b>${n(c.resultProxy)} proxy</b></div><span>${esc(c.status||'BASELINE')} • Δ ${deltaText(delta)}</span><em>${esc(c.note||'Proxy web, nu număr verificat de selleri.')}</em></div>`;}
function historyBox(p){const pts=historyOf(p),first=pts[0],last=pts.at(-1),delta=pts.length>1?n(last.score)-n(first.score):null;return `<div class="historybox"><div class="historyhead"><div><small>Istoric real</small><b>${pts.length} scanări</b></div><strong>${deltaText(delta,' pct')}</strong></div>${sparkline(pts)}<span>${pts.length?`MEGA ${n(first.score)} → ${n(last.score)}`:'Se colectează de la Faza 3'}</span></div>`;}
function why(p,a){const e=a.economics||economics(p),items=[];if(a.components?.romaniaGap>=70)items.push(`Romania Gap ${Math.round(a.components.romaniaGap)}/100`);if(a.components?.viral>=65)items.push(`Viral ${Math.round(a.components.viral)}/100`);if(a.components?.saturation>=70)items.push('competiție RO estimată redusă');if(a.components?.margin>=70)items.push(`profit ${money(e.profit)}/buc.`);if(p.supplierIntel?.coverage>=2)items.push('Alibaba + 1688 detectate');return items.slice(0,3).join(' • ')||'Necesită validare suplimentară înainte de comandă.';}
function alertMarkup(p){const a=p.radarAlert;if(!a?.active)return'';return `<div class="radar-alert"><b>🚨 ${esc(a.type||'ALERT')}</b><span>${esc(a.message||'Schimbare importantă detectată')}</span></div>`;}
function card(p){const a=analysis(p),e=a.economics||economics(p),action=actionOf(p),checked=p.marketScout?.checkedAt||p.lastChecked,plan=a.testPlan,isWatched=watched(p),encoded=encodeURIComponent(p.name),comp=p.competitorIntel||{};return `<article class="card ${tone(action)}card">${alertMarkup(p)}<div class="top"><div><div class="name">${esc(p.name)}</div><div class="cat">${esc(p.cat||'Fără categorie')} • ${esc(a.lifecycle||'WATCH')}</div><span class="badge ${tone(action)}">${esc(action)}</span></div><div class="score"><small>MEGA 3.0</small>${Math.round(n(a.score||p.score))}<span>/100</span></div></div>
<div class="hero-metrics"><div><small>Romania Gap</small><b>${Math.round(n(a.components?.romaniaGap))}/100</b></div><div><small>Viral</small><b>${Math.round(n(a.components?.viral))}/100</b></div><div><small>Profit / buc.</small><b>${money(e.profit)}</b><em>ROI ${n(e.roi).toFixed(0)}%</em></div><div><small>Competiție RO</small><b>${n(comp.resultProxy)} proxy</b><em>${esc(comp.status||'BASELINE')} ${comp.delta==null?'':deltaText(comp.delta)}</em></div></div>
<details><summary>Analiză completă</summary><p class="why">${esc(why(p,a))}</p><div class="components">${component('Demand',a.components?.demand)}${component('Trend',a.components?.trend)}${component('Romania Gap',a.components?.romaniaGap)}${component('Saturation',a.components?.saturation)}${component('Margin',a.components?.margin)}${component('Viral',a.components?.viral)}${component('Supplier',a.components?.supplier)}${component('Logistics',a.components?.logistics)}${component('Compliance',a.components?.compliance)}</div><div class="intelgrid">${supplierBox(p,a)}${competitorBox(p)}${reviewBox(p)}${historyBox(p)}</div></details>
<div class="metrics"><div class="metric"><small>Cost China</small><b>${money(p.chinaMin)} – ${money(p.chinaMax)}</b></div><div class="metric"><small>Landed</small><b>${money(e.landed||p.landed)}</b></div><div class="metric"><small>Preț RO</small><b>${money(e.sell||p.sell)}</b></div><div class="metric"><small>Marjă</small><b>${n(e.margin).toFixed(1)}%</b></div></div>
${plan?`<div class="testplan"><b>Test recomandat: ${n(plan.units)} buc.</b><span>Investiție ${money(plan.investment)} • Profit potențial ${money(plan.profitPotential)}</span></div>`:''}${signals(p)}${checked?`<div class="validated">Ultima verificare: ${esc(new Date(checked).toLocaleString('ro-RO'))} • ${hasLiveSignal(p)?'semnal web live':'validare parțială'}</div>`:''}
<div class="actions"><button class="watchbtn ${isWatched?'active':''}" data-watch="${esc(encoded)}">${isWatched?'★ În Watchlist':'☆ Watchlist'}</button><a target="_blank" rel="noopener" href="${link('Alibaba',p.name)}">Alibaba ↗</a><a target="_blank" rel="noopener" href="${link('1688',p.name)}">1688 ↗</a><a target="_blank" rel="noopener" href="${link('eMAG',p.name)}">eMAG ↗</a><a target="_blank" rel="noopener" href="${link('Amazon',p.name)}">Amazon ↗</a></div></article>`;}
function normalize(a){return normalizeProducts(a);}
function renderTop(){const top=[...products].sort((a,b)=>n(analysis(b).score)-n(analysis(a).score)).slice(0,3);$('#top3').innerHTML=top.map((p,i)=>`<div class="topitem"><span>#${i+1}</span><div><b>${esc(p.name)}</b><small>${esc(actionOf(p))} • Gap ${Math.round(n(analysis(p).components?.romaniaGap))} • Supplier ${Math.round(n(analysis(p).components?.supplier))}</small></div><strong>${Math.round(n(analysis(p).score))}</strong></div>`).join('');}
function renderAlerts(){const alerts=products.filter(p=>p.radarAlert?.active).sort((a,b)=>n(analysis(b).score)-n(analysis(a).score)).slice(0,5);$('#alerts').innerHTML=alerts.length?alerts.map(p=>`<div class="alertitem"><b>${esc(p.name)}</b><span>${esc(p.radarAlert.message)}</span></div>`).join(''):'<div class="alertempty">Nicio alertă majoră la ultima scanare.</div>';}
function render(){const q=$('#search').value.trim().toLowerCase(),cat=$('#category').value,sort=$('#sort').value;let a=products.filter(p=>(!cat||p.cat===cat)&&(!q||`${p.name} ${p.cat}`.toLowerCase().includes(q)));if(tab==='watchlist')a=a.filter(watched);else if(tab!=='all')a=a.filter(p=>actionOf(p).toLowerCase()===tab);a.sort((x,y)=>sort==='gap'?n(analysis(y).components?.romaniaGap)-n(analysis(x).components?.romaniaGap):sort==='supplier'?n(analysis(y).components?.supplier)-n(analysis(x).components?.supplier):sort==='competition'?n(x.competitorIntel?.resultProxy)-n(y.competitorIntel?.resultProxy):sort==='profit'?n(analysis(y).economics?.profit)-n(analysis(x).economics?.profit):n(analysis(y).score)-n(analysis(x).score));$('#grid').innerHTML=a.length?a.map(card).join(''):'<div class="empty">Nu există produse pentru filtrele selectate.</div>';$('#total').textContent=products.length;$('#buy').textContent=products.filter(p=>actionOf(p)==='BUY').length;$('#watchCount').textContent=products.filter(watched).length;$('#historyCount').textContent=products.filter(p=>historyOf(p).length>=2).length;$('#reviewCount').textContent=products.filter(p=>n(p.reviewIntel?.sourceCount)>0).length;renderTop();renderAlerts();}
async function load(){const btn=$('#refresh');btn.disabled=true;$('#status').textContent='Se actualizează…';try{let live=null;try{const [lr,hr]=await Promise.all([fetch(`radar-live.json?t=${Date.now()}`,{cache:'no-store'}),fetch(`radar-history.json?t=${Date.now()}`,{cache:'no-store'})]);if(lr.ok)live=await lr.json();if(hr.ok)historyData=await hr.json();}catch{}if(live?.live&&normalize(live.products).length){products=normalize(live.products);$('#source').textContent=`${live.engine||'Radar LIVE'} • ${n(live.successfulChecks)} checks`;$('#updated').textContent=live.updatedAt?new Date(live.updatedAt).toLocaleString('ro-RO'):'—';$('#status').innerHTML='<span class="good">Online</span>';}else{const r=await fetch(`products.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);products=normalize(await r.json());$('#source').textContent='Bază fallback';$('#updated').textContent='date de bază';$('#status').innerHTML='<span class="good">Online</span>';}products=products.map(p=>({...p,historyPoints:historyData.products?.[keyOf(p.name)]?.points||[]}));const cats=[...new Set(products.map(p=>p.cat).filter(Boolean))].sort();$('#category').innerHTML='<option value="">Toate categoriile</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('');render();}catch(e){$('#status').innerHTML=`<span class="error">Eroare: ${esc(e.message)}</span>`;$('#grid').innerHTML='<div class="empty">Datele nu s-au putut încărca. Apasă Refresh.</div>';}finally{btn.disabled=false;}}
if(typeof document!=='undefined'){$('#search').addEventListener('input',render);$('#category').addEventListener('change',render);$('#sort').addEventListener('change',render);$('#refresh').addEventListener('click',load);$('#grid').addEventListener('click',e=>{const b=e.target.closest('[data-watch]');if(b){e.preventDefault();toggleWatch(decodeURIComponent(b.dataset.watch));}});$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');tab=b.dataset.tab;render();}));load();}
