import {getCurrentSession} from './supabase-client.js';
import {getActiveWorkspace,ensurePersonalWorkspace} from './workspace-client.js';

const PAID_PLANS=['DISCOVER','RADAR','LAUNCH'];
const ATTEMPT_PREFIX='mpr_checkout_attempt_v1_';

async function authSession(){const session=await getCurrentSession();if(!session?.access_token)throw new Error('Autentificare necesară.');return session;}
async function billingFetch(path,options={}){const session=await authSession();const workspace=await getActiveWorkspace()||await ensurePersonalWorkspace('My Radar');if(!workspace?.id)throw new Error('Workspace-ul de billing nu este disponibil.');const response=await fetch(path,{...options,headers:{...(options.headers||{}),authorization:`Bearer ${session.access_token}`,'x-mpr-workspace-id':workspace.id}});const data=await response.json().catch(()=>({}));return {response,data};}
function storage(){try{return typeof sessionStorage!=='undefined'?sessionStorage:null;}catch{return null;}}
function randomAttemptId(){if(globalThis.crypto?.randomUUID)return globalThis.crypto.randomUUID();return `${Date.now().toString(36)}_${Math.random().toString(36).slice(2)}_${Math.random().toString(36).slice(2)}`;}
function checkoutAttemptKey(plan){return `${ATTEMPT_PREFIX}${String(plan||'').toUpperCase()}`;}
export function getSubscriptionCheckoutAttempt(plan){const code=String(plan||'').toUpperCase();if(!PAID_PLANS.includes(code))throw new Error('Plan de abonament invalid.');const store=storage(),key=checkoutAttemptKey(code);let value=store?.getItem(key)||'';if(!/^[A-Za-z0-9_-]{16,100}$/.test(value)){value=randomAttemptId().replace(/[^A-Za-z0-9_-]/g,'_').slice(0,100);store?.setItem(key,value);}return value;}
export function resetSubscriptionCheckoutAttempt(plan=null){const store=storage();if(!store)return;const codes=plan?[String(plan).toUpperCase()]:PAID_PLANS;for(const code of codes)if(PAID_PLANS.includes(code))store.removeItem(checkoutAttemptKey(code));}
export async function startSubscriptionCheckout(plan){const code=String(plan||'').toUpperCase();if(!PAID_PLANS.includes(code))throw new Error('Plan de abonament invalid.');const session=await getCurrentSession();if(!session?.access_token){location.href=`login.html?next=${encodeURIComponent('pricing.html?plan='+code)}`;return null;}const checkoutAttemptId=getSubscriptionCheckoutAttempt(code);const first=await billingFetch('/api/billing/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({plan:code,checkoutAttemptId})});if(first.response.ok&&first.data?.url){location.href=first.data.url;return first.data;}if(first.response.status===409&&first.data?.code==='ALREADY_ON_PLAN'){resetSubscriptionCheckoutAttempt(code);location.href='account.html?billing=already';return first.data;}if(first.response.status===409&&first.data?.code==='ACTIVE_SUBSCRIPTION_EXISTS'){resetSubscriptionCheckoutAttempt(code);const changed=await billingFetch('/api/billing/change-plan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({plan:code})});if(!changed.response.ok)throw new Error(changed.data?.error||'Schimbarea planului nu a reușit.');location.href=`account.html?billing=changed&plan=${encodeURIComponent(code)}`;return changed.data;}throw new Error(first.data?.error||'Checkout indisponibil momentan.');}
export async function getBillingStatus(){const {response,data}=await billingFetch('/api/billing/status',{cache:'no-store'});if(!response.ok)throw new Error(data?.error||'Statusul abonamentului nu este disponibil.');return data;}
export async function cancelSubscription(){const {response,data}=await billingFetch('/api/billing/cancel',{method:'POST'});if(!response.ok)throw new Error(data?.error||'Anularea abonamentului nu a reușit.');return data;}
export async function resumeSubscription(){const {response,data}=await billingFetch('/api/billing/resume',{method:'POST'});if(!response.ok)throw new Error(data?.error||'Retragerea anulării nu a reușit.');return data;}
