import {getCurrentSession} from './supabase-client.js';
import {applyPrivateCommercialDecisions} from './commercial-decision-client.js';
import {roCategory,roProductName} from './product-ro.js';
import {saveToCommercialWatchlist} from './commercial-watchlist.js';
import {trackJourneyEvent} from './journey-events.js';

const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const money=v=>v===null||v===undefined?'—':`${Number(v).toLocaleString('ro-RO',{maximumFractionDigits:2})} lei`;
const gateLabels={demandReady:'Cerere România',pricingVerified:'Preț România',estimatedSalesReady:'Dovezi vânzări',supplierVerified:'Furnizor verificat',reviewVerified:'Dovezi review',marketEvidence:'Dovezi piață',economicsHealthy:'Economics',confidenceReady:'Încredere date',trendSafe:'Trend'};
function scoreOf(p){return n(p?.launchScore?.score||p?.launchScore?.total||p?.opportunityRanking?.score||p?.opportunityRankingV2?.score||p?.score);}
function scoreLabel(p){return p?.launchScore||p?.opportunityRanking||p?.opportunityRankingV2?'Scor oportunitate':'Scor derivat';}
function gapText(p){const g=p.romaniaGap2||{};const verified=g.label||g.status||(n(g.opportunityScore)>0?`${Math.round(n(g.opportunityScore))}/100`:'');if(verified)return verified;const proxy=n(p?.derivedRomaniaGap?.score);return proxy>0?`DERIVED ${Math.round(proxy)}/100`:'—';}
function badgeClass(action){return action==='BUY'?'buy':action==='TEST'?'test':'hold';}
function image(p,name){const url=String(p.imageUrl||'');if(!/^https?:\/\//i.test(url))return '<div class="media">Fără imagine verificată</div>';return `<div class="media"><img src="${esc(url)}" alt="${esc(name)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.parentElement.textContent='Fără imagine verificată'"></div>`;}
function salesLabel(d){const e=d.estimationEvidence||{};const status=String(e.salesEstimateStatus||'UNKNOWN');if(status==='ACTUAL_OBSERVED')return {label:'VERIFIED',className:'verified',text:'Vânzări observate'};if(status==='ESTIMATED_HIGH_CONFIDENCE')return {label:'ESTIMATED',className:'estimated',text:`Estimare cu încredere ridicată ${n(e.salesEstimateConfidence)}%`};return {label:'DERIVED',className:'derived',text:'Dovezi de vânzări insuficiente'};}
function row(label,value){return `<div class="row"><span>${esc(label)}</span><b>${esc(value)}</b></div>`;}
function render(p){const d=p.testBuyDecision||{},e=d.economics||{},name=roProductName(p.name),cat=roCategory(p.cat||''),sales=salesLabel(d),gates=d.gates||{};const blockers=Array.isArray(d.blockers)?d.blockers:[];const action=String(d.commercialAction||'HOLD');const moneyReady=Boolean(d.landedCostConfirmed&&e?.profit!=null);$('#app').innerHTML=`
<section class="card hero"><div>${image(p,name)}</div><div class="product"><h1>${esc(name)}</h1><div class="muted">${esc(cat||p.cat||'Categorie')} · România Gap ${esc(gapText(p))}</div><span class="badge ${badgeClass(action)}">${esc(d.verdict||action)}</span><span class="badge ${sales.className}">${sales.label}</span><span class="badge derived">${n(d.passedGates)}/9 gate-uri</span></div></section>
<section class="card"><div class="metrics"><div class="metric"><small>${esc(scoreLabel(p))}</small><b>${Math.round(scoreOf(p))}</b></div><div class="metric"><small>Grad de validare</small><b>${Math.round(n(d.commercialReadiness))}%</b></div><div class="metric"><small>Preț țintă</small><b>${d.targetSalePrice!=null?money(d.targetSalePrice):'—'}</b></div><div class="metric"><small>Landed cost</small><b>${d.landedCostConfirmed?money(d.unitLandedCost):'NECONFIRMAT'}</b></div><div class="metric"><small>Profit / buc.</small><b>${moneyReady?money(e.profit):'—'}</b></div><div class="metric"><small>Marjă</small><b>${moneyReady?`${n(e.margin).toFixed(1)}%`:'—'}</b></div><div class="metric"><small>ROI</small><b>${moneyReady?`${n(e.roi).toFixed(0)}%`:'—'}</b></div><div class="metric"><small>Cantitate TEST</small><b>${['TEST','BUY'].includes(action)&&n(d.quantity)>0?`${n(d.quantity)} buc.`:'—'}</b></div></div></section>
<section class="card"><h2 class="section-title">Cele 9 gate-uri comerciale</h2><div class="gates">${Object.entries(gateLabels).map(([key,label])=>`<div class="gate ${gates[key]?'ok':'no'}">${gates[key]?'✓':'○'} ${esc(label)}</div>`).join('')}</div></section>
<section class="grid2"><section class="card"><h2 class="section-title">Dovezi & România</h2>${row('România Gap',gapText(p))}${row('Validare vânzări',sales.text)}${row('Încredere estimare',d.estimationEvidence?.salesEstimateConfidence!=null?`${n(d.estimationEvidence.salesEstimateConfidence)}%`:'—')}${row('Încredere date',p.dataConfidence?.overall!=null?`${n(p.dataConfidence.overall)}%`:'—')}${row('Trend',p.trendIntelligence?.status||'—')}${row('Dovezi piață',gates.marketEvidence?'PASS':'HOLD')}</section><section class="card"><h2 class="section-title">Furnizor & bani</h2>${row('Furnizor',gates.supplierVerified?'VERIFICAT':'NECONFIRMAT')}${row('Landed cost',d.landedCostConfirmed?'CONFIRMAT':'NECONFIRMAT')}${row('Preț România',gates.pricingVerified?'VERIFICAT':'NECONFIRMAT')}${row('Economics',gates.economicsHealthy?'PASS':'HOLD')}${row('Buget TEST',d.testBudget!=null?money(d.testBudget):'—')}${row('Verdict financiar',moneyReady?'CALCULAT PE COST CONFIRMAT':'NU RECOMANDĂM BANI')}</section></section>
<section class="card"><h2 class="section-title">Ce blochează produsul</h2>${blockers.length?blockers.map(x=>`<div class="row"><span>○</span><b>${esc(x)}</b></div>`).join(''):'<div class="row"><span>Stare</span><b>Niciun blocker în decizia curentă.</b></div>'}</section>
<section class="card"><div class="next"><b>Următorul pas recomandat:</b><br>${esc(d.nextAction||'Continuă validarea înainte de bani.')}</div><div class="integrity" style="margin-top:12px"><b>Regulă de integritate:</b> estimările nu sunt prezentate ca vânzări verificate. Scorurile și România Gap provenite din snapshot-ul legacy rămân marcate DERIVED și nu trec gate-uri comerciale. Profitul și ROI-ul sunt folosite pentru recomandări de bani numai când landed cost este confirmat. BUY necesită feedback dintr-un test real finalizat.</div><div class="actions customer-actions" style="margin-top:12px"><button id="watch" class="primary primary-action">Urmărește produsul</button>${action==='TEST'?'<a class="good" href="test-buy.html">Pregătește TEST</a>':''}<a href="supplier-intelligence.html">Furnizor</a><a href="landed-cost.html">Landed cost</a><a href="commercial-radar.html">Înapoi la Radar</a></div></section>`;
$('#watch')?.addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;try{await saveToCommercialWatchlist(p,'WATCHING');button.textContent='Salvat în Watchlist';trackJourneyEvent('WATCHLIST_ADD',{product:p.name,action});}catch(error){button.textContent='Nu s-a putut salva';setTimeout(()=>{button.disabled=false;button.textContent='Urmărește produsul';},1800);}});
}
async function load(){try{const session=await getCurrentSession();if(!session){location.href='login.html?next='+encodeURIComponent(location.pathname+location.search);return;}const response=await fetch('/api/commercial/radar',{headers:{authorization:`Bearer ${session.access_token}`},cache:'no-store'});const data=await response.json();if(response.status===403){location.href='pricing.html?upgrade=RADAR';return;}if(!response.ok)throw new Error(data.error||'Radar indisponibil');const list=await applyPrivateCommercialDecisions(Array.isArray(data.products)?data.products:[]);const wanted=new URLSearchParams(location.search).get('product')||'';const product=list.find(p=>String(p.name)===wanted)||list.find(p=>String(p.name).toLowerCase()===wanted.toLowerCase())||null;if(!product)throw new Error('Produsul nu a fost găsit în Radarul comercial curent.');render(product);trackJourneyEvent('COMMERCIAL_PRODUCT_VIEW',{product:product.name,action:product.testBuyDecision?.commercialAction||'HOLD'});}catch(error){$('#app').innerHTML=`<section class="card customer-empty"><h3>Dosarul comercial nu este disponibil</h3><p>${esc(error?.message||error)}</p><a href="commercial-radar.html">Înapoi la Radar</a></section>`;}}
load();
