import {getCurrentSession} from './supabase-client.js';
import {applyPrivateCommercialDecisions} from './commercial-decision-client.js';
import {roCategory,roProductName} from './product-ro.js';
import {trackJourneyEvent,installJourneyLinkTracking} from './journey-events.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const safeUrl=u=>{try{const x=new URL(String(u||''),location.href);return['http:','https:'].includes(x.protocol)?x.href:'#';}catch{return'#';}};
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const money=v=>v===null||v===undefined?'—':`${Number(v).toLocaleString('ro-RO',{maximumFractionDigits:2})} lei`;
let products=[];
function scoreOf(p){return n(p?.launchScore?.score||p?.launchScore?.total||p?.opportunityRanking?.score||p?.opportunityRankingV2?.score||p?.discoveryAnalysis?.score||p?.score);}
function scoreLabel(p){return p?.launchScore||p?.opportunityRanking||p?.opportunityRankingV2||p?.discoveryAnalysis?'SCOR OPORTUNITATE':'SCOR DERIVAT';}
function gapOf(p){const g=p.romaniaGap2||{};const verified=g.label||g.status||(n(g.opportunityScore)>0?`${Math.round(n(g.opportunityScore))}/100`:'');if(verified)return verified;const proxy=n(p?.derivedRomaniaGap?.score);return proxy>0?`DERIVED ${Math.round(proxy)}/100`:'—';}
function image(p,name){const src=safeUrl(p.imageUrl);return src==='#'?'<div class="media">Fără imagine verificată</div>':`<div class="media"><img src="${esc(src)}" alt="${esc(name)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.parentElement.textContent='Fără imagine verificată'"></div>`;}
function verdictClass(a){return a==='BUY'?'vbuy':a==='TEST'?'vtest':'vhold';}
const gateLabels={demandReady:'Cerere România',pricingVerified:'Preț România',estimatedSalesReady:'Dovezi vânzări',supplierVerified:'Furnizor verificat',reviewVerified:'Dovezi review',marketEvidence:'Dovezi piață',economicsHealthy:'Economics',confidenceReady:'Încredere date',trendSafe:'Trend'};
function card(p){const d=p.testBuyDecision||{},econ=d.economics||{},name=roProductName(p.name),cat=roCategory(p.cat||''),sales=d.estimationEvidence||{};const productUrl=`commercial-product.html?product=${encodeURIComponent(p.name)}`;return `<article class="card"><div class="top"><div class="product">${image(p,name)}<div class="copy"><h3>${esc(name)}</h3><small>${esc(cat||p.cat||'Categorie')} · România Gap: ${esc(gapOf(p))}</small><br><span class="verdict ${verdictClass(d.commercialAction)}">${esc(d.verdict||'HOLD')}</span></div></div><div class="score">${scoreOf(p)}<small>${esc(scoreLabel(p))}</small></div></div><div class="metrics preview-metrics"><div class="metric"><small>Grad de validare</small><b>${Math.round(n(d.commercialReadiness))}%</b></div><div class="metric"><small>Gate-uri trecute</small><b>${n(d.passedGates)}/9</b></div><div class="metric"><small>Landed cost</small><b>${d.landedCostConfirmed?money(d.unitLandedCost):'NECONFIRMAT'}</b></div><div class="metric"><small>Verdict</small><b>${esc(d.commercialAction||'HOLD')}</b></div></div><div class="next"><b>Următorul pas:</b> ${esc(d.nextAction||'Continuă validarea.')}</div><div class="actions customer-actions"><a class="primary primary-action" data-journey-event="RADAR_OPEN_PRODUCT" href="${productUrl}">Vezi dosarul comercial</a><a href="commercial-watchlist.html">Watchlist</a></div><details class="radar-details"><summary>Vezi toate dovezile și gate-urile</summary><div class="metrics"><div class="metric"><small>Preț țintă</small><b>${money(d.targetSalePrice)}</b></div><div class="metric"><small>Profit / buc.</small><b>${econ?.profit!=null?money(econ.profit):'—'}</b></div><div class="metric"><small>Marjă / ROI</small><b>${econ?.margin!=null?`${n(econ.margin).toFixed(1)}% / ${n(econ.roi).toFixed(0)}%`:'—'}</b></div><div class="metric"><small>Validare vânzări</small><b>${esc(sales.salesEstimateStatus||'NECUNOSCUT')}</b></div></div><div class="gates">${Object.entries(d.gates||{}).map(([k,v])=>`<div class="gate ${v?'ok':'no'}">${v?'✓':'○'} ${esc(gateLabels[k]||k)}</div>`).join('')}</div><div class="actions customer-actions"><a href="supplier-intelligence.html">Furnizor</a><a href="landed-cost.html">Landed cost</a>${d.commercialAction==='TEST'?'<a class="primary" data-journey-event="RADAR_PREPARE_TEST" href="test-buy.html">Pregătește testul</a>':''}</div></details></article>`;}
function filtered(){const q=(document.querySelector('#search')?.value||'').trim().toLowerCase();let list=products.filter(p=>!q||`${p.name} ${roProductName(p.name)} ${p.cat||''} ${roCategory(p.cat||'')}`.toLowerCase().includes(q));const sort=document.querySelector('#sort')?.value||'READINESS';list.sort((a,b)=>sort==='SCORE'?scoreOf(b)-scoreOf(a):sort==='PROFIT'?n(b.testBuyDecision?.economics?.profit)-n(a.testBuyDecision?.economics?.profit):n(b.testBuyDecision?.commercialReadiness)-n(a.testBuyDecision?.commercialReadiness));return list;}
function render(){const list=filtered();document.querySelector('#grid').innerHTML=list.length?list.map(card).join(''):'<div class="empty customer-empty"><h3>Nicio oportunitate pentru filtrul ales</h3><p>Schimbă căutarea sau sortarea pentru a vedea din nou produsele disponibile.</p><button type="button" id="clearFilter" class="customer-primary">Resetează filtrul</button></div>';document.querySelector('#clearFilter')?.addEventListener('click',()=>{document.querySelector('#search').value='';document.querySelector('#sort').value='READINESS';render();});document.querySelector('#kTotal').textContent=products.length;document.querySelector('#kTest').textContent=products.filter(p=>['TEST','BUY'].includes(p.testBuyDecision?.commercialAction)).length;document.querySelector('#kHold').textContent=products.filter(p=>p.testBuyDecision?.commercialAction==='HOLD').length;document.querySelector('#kLanded').textContent=products.filter(p=>p.testBuyDecision?.landedCostConfirmed).length;const avg=products.length?products.reduce((s,p)=>s+n(p.testBuyDecision?.commercialReadiness),0)/products.length:0;document.querySelector('#kAvg').textContent=`${Math.round(avg)}%`;}
async function load(){const grid=document.querySelector('#grid');try{const session=await getCurrentSession();if(!session){location.href='login.html?next=commercial-radar.html';return;}const response=await fetch('/api/commercial/radar',{headers:{authorization:`Bearer ${session.access_token}`},cache:'no-store'});const data=await response.json();if(response.status===403){trackJourneyEvent('UPGRADE_INTENT_RADAR',{source:'RADAR_ACCESS_GATE'});location.href='pricing.html?upgrade=RADAR';return;}if(!response.ok)throw new Error(data.error||'Radar indisponibil');document.querySelector('#planName').textContent=data.plan||'RADAR';products=await applyPrivateCommercialDecisions(Array.isArray(data.products)?data.products:[]);render();trackJourneyEvent('RADAR_VIEW',{products:products.length,testable:products.filter(p=>['TEST','BUY'].includes(p.testBuyDecision?.commercialAction)).length});}catch(error){grid.innerHTML=`<div class="errorbox customer-empty"><h3>Radar indisponibil momentan</h3><p>${esc(error?.message||error)}</p><a href="home.html">Înapoi la Home</a></div>`;}}
document.querySelector('#search')?.addEventListener('input',render);document.querySelector('#sort')?.addEventListener('change',render);installJourneyLinkTracking(document);load();
