import {getCurrentSession} from './supabase-client.js';
import {applyPrivateCommercialDecisions} from './commercial-decision-client.js';
import {roCategory,roProductName} from './product-ro.js';
import {loadSellerPreferences,categoryPreferenceScore} from './seller-preferences.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const money=v=>`${Number(v||0).toLocaleString('ro-RO',{maximumFractionDigits:2})} lei`;
let products=[],preferences=null;
function scoreOf(p){return n(p?.launchScore?.score||p?.launchScore?.total||p?.opportunityRanking?.score||p?.opportunityRankingV2?.score||p?.score);}
function priority(p){const d=p.testBuyDecision||{};const risk=String(preferences?.risk_profile||'BALANCED');const riskBonus=risk==='CONSERVATIVE'?(d.commercialAction==='BUY'?20:d.commercialAction==='TEST'?5:0):risk==='AGGRESSIVE'?(d.commercialAction==='TEST'?12:0):0;return (d.commercialAction==='BUY'?300:d.commercialAction==='TEST'?200:100)+n(d.commercialReadiness)+scoreOf(p)/10+categoryPreferenceScore(p,preferences||{})+riskBonus;}
function shortlist(){return [...products].sort((a,b)=>priority(b)-priority(a)).slice(0,5);}
function planAllocation(list,budget){let left=Math.max(0,budget),allocated=0;const rows=[];for(const p of list){const d=p.testBuyDecision||{};const eligible=['TEST','BUY'].includes(d.commercialAction)&&d.landedCostConfirmed&&n(d.testBudget)>0;let capital=0;if(eligible&&d.testBudget<=left){capital=d.testBudget;left-=capital;allocated+=capital;}rows.push({p,d,eligible,capital});}return {rows,allocated,left};}
function card(row){const {p,d,eligible,capital}=row,e=d.economics||{},name=roProductName(p.name),cat=roCategory(p.cat||'');const preferred=categoryPreferenceScore(p,preferences||{})>0;const status=eligible?(capital>0?'ALOCAT PENTRU TEST':'TESTABIL, DAR PESTE BUGET'):'VALIDARE ÎNAINTE DE BANI';return `<article class="card"><div class="top"><div class="copy"><h3>${esc(name)}</h3><small>${esc(cat||p.cat||'Categorie')} · ${n(d.passedGates)}/9 gate-uri${preferred?' · potrivire profil':''}</small><br><span class="badge ${eligible?'ready':'hold'}">${esc(status)}</span></div><div class="score">${Math.round(n(d.commercialReadiness))}%<small>READINESS</small></div></div><div class="metrics"><div class="metric"><small>Capital test</small><b>${d.testBudget!=null?money(d.testBudget):'—'}</b></div><div class="metric"><small>Capital alocat</small><b>${capital?money(capital):'—'}</b></div><div class="metric"><small>Preț vânzare</small><b>${d.targetSalePrice!=null?money(d.targetSalePrice):'—'}</b></div><div class="metric"><small>Profit / marjă</small><b>${e.profit!=null?`${money(e.profit)} / ${n(e.margin).toFixed(1)}%`:'—'}</b></div></div><div class="steps"><div class="step"><b>1. Produs</b><br>${eligible?'Gate-urile permit test.':'Închide blocker-ele Radar.'}</div><div class="step"><b>2. Furnizor</b><br>${d.gates?.supplierVerified?'Ofertă verificată.':'Confirmă oferta completă.'}</div><div class="step"><b>3. Cost</b><br>${d.landedCostConfirmed?'Landed confirmat.':'Confirmă landed cost.'}</div><div class="step"><b>4. Execuție</b><br>${capital>0?`Pregătește lot ${n(d.quantity)} buc.`:'Nu aloca bani încă.'}</div></div><div class="actions"><a href="commercial-radar.html">Vezi Radar</a><a href="supplier-intelligence.html">Furnizor</a><a href="landed-cost.html">Cost import</a><a href="onboarding.html">Preferințe</a>${capital>0?'<a class="primary" href="test-buy.html">Pornește testul</a>':''}</div></article>`;}
function render(){const list=shortlist(),budget=Math.max(0,n(document.querySelector('#budget')?.value)),plan=planAllocation(list,budget);document.querySelector('#grid').innerHTML=plan.rows.length?plan.rows.map(card).join(''):'<div class="empty">Nu există produse în shortlist.</div>';document.querySelector('#allocated').textContent=money(plan.allocated);document.querySelector('#reserve').textContent=money(plan.left);document.querySelector('#testable').textContent=plan.rows.filter(x=>x.eligible).length;document.querySelector('#shortlist').textContent=plan.rows.length;}
async function load(){const grid=document.querySelector('#grid');try{const session=await getCurrentSession();if(!session){location.href='login.html?next=commercial-launch.html';return;}preferences=await loadSellerPreferences();const budget=document.querySelector('#budget');if(budget&&preferences?.monthly_budget_ron!=null)budget.value=String(Math.max(0,n(preferences.monthly_budget_ron)));const response=await fetch('/api/commercial/radar',{headers:{authorization:`Bearer ${session.access_token}`},cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Launch data unavailable');if(String(data.plan)!=='LAUNCH'){location.href='pricing.html?upgrade=LAUNCH';return;}products=await applyPrivateCommercialDecisions(Array.isArray(data.products)?data.products:[]);render();}catch(error){grid.innerHTML=`<div class="empty"><b>Launch indisponibil momentan.</b><br>${esc(error?.message||error)}</div>`;}}
document.querySelector('#budget')?.addEventListener('input',render);load();
