export const VAULT_KEYS=['megaRadarSupplierRecordsV1','megaRadarPurchaseRecordsV1','megaRadarLandedCostRecordsV1','megaRadarDiscoveryRecordsV1','megaRadarEconomicsV2','megaRadarWatchlistV1','megaRadarBuyingBudgetV1'];
export function collectVault(storage=localStorage){const data={};for(const key of VAULT_KEYS){const raw=storage.getItem(key);if(raw!==null)data[key]=raw;}return{version:'5.7',exportedAt:new Date().toISOString(),data};}
export function validateVault(payload){if(!payload||typeof payload!=='object'||!payload.data||typeof payload.data!=='object')return{ok:false,error:'Backup invalid'};const keys=Object.keys(payload.data);if(keys.some(k=>!VAULT_KEYS.includes(k)))return{ok:false,error:'Backup contains unknown keys'};for(const value of Object.values(payload.data))if(typeof value!=='string')return{ok:false,error:'Backup values must be strings'};return{ok:true,keys};}
export function applyVault(payload,storage=localStorage){const check=validateVault(payload);if(!check.ok)throw new Error(check.error);for(const key of VAULT_KEYS)if(Object.hasOwn(payload.data,key))storage.setItem(key,payload.data[key]);return check.keys.length;}
function setStatus(text,kind=''){const el=document.querySelector('#vaultStatus');if(el){el.textContent=text;el.dataset.kind=kind;}}
function downloadVault(){const payload=collectVault(),blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`mega-product-radar-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus(`Backup exportat: ${Object.keys(payload.data).length} zone locale.`,'ok');}
async function importVault(file){const text=await file.text(),payload=JSON.parse(text),count=applyVault(payload);setStatus(`Backup restaurat: ${count} zone. Reîncarcă modulele pentru a vedea datele.`,'ok');}
function syncSecret(){return document.querySelector('#syncSecret')?.value.trim()||'';}
async function cloudPush(){const secret=syncSecret();if(!secret)throw new Error('Introdu secretul de sync.');const payload=collectVault();const r=await fetch('/api/radar/sync',{method:'POST',headers:{'Content-Type':'application/json','x-radar-sync-secret':secret},body:JSON.stringify(payload)}),data=await r.json();if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);setStatus(`Cloud backup salvat: ${new Date(data.updatedAt).toLocaleString('ro-RO')}.`,'ok');}
async function cloudPull(){const secret=syncSecret();if(!secret)throw new Error('Introdu secretul de sync.');const r=await fetch('/api/radar/sync',{headers:{'x-radar-sync-secret':secret}}),data=await r.json();if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);if(data.empty)throw new Error('Nu există încă backup în cloud.');const count=applyVault(data);setStatus(`Cloud backup restaurat: ${count} zone.`,'ok');}
if(typeof document!=='undefined'){document.querySelector('#exportVault')?.addEventListener('click',downloadVault);document.querySelector('#importVault')?.addEventListener('change',e=>{const file=e.target.files?.[0];if(file)importVault(file).catch(err=>setStatus(err.message,'error'));});document.querySelector('#cloudPush')?.addEventListener('click',()=>cloudPush().catch(err=>setStatus(err.message,'error')));document.querySelector('#cloudPull')?.addEventListener('click',()=>cloudPull().catch(err=>setStatus(err.message,'error')));document.querySelector('#localCount').textContent=String(Object.keys(collectVault().data).length);}
