export const VAULT_KEYS=['megaRadarSupplierRecordsV1','megaRadarPurchaseRecordsV1','megaRadarLandedCostRecordsV1','megaRadarDiscoveryRecordsV1','megaRadarEconomicsV2','megaRadarWatchlistV1','megaRadarBuyingBudgetV1','megaRadarPortfolioV6','megaRadarFeedbackV6','megaRadarSupplierMatrixV6','megaRadarCapitalPlanV6'];
export function collectVault(storage=localStorage){const data={};for(const key of VAULT_KEYS){const raw=storage.getItem(key);if(raw!==null)data[key]=raw;}return{version:'6.0',exportedAt:new Date().toISOString(),data};}
export function validateVault(payload){if(!payload||typeof payload!=='object'||!payload.data||typeof payload.data!=='object')return{ok:false,error:'Backup invalid'};const keys=Object.keys(payload.data);if(keys.some(k=>!VAULT_KEYS.includes(k)))return{ok:false,error:'Backup contains unknown keys'};for(const value of Object.values(payload.data))if(typeof value!=='string')return{ok:false,error:'Backup values must be strings'};return{ok:true,keys};}
export function applyVault(payload,storage=localStorage){const check=validateVault(payload);if(!check.ok)throw new Error(check.error);for(const key of VAULT_KEYS)if(Object.hasOwn(payload.data,key))storage.setItem(key,payload.data[key]);return check.keys.length;}
const enc=new TextEncoder(),dec=new TextDecoder();
function bytesToB64(bytes){if(typeof Buffer!=='undefined')return Buffer.from(bytes).toString('base64');let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s);}
function b64ToBytes(value){if(typeof Buffer!=='undefined')return new Uint8Array(Buffer.from(value,'base64'));const s=atob(value),out=new Uint8Array(s.length);for(let i=0;i<s.length;i++)out[i]=s.charCodeAt(i);return out;}
async function deriveKey(password,salt,cryptoObj=globalThis.crypto){if(!password||password.length<8)throw new Error('Parola backup trebuie sa aiba minimum 8 caractere.');const base=await cryptoObj.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return cryptoObj.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function encryptVaultPayload(payload,password,cryptoObj=globalThis.crypto){const check=validateVault(payload);if(!check.ok)throw new Error(check.error);const salt=cryptoObj.getRandomValues(new Uint8Array(16)),iv=cryptoObj.getRandomValues(new Uint8Array(12)),key=await deriveKey(password,salt,cryptoObj),cipher=await cryptoObj.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(payload)));return{format:'MEGA_RADAR_VAULT',version:1,kdf:'PBKDF2-SHA256-250000',cipher:'AES-256-GCM',salt:bytesToB64(salt),iv:bytesToB64(iv),data:bytesToB64(new Uint8Array(cipher))};}
export async function decryptVaultPayload(encrypted,password,cryptoObj=globalThis.crypto){if(encrypted?.format!=='MEGA_RADAR_VAULT'||!encrypted.salt||!encrypted.iv||!encrypted.data)throw new Error('Fisier criptat invalid.');try{const salt=b64ToBytes(encrypted.salt),iv=b64ToBytes(encrypted.iv),key=await deriveKey(password,salt,cryptoObj),plain=await cryptoObj.subtle.decrypt({name:'AES-GCM',iv},key,b64ToBytes(encrypted.data)),payload=JSON.parse(dec.decode(plain)),check=validateVault(payload);if(!check.ok)throw new Error(check.error);return payload;}catch(error){if(String(error?.message||'').includes('Backup'))throw error;throw new Error('Parola gresita sau backup corupt.');}}
function setStatus(text,kind=''){const el=document.querySelector('#vaultStatus');if(el){el.textContent=text;el.dataset.kind=kind;}}
function password(){return document.querySelector('#vaultPassword')?.value||'';}
function filename(){return `mega-product-radar-v6-${new Date().toISOString().slice(0,10)}.radarvault.json`;}
async function buildEncryptedFile(){const encrypted=await encryptVaultPayload(collectVault(),password()),text=JSON.stringify(encrypted,null,2),blob=new Blob([text],{type:'application/json'});return new File([blob],filename(),{type:'application/json'});}
async function downloadEncrypted(){const file=await buildEncryptedFile(),url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Backup criptat creat. Salveaza-l in Files/iCloud Drive.','ok');}
async function shareEncrypted(){const file=await buildEncryptedFile();if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'Mega Product Radar Backup',text:'Backup criptat Radar 6',files:[file]});setStatus('Backup trimis catre Share Sheet. Alege Save to Files / iCloud Drive.','ok');return;}await downloadEncrypted();}
async function importEncrypted(file){const encrypted=JSON.parse(await file.text()),payload=await decryptVaultPayload(encrypted,password()),count=applyVault(payload);setStatus(`Backup restaurat: ${count} zone. Reincarca modulele pentru datele restaurate.`,'ok');}
function downloadPlain(){const payload=collectVault(),blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`mega-product-radar-v6-plain-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Backup JSON necriptat exportat. Foloseste-l doar temporar.','ok');}
async function importPlain(file){const payload=JSON.parse(await file.text()),count=applyVault(payload);setStatus(`Backup JSON restaurat: ${count} zone.`,'ok');}
if(typeof document!=='undefined'){document.querySelector('#exportEncrypted')?.addEventListener('click',()=>downloadEncrypted().catch(e=>setStatus(e.message,'error')));document.querySelector('#shareEncrypted')?.addEventListener('click',()=>shareEncrypted().catch(e=>setStatus(e.message,'error')));document.querySelector('#importEncrypted')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)importEncrypted(f).catch(err=>setStatus(err.message,'error'));});document.querySelector('#exportPlain')?.addEventListener('click',downloadPlain);document.querySelector('#importPlain')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)importPlain(f).catch(err=>setStatus(err.message,'error'));});document.querySelector('#localCount').textContent=String(Object.keys(collectVault().data).length);}
