import {getCurrentSession} from './supabase-client.js';
import {roCategory,roProductName} from './product-ro.js';
import {bestEvidence,evidenceClassOf,sortDiscoverProducts} from './discover-ranking.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const safeUrl=u=>{try{const x=new URL(String(u||''),location.href);return['http:','https:'].includes(x.protocol)?x.href:'#';}catch{return'#';}};
const num=v=>Number(v||0);
let products=[],view='ALL',discoverFull=false,radarAccess=false,planCode='FREE';
function signal(p,key){return p?.signals?.[key]||{};}function signalCount(p,keys){return keys.reduce((sum,key)=>sum+num(signal(p,key).resultCount),0);}function present(p,keys){return keys.some(key=>Boolean(signal(p,key).present));}function amazonCount(p){return signalCount(p,['amazonUS','amazonDE','amazonIT','amazonFR']);}function amazonPresent(p){return present(p,['amazonUS','amazonDE','amazonIT','amazonFR']);}function tiktokCount(p){return signalCount(p,['tiktok']);}function tiktokPresent(p){return present(p,['tiktok']);}function delta7(p){return num(p?.trendWindows?.d7?.scoreDelta);}function delta30(p){return num(p?.trendWindows?.d30?.scoreDelta);}function isRising(p){return Boolean(p?.risingSignal?.eligible)||delta7(p)>0;}function isNew(p){const t=Date.parse(p.firstDiscoveredAt||'');return Number.isFinite(t)&&Date.now()-t<=14*86400000;}function score(p){return num(p?.discoveryAnalysis?.score||p?.score);}function sourceStatus(p){return String(p.sourceStatus||p?.discoveryAnalysis?.quality?.level||'PARTIAL').toUpperCase();}function reviewEvidence(p){const r=p.reviewIntel||{};return {sources:num(r.sourceCount),snippets:num(r.snippetCount),confidence:String(r.confidence||'LOW').toUpperCase()};}
function representativeImageUrl(name){const query=`${String(name||'').trim()} product`;return `https://tse1.mm.bing.net/th?q=${encodeURIComponent(query)}&pid=Api`;}
function image(p,name){const verified=safeUrl(p.imageUrl),fallback=safeUrl(representativeImageUrl(p.name||name)),hasVerified=verified!=='#',src=hasVerified?verified:fallback;return `<div class="media${hasVerified?'':' representative'}"><img src="${esc(src)}" data-fallback="${esc(fallback)}" alt="${esc(name)}" loading="lazy" referrerpolicy="no-referrer" onerror="const f=this.dataset.fallback;if(f&&this.src!==f){this.src=f;this.parentElement.classList.add('representative');const n=this.parentElement.querySelector('.media-note');if(n)n.hidden=false;}else{this.parentElement.textContent='Imagine indisponibilă'}"><span class="media-note" ${hasVerified?'hidden':''}>Imagine reprezentativă</span></div>`;}function platformBadges(p){const out=[];if(amazonPresent(p)||amazonCount(p)>0)out.push('<span class="badge">Amazon</span>');if(tiktokPresent(p)||tiktokCount(p)>0)out.push('<span class="badge">TikTok</span>');if(isRising(p))out.push('<span class="badge verified">RISING</span>');if(isNew(p))out.push('<span class="badge">NEW</span>');return out.join('');}function upgradeCard(){return `<article class="card"><div class="lock-box"><b>🔒 Top 20 este în Discover</b><p>Free primește doar 3 produse din endpoint. Datele suplimentare nu sunt trimise browserului până la upgrade.</p><a class="upgrade" href="pricing.html">Vezi Discover · €17,90</a></div></article>`;}
function sourceBlock(p){const e=bestEvidence(p),directUrl=safeUrl(e.url),searchUrl=safeUrl(e.searchUrl);let action='';if(e.direct&&directUrl!=='#')action=`<a href="${esc(directUrl)}" target="_blank" rel="noopener noreferrer">Verifică sursa</a>`;else if(searchUrl!=='#')action=`<a href="${esc(searchUrl)}" target="_blank" rel="noopener noreferrer">Caută sursa</a>`;return `<div class="source-box"><div><small>Sursă principală</small><b>${esc(e.market)}</b></div><span class="badge ${e.evidenceClass==='VERIFIED'?'verified':e.evidenceClass==='ESTIMATED'?'estimated':'derived'}">${esc(e.evidenceClass)}</span>${action}</div>`;}
function card(p){const name=roProductName(p.name),cat=roCategory(p.cat||''),reviews=reviewEvidence(p),aCount=amazonCount(p),tCount=tiktokCount(p),status=sourceStatus(p),klass=evidenceClassOf(p),rising=p?.risingSignal;return `<article class="card"><div class="top"><div class="product">${image(p,name)}<div class="copy"><h3>${esc(name)}</h3><small>${esc(cat||p.cat||'Categorie')} · ${esc(status)} data</small></div></div><div class="score">${score(p)}<small>${p.origin==='ORGANIC_RISING'?'RISING SCORE':'DISCOVERY SCORE'}</small></div></div><div class="badges">${platformBadges(p)}<span class="badge ${klass==='VERIFIED'?'verified':klass==='ESTIMATED'?'estimated':'derived'}">${esc(klass)}</span></div>${sourceBlock(p)}<div class="metrics"><div class="metric"><small>Amazon evidence</small><b>${aCount||'—'}</b></div><div class="metric"><small>TikTok evidence</small><b>${tCount||'—'}</b></div><div class="metric"><small>Review evidence</small><b>${reviews.sources} surse</b></div><div class="metric"><small>Fragmente review</small><b>${reviews.snippets}</b></div></div><div class="trend"><b>${rising?.eligible?'Rising observat':'Trend derivat'}:</b> ${rising?.eligible?`score ${num(rising.score)} · ${esc(rising.sourceMarket||'marketplace')} · rank Δ ${num(rising.rankDelta)}`:`7 zile ${delta7(p)>0?'+':''}${delta7(p)} · 30 zile ${delta30(p)>0?'+':''}${delta30(p)}`} · confidence review ${esc(reviews.confidence)}</div><div class="actions"><a class="primary" href="${radarAccess?'commercial-radar.html':'pricing.html'}">${radarAccess?'Analizează în Radar':'🔒 Analizează pentru România'}</a></div></article>`;}
function filtered(){const q=(document.querySelector('#search')?.value||'').trim().toLowerCase();let list=products.filter(p=>!q||`${p.name} ${roProductName(p.name)} ${p.cat||''} ${roCategory(p.cat||'')}`.toLowerCase().includes(q));if(view==='AMAZON')list=list.filter(p=>amazonPresent(p)||amazonCount(p)>0);if(view==='TIKTOK')list=list.filter(p=>tiktokPresent(p)||tiktokCount(p)>0);if(view==='RISING')list=list.filter(isRising);if(view==='NEW')list=list.filter(isNew);return sortDiscoverProducts(list,document.querySelector('#sort')?.value||'BEST');}
function render(){const list=filtered(),grid=document.querySelector('#grid');grid.innerHTML=list.length?list.map(card).join(''):'<div class="empty">Nu există produse pentru filtrul selectat.</div>';if(!discoverFull&&view==='ALL'&&!document.querySelector('#search')?.value)grid.insertAdjacentHTML('beforeend',upgradeCard());document.querySelector('#kVisible').textContent=list.length;document.querySelector('#kAmazon').textContent=products.filter(p=>amazonPresent(p)||amazonCount(p)>0).length;document.querySelector('#kTikTok').textContent=products.filter(p=>tiktokPresent(p)||tiktokCount(p)>0).length;document.querySelector('#kRising').textContent=products.filter(isRising).length;document.querySelector('#kLive').textContent=products.filter(p=>['LIVE','PARTIAL'].includes(sourceStatus(p))).length;}
async function load(){const session=await getCurrentSession();const headers={accept:'application/json'};if(session?.access_token)headers.authorization=`Bearer ${session.access_token}`;try{const r=await fetch('/api/commercial/discover',{headers,cache:'no-store'});const data=await r.json();if(!r.ok||!data.ok)throw new Error(data.error||'Discover API unavailable');products=Array.isArray(data.products)?data.products:[];discoverFull=Boolean(data.entitlements?.discoverFull);radarAccess=Boolean(data.entitlements?.radar);planCode=String(data.plan||'FREE');}catch{products=[];discoverFull=false;radarAccess=false;planCode='FREE';}document.querySelector('#planName').textContent=planCode;const cta=document.querySelector('#upgradeCta');if(cta){cta.textContent=discoverFull?'Discover activ':'Deblochează Discover · €17,90';if(discoverFull)cta.href='account.html';}render();}
document.querySelectorAll('[data-view]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');view=btn.dataset.view;render();}));document.querySelector('#search')?.addEventListener('input',render);document.querySelector('#sort')?.addEventListener('change',render);load();
