export const DISCOVERY_STAGES=['NEW','VALIDATE','TEST','BUY CANDIDATE','REJECT'];
const n=(v,min=0,max=10000)=>{const x=Number(v);return Number.isFinite(x)?Math.max(min,Math.min(max,x)):0};
const clamp=(v,min=0,max=100)=>Math.max(min,Math.min(max,Number(v)||0));
export function discoveryEconomics(p={}){const sell=n(p.sellTarget||p.sell),landed=n(p.landedEstimate||p.landed),net=sell/1.21,marketplace=sell*.17,ads=sell*.08,returns=sell*.04,profit=net-marketplace-ads-returns-landed;return{sell,landed,profit,margin:sell?profit/sell*100:0,roi:landed?profit/landed*100:0};}
export function discoveryQuality(p={}){const checks=n(p.checks||p.marketScout?.checks,0,99),foreign=n(p.foreignPresence||p.marketScout?.foreignPresence,0,99),china=n(p.chinaPresence||p.marketScout?.chinaSourcingPresence,0,99),romania=n(p.romaniaPresence||p.marketScout?.romaniaPresence,0,99);const live=checks>=5&&foreign>=1;return{level:live?'LIVE':'PARTIAL',checks,foreignPresence:foreign,chinaPresence:china,romaniaPresence:romania};}
export function discoveryScore(p={}){const q=discoveryQuality(p),e=discoveryEconomics(p),foreignResults=n(p.foreignResults,0,30),romaniaResults=n(p.romaniaResults,0,10),chinaResults=n(p.chinaResults,0,20),socialResults=n(p.socialResults,0,30);const demand=clamp(35+q.foreignPresence*14+foreignResults*2),gap=clamp(75+q.foreignPresence*8-romaniaResults*7-q.romaniaPresence*15),supplier=clamp(30+q.chinaPresence*20+chinaResults*3),viral=clamp(30+socialResults*2.5),margin=clamp(e.margin*1.5+Math.max(0,e.roi)*.2),score=Math.round(demand*.22+gap*.25+supplier*.12+viral*.10+margin*.21+(q.level==='LIVE'?10:0));return{score,components:{demand:Math.round(demand),gap:Math.round(gap),supplier:Math.round(supplier),viral:Math.round(viral),margin:Math.round(margin)},quality:q,economics:e};}
export function suggestedDiscoveryStage(p={}){const a=discoveryScore(p),kids=String(p.cat||p.category||'').toLowerCase().includes('kids');if(a.economics.profit<10||a.economics.margin<10)return'REJECT';if(a.quality.level!=='LIVE')return'NEW';if(a.quality.chinaPresence<1)return'VALIDATE';if(a.score>=84&&a.economics.profit>=40&&a.economics.margin>=20&&!kids)return'BUY CANDIDATE';if(a.score>=76&&a.economics.profit>=25)return'TEST';return'VALIDATE';}
export function normalizeDiscoveryRecord(v={}){const stage=DISCOVERY_STAGES.includes(String(v.stage||''))?String(v.stage):'NEW';return{stage,notes:String(v.notes||'').trim(),pinned:Boolean(v.pinned),updatedAt:String(v.updatedAt||'').trim()};}
export function canEnterPurchaseFlow(p={},record={}){const stage=normalizeDiscoveryRecord(record).stage,a=discoveryScore(p);return stage==='BUY CANDIDATE'&&a.quality.level==='LIVE'&&a.quality.chinaPresence>=1&&a.economics.profit>=40&&a.economics.margin>=20;}
