import {installCloudAutosync} from './cloud-sync.js';
await installCloudAutosync();
import { canEnterPurchaseFlow, discoveryScore, effectiveDiscoveryProduct, normalizeDiscoveryRecord, suggestedDiscoveryStage } from './discovery-engine.js';
import { trendLabel } from './discovery-history.js';

function installDiscoveryContrast(){if(document.querySelector('#discoveryContrastFix'))return;const s=document.createElement('style');s.id='discoveryContrastFix';s.textContent=`body{background:linear-gradient(180deg,#07101c,#0a1220)!important;color:#f5f7fb!important}main{color:#f5f7fb!important}.note,.toolbar{background:linear-gradient(180deg,rgba(18,29,45,.98),rgba(11,19,31,.98))!important;border-color:rgba(255,255,255,.09)!important;color:#aebdd0!important}.note b{color:#e7eef8!important}.kpi b{color:#f8fbff!important}.kpi small{color:#a4b5ca!important}.toolbar input{background:#0b1422!important;border-color:rgba(255,255,255,.14)!important;color:#f5f7fb!important}.toolbar input::placeholder{color:#7f91a9!important}.filter{background:#101a2a!important;border-color:rgba(255,255,255,.13)!important;color:#b8d5ff!important}.filter.active{background:linear-gradient(135deg,#5b9cff,#7ab6ff)!important;color:#07111f!important;border-color:transparent!important}.card{color:#f5f7fb!important}.top h3{color:#f5f7fb!important}.cat,.evidence{color:#93a5bc!important}.score{background:rgba(54,211,153,.13)!important;color:#7de9bf!important;border:1px solid rgba(54,211,153,.2)!important}.metric,.intel{background:rgba(255,255,255,.045)!important;border:1px solid rgba(255,255,255,.07)!important;color:#dbe4ef!important}.metric b{color:#f5f7fb!important}.metric small{color:#91a4bc!important}.empty{background:#0f1827!important;border-color:rgba(255,255,255,.09)!important;color:#a4b5ca!important}@media(max-width:700px){main{padding:12px!important}.kpis{gap:10px!important}.kpi{min-height:96px!important;padding:14px!important}.kpi b{font-size:30px!important}.toolbar{padding:12px!important;border-radius:18px!important}.card{padding:14px!important}.metrics{gap:8px!important}}`;document.head.appendChild(s);}installDiscoveryContrast();

const RECORD_KEY='megaRadarDiscoveryRecordsV1';
const keyOf=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>`${Number(v||0).toLocaleString('ro-RO',{maximumFractionDigits:2})} lei`;
const safeUrl=u=>{try{const x=new URL(String(u));return['http:','https:'].includes(x.protocol)?x.href:'#';}catch{return'#';}};
const loadRecords=()=>{try{return JSON.parse(localStorage.getItem(RECORD_KEY)||'{}')||{};}catch{return{}}};
const saveRecords=v=>localStorage.setItem(RECORD_KEY,JSON.stringify(v));
const recordFor=name=>normalizeDiscoveryRecord(loadRecords()[keyOf(name)]||{});
const effectiveProduct=p=>effectiveDiscoveryProduct(p,recordFor(p.name));
const effectiveStage=p=>{const r=recordFor(p.name),e=effectiveProduct(p);return r.updatedAt?r.stage:suggestedDiscoveryStage(e)};
const stageLabel=s=>({'NEW':'NOU','VALIDATE':'DE VALIDAT','TEST':'TESTEAZĂ','BUY CANDIDATE':'CANDIDAT DE CUMPĂRARE','REJECT':'RESPINGE'}[s]||s);
const qualityLabel=q=>q==='PARTIAL'?'PARȚIAL':q;
function localizeStatic(){const map=new Map([['New Product Inbox','Inbox produse noi'],['← Command Center','← Centru de comandă'],['Overview','Prezentare'],["Today's Opportunities",'Oportunitățile de azi'],['Strict Audit','Audit strict'],['Suppliers','Furnizori'],['Profit','Profit'],['MULTILINGUAL OPEN DISCOVERY → EVIDENCE → TREND → REVIEW INTELLIGENCE → VALIDATE','DESCOPERIRE MULTILINGVĂ → DOVEZI → TREND → ANALIZĂ RECENZII → VALIDARE'],['LIVE','LIVE'],['NEW','NOU'],['TEST','TESTEAZĂ'],['BUY CANDIDATE','CANDIDAT DE CUMPĂRARE'],['VALIDATE','DE VALIDAT'],['★ Pinned','★ Fixate'],['REJECT','RESPINSE']]);document.querySelectorAll('body *').forEach(el=>{if(el.children.length===0){const t=el.textContent.trim();if(map.has(t))el.textContent=map.get(t);}});}
let products=[],filter='ALL',editing='';
async function load(){let data={products:[]};try{const r=await fetch(`discovery-live.json?t=${Date.now()}`,{cache:'no-store'});if(r.ok)data=await r.json();}catch{}products=Array.isArray(data.products)?data.products:[];render();}
function stageClass(stage){return stage==='BUY CANDIDATE'?'buy':stage==='TEST'?'test':stage==='REJECT'?'reject':stage==='VALIDATE'?'validate':'new';}
function trendText(p){const w=p.trendWindows||{},fmt=(d,label)=>d?`${label} ${d.scoreDelta>0?'+':''}${d.scoreDelta}`:`${label} —`;return`${fmt(w.d7,'7z')} • ${fmt(w.d30,'30z')} • ${fmt(w.d90,'90z')} • ${trendLabel(w.d7)}`;}
function reviewText(p){const r=p.reviewIntel||{},themes=(r.negativeThemes||[]).map(x=>x.theme).slice(0,3);return`${Number(r.sourceCount||0)} surse de recenzii • ${Number(r.snippetCount||0)} fragmente • ${r.confidence||'INSUFICIENT'}${themes.length?` • riscuri: ${themes.join(', ')}`:''}`;}
function evidenceLinks(p){const links=[];for(const s of Object.values(p.signals||{}))for(const l of s.links||[])if(l?.url&&!links.some(x=>x.url===l.url))links.push({label:s.label||'Sursă',url:l.url,title:l.title||''});if(p.openDiscovery?.url)links.unshift({label:`Web: ${p.openDiscovery.market||'sursă'}`,url:p.openDiscovery.url,title:p.openDiscovery.title||''});return links.slice(0,6);}
function card(p){const r=recordFor(p.name),ep=effectiveProduct(p),a=discoveryScore(ep),stage=effectiveStage(p),quality=a.quality.level,canFlow=canEnterPurchaseFlow(p,{...r,stage}),ali=(p.sourcing||[]).find(x=>x.market==='Alibaba'),x1688=(p.sourcing||[]).find(x=>x.market==='1688'),links=evidenceLinks(p);return `<article class="card"><div class="top"><div><h3>${esc(p.name)}</h3><div class="cat">${esc(p.cat||'')} ${p.sourceType==='OPEN_WEB_DISCOVERY'?'• WEB DESCHIS':''}</div></div><div class="score">${a.score}<small>DESCOPERIRE</small></div></div><div class="badges"><span class="badge ${quality==='LIVE'?'live':'partial'}">${qualityLabel(quality)}</span><span class="badge ${stageClass(stage)}">${esc(stageLabel(stage))}</span>${a.economics.priceComplete?'<span class="badge live">PREȚ COMPLET</span>':'<span class="badge validate">PREȚ NECUNOSCUT</span>'}${canFlow?'<span class="badge live">GATA DE FLUX</span>':''}</div><div class="metrics"><div class="metric"><small>Profit scenariu</small><b>${a.economics.priceComplete?money(a.economics.profit):'de validat'}</b></div><div class="metric"><small>Marjă</small><b>${a.economics.priceComplete?`${a.economics.margin.toFixed(1)}%`:'—'}</b></div><div class="metric"><small>Extern / China</small><b>${a.quality.foreignPresence} / ${a.quality.chinaPresence}</b></div><div class="metric"><small>Semnal RO</small><b>${Number(p.romaniaResults||0)}</b></div></div><div class="intel"><b>Trend:</b> ${esc(trendText(p))}</div><div class="intel"><b>Analiză recenzii:</b> ${esc(reviewText(p))}</div><div class="evidence">${esc(p.evidence||'')} ${r.notes?`<br><b>Notiță:</b> ${esc(r.notes)}`:''}</div>${links.length?`<details><summary>Dovezi din surse (${links.length})</summary><div class="sources">${links.map(l=>`<a href="${esc(safeUrl(l.url))}" target="_blank" rel="noopener"><b>${esc(l.label)}</b><small>${esc(l.title||l.url)}</small></a>`).join('')}</div></details>`:''}<div class="actions"><button class="stage" data-stage="${encodeURIComponent(p.name)}">Validează / schimbă etapa</button><button class="pin ${r.pinned?'active':''}" data-pin="${encodeURIComponent(p.name)}">${r.pinned?'★ Fixat':'☆ Fixează'}</button>${ali?.url?`<a class="supplier" href="${esc(safeUrl(ali.url))}" target="_blank" rel="noopener">Alibaba</a>`:''}${x1688?.url?`<a class="supplier" href="${esc(safeUrl(x1688.url))}" target="_blank" rel="noopener">1688</a>`:''}</div></article>`;}
function render(){const q=(document.querySelector('#search')?.value||'').trim().toLowerCase();let list=products.filter(p=>!q||`${p.name} ${p.cat||''}`.toLowerCase().includes(q));if(filter==='PINNED')list=list.filter(p=>recordFor(p.name).pinned);else if(filter!=='ALL')list=list.filter(p=>effectiveStage(p)===filter);list.sort((a,b)=>{const pa=recordFor(a.name).pinned?1:0,pb=recordFor(b.name).pinned?1:0;return pb-pa||discoveryScore(effectiveProduct(b)).score-discoveryScore(effectiveProduct(a)).score});document.querySelector('#grid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">Nu există candidați în filtrul selectat.</div>';document.querySelector('#kTotal').textContent=products.length;document.querySelector('#kLive').textContent=products.filter(p=>discoveryScore(effectiveProduct(p)).quality.level==='LIVE').length;document.querySelector('#kNew').textContent=products.filter(p=>effectiveStage(p)==='NEW').length;document.querySelector('#kTest').textContent=products.filter(p=>effectiveStage(p)==='TEST').length;document.querySelector('#kBuy').textContent=products.filter(p=>effectiveStage(p)==='BUY CANDIDATE').length;}
function openStage(name){editing=name;const p=products.find(x=>x.name===name);if(!p)return;const r=recordFor(name),ep=effectiveProduct(p);document.querySelector('#stageProduct').textContent=name;document.querySelector('#stageSelect').value=r.updatedAt?r.stage:suggestedDiscoveryStage(ep);document.querySelector('#stageSell').value=r.sellTarget||p.sellTarget||'';document.querySelector('#stageLanded').value=r.landedEstimate||p.landedEstimate||'';document.querySelector('#stageNotes').value=r.notes;document.querySelector('#stageDialog').showModal();}
function saveStage(){if(!editing)return;const all=loadRecords(),old=recordFor(editing);all[keyOf(editing)]={...old,stage:document.querySelector('#stageSelect').value,sellTarget:Number(document.querySelector('#stageSell').value||0),landedEstimate:Number(document.querySelector('#stageLanded').value||0),notes:document.querySelector('#stageNotes').value.trim(),updatedAt:new Date().toISOString()};saveRecords(all);}
if(typeof document!=='undefined'){localizeStatic();document.querySelector('#search')?.addEventListener('input',render);document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render();}));document.querySelector('#grid')?.addEventListener('click',e=>{const s=e.target.closest('[data-stage]');if(s)return openStage(decodeURIComponent(s.dataset.stage));const pin=e.target.closest('[data-pin]');if(pin){const name=decodeURIComponent(pin.dataset.pin),all=loadRecords(),old=recordFor(name);all[keyOf(name)]={...old,pinned:!old.pinned,updatedAt:new Date().toISOString()};saveRecords(all);render();}});document.querySelector('#stageForm')?.addEventListener('submit',e=>{e.preventDefault();saveStage();document.querySelector('#stageDialog').close();render();});document.querySelector('#stageCancel')?.addEventListener('click',()=>document.querySelector('#stageDialog').close());load();}