export const DISCOVERY_STAGES=['NEW','VALIDATE','TEST','BUY CANDIDATE','REJECT'];
const n=(v,min=0,max=10000)=>{const x=Number(v);return Number.isFinite(x)?Math.max(min,Math.min(max,x)):0};
const clamp=(v,min=0,max=100)=>Math.max(min,Math.min(max,Number(v)||0));
const isKids=p=>String(p.cat||p.category||'').toLowerCase().includes('kids');
export function discoveryEconomics(p={}){const sell=n(p.sellTarget||p.sell),landed=n(p.landedEstimate||p.landed),priceComplete=sell>0&&landed>0,net=priceComplete?sell/1.21:0,marketplace=priceComplete?sell*.17:0,ads=priceComplete?sell*.08:0,returns=priceComplete?sell*.04:0,profit=priceComplete?net-marketplace-ads-returns-landed:0;return{sell,landed,priceComplete,profit,margin:priceComplete&&sell?profit/sell*100:0,roi:priceComplete&&landed?profit/landed*100:0};}
export function discoveryQuality(p={}){const checks=n(p.checks||p.marketScout?.checks,0,99),foreign=n(p.foreignPresence||p.marketScout?.foreignPresence,0,99),china=n(p.chinaPresence||p.marketScout?.chinaSourcingPresence,0,99),romania=n(p.romaniaPresence||p.marketScout?.romaniaPresence,0,99);const live=checks>=5&&foreign>=1;return{level:live?'LIVE':'PARTIAL',checks,foreignPresence:foreign,chinaPresence:china,romaniaPresence:romania};}
export function romaniaGap2(p={}){const roPresence=n(p.romaniaPresence||p.marketScout?.romaniaPresence,0,20),roResults=n(p.romaniaResults||p.competitorIntel?.resultProxy,0,50),foreignPresence=n(p.foreignPresence||p.marketScout?.foreignPresence,0,20),foreignResults=n(p.foreignResults,0,100),socialResults=n(p.socialResults,0,100),earlyPresence=n(p.earlyPresence,0,10),reviewSources=n(p.reviewIntel?.sourceCount,0,10);let saturation='LOW';if(roResults>=8||roPresence>=3)saturation='HIGH';else if(roResults>=4||roPresence>=2)saturation='MEDIUM';const scarcity=clamp(100-roResults*8-roPresence*12),foreignValidation=clamp(foreignPresence*18+foreignResults*2.2),momentum=clamp(socialResults*2+earlyPresence*15+reviewSources*5),opportunityScore=Math.round(clamp(scarcity*.50+foreignValidation*.35+momentum*.15));let label='WATCH';if(opportunityScore>=80&&saturation==='LOW'&&foreignPresence>=1)label='OPEN GAP';else if(opportunityScore>=68&&saturation!=='HIGH'&&foreignPresence>=1)label='PROMISING';else if(saturation==='HIGH')label='SATURATED';return{version:'2.0',opportunityScore,saturation,label,evidence:{roPresence,roResults,foreignPresence,foreignResults,socialResults,earlyPresence,reviewSources},components:{scarcity:Math.round(scarcity),foreignValidation:Math.round(foreignValidation),momentum:Math.round(momentum)},note:'Romania Gap 2.0 uses web-search presence/result proxies, not verified seller counts or sales volume.'};}
export function discoveryScore(p={}){const q=discoveryQuality(p),e=discoveryEconomics(p),foreignResults=n(p.foreignResults,0,30),chinaResults=n(p.chinaResults,0,20),socialResults=n(p.socialResults,0,30),gap2=romaniaGap2(p),demand=clamp(35+q.foreignPresence*14+foreignResults*2),gap=gap2.opportunityScore,supplier=clamp(30+q.chinaPresence*20+chinaResults*3),viral=clamp(30+socialResults*2.5),margin=e.priceComplete?clamp(e.margin*1.5+Math.max(0,e.roi)*.2):0,score=Math.round(demand*.22+gap*.25+supplier*.12+viral*.10+margin*.21+(q.level==='LIVE'?10:0));return{score,components:{demand:Math.round(demand),gap:Math.round(gap),supplier:Math.round(supplier),viral:Math.round(viral),margin:Math.round(margin)},romaniaGap2:gap2,quality:q,economics:e};}
export function suggestedDiscoveryStage(p={}){const a=discoveryScore(p),kids=isKids(p);if(!a.economics.priceComplete)return a.quality.level==='LIVE'?'VALIDATE':'NEW';if(a.economics.profit<10||a.economics.margin<10)return'REJECT';if(a.quality.level!=='LIVE')return'NEW';if(a.quality.chinaPresence<1)return'VALIDATE';if(a.romaniaGap2.saturation==='HIGH')return'VALIDATE';if(a.score>=84&&a.romaniaGap2.opportunityScore>=75&&a.economics.profit>=40&&a.economics.margin>=20&&!kids)return'BUY CANDIDATE';if(a.score>=76&&a.romaniaGap2.opportunityScore>=65&&a.economics.profit>=25)return'TEST';return'VALIDATE';}
export function normalizeDiscoveryRecord(v={}){const stage=DISCOVERY_STAGES.includes(String(v.stage||''))?String(v.stage):'NEW';return{stage,notes:String(v.notes||'').trim(),pinned:Boolean(v.pinned),sellTarget:Math.max(0,n(v.sellTarget)),landedEstimate:Math.max(0,n(v.landedEstimate)),updatedAt:String(v.updatedAt||'').trim()};}
export function effectiveDiscoveryProduct(p={},record={}){const r=normalizeDiscoveryRecord(record);return{...p,...(r.sellTarget>0?{sellTarget:r.sellTarget}:{}),...(r.landedEstimate>0?{landedEstimate:r.landedEstimate}:{}),pricingStatus:(r.sellTarget>0&&r.landedEstimate>0)?'MANUAL_VALIDATION':p.pricingStatus};}
export function canEnterPurchaseFlow(p={},record={}){const r=normalizeDiscoveryRecord(record),effective=effectiveDiscoveryProduct(p,r),a=discoveryScore(effective),kidsOk=!isKids(effective)||String(effective.kidsGate||'').toUpperCase()==='PASS';return r.stage==='BUY CANDIDATE'&&kidsOk&&a.economics.priceComplete&&a.quality.level==='LIVE'&&a.quality.chinaPresence>=1&&a.romaniaGap2.opportunityScore>=75&&a.romaniaGap2.saturation!=='HIGH'&&a.economics.profit>=40&&a.economics.margin>=20;}
