import { discoveryScore, suggestedDiscoveryStage } from './discovery-engine.js';
const $=s=>document.querySelector(s),n=v=>Number.isFinite(Number(v))?Number(v):0,keyOf=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const getLocal=(key,fallback={})=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))||fallback}catch{return fallback}};
const discoveryRecord=name=>getLocal('megaRadarDiscoveryRecordsV1',{})[keyOf(name)]||{};
const supplierRecord=name=>getLocal('megaRadarSupplierRecordsV1',{})[keyOf(name)]||{};
function supplierOk(s={}){const certs=Array.isArray(s.certifications)?s.certifications:[];return Boolean((s.supplierName||s.url)&&n(s.moq)>0&&n(s.rating)>=4.3&&n(s.years)>=2&&(s.tradeAssurance===true||certs.length>0));}
async function fetchJson(path,fallback){try{const r=await fetch(`${path}?t=${Date.now()}`,{cache:'no-store'});if(r.ok)return await r.json()}catch{}return fallback;}
function promoteCategoryRadar(){
  const hero=document.querySelector('.hero-actions');
  if(hero){const primary=hero.querySelector('.primary-link');if(primary){primary.href='category-radar.html';primary.textContent='🧭 Alege categoria și vezi Top 10–20';}const secondary=hero.querySelector('.secondary-link');if(secondary){secondary.href='test-buy.html';secondary.textContent='Test Buy 20–30';}}
  const modules=document.querySelector('.modules');
  if(modules&&!modules.querySelector('a[href="category-radar.html"]')){const a=document.createElement('a');a.className='module';a.href='category-radar.html';a.innerHTML='<h3>🧭 Category Radar</h3><p>Alege nișa ta și vezi Top 10–20 produse, cu gate-uri, marjă, ROI și verdict comercial separat pe categorie.</p><strong>Alege categoria →</strong>';modules.prepend(a);}
  document.querySelectorAll('.bottom-nav a').forEach(a=>{if(a.getAttribute('href')==='discovery-inbox.html'){a.href='category-radar.html';a.innerHTML='<b>🧭</b>Categorii';}});
}
function localizeHome(){
  const replacements=new Map([
    ['Product Intelligence for Romania','Inteligență de produs pentru România'],['Live intelligence','Inteligență live'],['Global discovery','Descoperire globală'],['Supplier intelligence','Analiză furnizori'],['Profit engine','Motor de profit'],['Import risk','Risc de import'],['Evidence','Dovezi'],['Decision layer','Strat decizional'],['DISCOVER','DESCOPERĂ'],['ROMANIA GAP','GOL PIAȚĂ ROMÂNIA'],['VALIDATE','VALIDEAZĂ'],['SUPPLIER','FURNIZOR'],['PROFIT','PROFIT'],['RISK','RISC'],['TEST','TESTEAZĂ'],['BUY','CUMPĂRĂ'],['discovery LIVE','descoperire LIVE'],['BUY candidate','candidat de cumpărare'],['order now','comandă acum'],['supplier ok','furnizor validat'],['Signal center','Centru de semnale'],['Core system','Sistem principal'],['Intelligence Workspace','Spațiu de lucru inteligent'],['Auth','Autentificare'],['Email + Password ready','Email + parolă pregătite'],['Workspace','Spațiu de lucru'],['Multi-user ready','Pregătit pentru mai mulți utilizatori'],['Data','Date'],['Cloud-ready','Pregătit pentru cloud'],['Today\'s Opportunities','Oportunitățile de azi'],['BUY, TEST, Early Warning și Romania Gap într-un singur ecran.','Cumpărare, testare, alerte timpurii și golul de piață din România într-un singur ecran.'],['Strict Audit','Audit strict'],['Evidence, profit, compliance și blocaje reale înainte de bani.','Dovezi, profit, conformitate și blocaje reale înainte de a investi bani.'],['Global Discovery','Descoperire globală'],['Produse noi din piețe externe și semnale early-stage.','Produse noi din piețe externe și semnale timpurii.'],['Vezi discovery →','Vezi descoperirile →'],['Supplier Intelligence','Analiză furnizori'],['Compară sourcing, MOQ, rating, risc și opțiuni de furnizori.','Compară sursele, MOQ, ratingul, riscul și opțiunile de furnizori.'],['Opportunity Radar','Radar de oportunități'],['MEGA Score, Buying Readiness și Kill Score.','Scor MEGA, pregătire pentru cumpărare și scor de eliminare.'],['Profit & Landed Cost','Profit și cost total de import'],['Purchase Manager','Manager achiziții'],['Sample, compliance, MOQ și READY TO ORDER.','Mostră, conformitate, MOQ și pregătire pentru comandă.'],['Executive Dashboard','Panou executiv'],['Deschide Executive →','Deschide panoul →'],['Home','Acasă'],['Today','Astăzi'],['Discover','Descoperă'],['Supply','Furnizori'],['Audit','Audit']
  ]);
  document.querySelectorAll('body *').forEach(el=>{if(el.children.length===0){const t=el.textContent.trim();if(replacements.has(t))el.textContent=replacements.get(t);}});
  document.querySelectorAll('a[href="radar.html"]').forEach(a=>a.href='radar-ro.html');
  document.querySelectorAll('a[href="purchase-manager.html"]').forEach(a=>a.href='purchase-manager-ro.html');
  document.querySelectorAll('a[href="executive-dashboard.html"]').forEach(a=>a.href='executive-ro.html');
  document.querySelectorAll('a[href="strict-audit.html"]').forEach(a=>a.href='strict-audit-ro.html');
}
async function load(){const [radar,discovery,status,category]=await Promise.all([fetchJson('radar-live.json',{products:[]}),fetchJson('discovery-live.json',{products:[]}),fetchJson('scan-status.json',{}),fetchJson('category-radar-live.json',{stats:{}})]),rp=Array.isArray(radar.products)?radar.products:[],dp=Array.isArray(discovery.products)?discovery.products:[];$('#kRadar').textContent=rp.length;$('#kDiscovery').textContent=dp.length;$('#kLive').textContent=dp.filter(p=>discoveryScore(p).quality.level==='LIVE').length;$('#kBuy').textContent=dp.filter(p=>(discoveryRecord(p.name).updatedAt?discoveryRecord(p.name).stage:suggestedDiscoveryStage(p))==='BUY CANDIDATE').length;$('#kSupplier').textContent=rp.filter(p=>supplierOk(supplierRecord(p.name))).length;$('#kOrder').textContent=n(category?.stats?.totalTestReady)||rp.filter(p=>String(p.action||p.verdict).toUpperCase()==='BUY'&&n(p.megaScore||p.score)>=84&&n(p.marketScout?.checks)>=5&&n(p.marketScout?.foreignPresence)>=1&&supplierOk(supplierRecord(p.name))).length;$('#radarStatus').textContent=status.ok===false?'EROARE':radar.live?'LIVE':'PARȚIAL';$('#discoveryStatus').textContent=category?.stats?.categories?`${category.stats.categories} categorii · ${category.stats.categoriesAtMinimum||0} cu min. 10`:(discovery.updatedAt?`${dp.length} candidați`:'NERULAT');const dates=[radar.updatedAt,discovery.updatedAt,status.completedAt,category.updatedAt].filter(Boolean).map(x=>new Date(x)).filter(x=>!Number.isNaN(x.getTime()));$('#updated').textContent=dates.length?new Date(Math.max(...dates.map(x=>x.getTime()))).toLocaleString('ro-RO'):'—';}
promoteCategoryRadar();localizeHome();
$('#refresh')?.addEventListener('click',load);load();
