import {installCloudAutosync} from './cloud-sync.js';
await installCloudAutosync();
const LANDED_KEY='megaRadarLandedCostRecordsV1';
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const keyOf=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>`${n(v).toLocaleString('ro-RO',{maximumFractionDigits:2})} lei`;
export function normalizeLandedRecord(v={}){return{currency:['CNY','USD','EUR','RON'].includes(String(v.currency||'').toUpperCase())?String(v.currency).toUpperCase():'CNY',fxRate:Math.max(0,n(v.fxRate)),unitPriceForeign:Math.max(0,n(v.unitPriceForeign)),quantity:Math.max(0,Math.round(n(v.quantity))),internationalFreight:Math.max(0,n(v.internationalFreight)),customsDutyRate:Math.max(0,n(v.customsDutyRate)),customsFixed:Math.max(0,n(v.customsFixed)),brokerage:Math.max(0,n(v.brokerage)),domesticFreight:Math.max(0,n(v.domesticFreight)),inspection:Math.max(0,n(v.inspection)),labelsPackaging:Math.max(0,n(v.labelsPackaging)),otherFixed:Math.max(0,n(v.otherFixed)),confirmed:Boolean(v.confirmed),notes:String(v.notes||'').trim(),updatedAt:String(v.updatedAt||'').trim()};}
export function calculateLandedCost(v={}){const r=normalizeLandedRecord(v),qty=r.quantity,goodsRon=r.unitPriceForeign*r.fxRate*qty,freight=r.internationalFreight,customsBase=goodsRon+freight,duty=customsBase*(r.customsDutyRate/100),fixed=r.customsFixed+r.brokerage+r.domesticFreight+r.inspection+r.labelsPackaging+r.otherFixed,total=goodsRon+freight+duty+fixed,perUnit=qty?total/qty:0;return{...r,goodsRon,customsBase,duty,fixed,total,perUnit,valid:qty>0&&r.fxRate>0&&r.unitPriceForeign>0};}
export function landedCostStatus(v={}){const c=calculateLandedCost(v);if(!c.valid)return{status:'INCOMPLET',reason:'Completează prețul, cursul și cantitatea.'};if(!c.confirmed)return{status:'SIMULAT',reason:'Calcul complet, dar încă neconfirmat din oferta și transportul real.'};return{status:'CONFIRMAT',reason:'Costurile au fost marcate ca verificate manual.'};}
function loadJson(key){try{return JSON.parse(localStorage.getItem(key)||'{}')||{};}catch{return{};}}
function allRecords(){return loadJson(LANDED_KEY);}
function recordFor(name){return normalizeLandedRecord(allRecords()[keyOf(name)]||{});}
function saveRecord(name,record){const all=allRecords(),clean=normalizeLandedRecord(record),calc=calculateLandedCost(clean);clean.updatedAt=new Date().toISOString();clean.productName=name;clean.landedPerUnit=calc.valid?calc.perUnit:0;clean.totalLandedCost=calc.valid?calc.total:0;clean.costStatus=landedCostStatus(clean).status;all[keyOf(name)]=clean;localStorage.setItem(LANDED_KEY,JSON.stringify(all));return clean;}
let products=[],editing='';
async function loadProducts(){let data=null;try{const r=await fetch(`radar-live.json?t=${Date.now()}`,{cache:'no-store'});if(r.ok)data=await r.json();}catch{}if(!Array.isArray(data?.products)){const r=await fetch(`products.json?t=${Date.now()}`,{cache:'no-store'});data={products:await r.json()};}products=(data.products||[]).filter(p=>p&&p.name);render();}
function row(p){const r=recordFor(p.name),c=calculateLandedCost(r),s=landedCostStatus(r),delta=c.perUnit&&n(p.landed)?c.perUnit-n(p.landed):0,has=Boolean(r.quantity||r.unitPriceForeign||r.fxRate||r.confirmed);return `<article class="lc-card"><div class="lc-top"><div><h3>${esc(p.name)}</h3><small>${esc(p.cat||'')}</small></div><span class="badge ${s.status==='CONFIRMAT'?'ok':s.status==='SIMULAT'?'sim':''}">${s.status}</span></div><div class="metrics"><div><small>Cost estimat de radar</small><b>${money(p.landed)}</b></div><div><small>Cost total calculat</small><b>${c.perUnit?money(c.perUnit):'—'}</b></div><div><small>Diferență</small><b>${c.perUnit?`${delta>=0?'+':''}${money(delta)}`:'—'}</b></div><div><small>Total lot</small><b>${c.total?money(c.total):'—'}</b></div></div><p>${esc(s.reason)}</p><button data-edit="${encodeURIComponent(p.name)}">${has?'Editează costul':'Calculează costul de import'}</button></article>`;}
function render(){const q=(document.querySelector('#lcSearch')?.value||'').trim().toLowerCase(),f=document.querySelector('#lcFilter')?.value||'';let a=products.filter(p=>!q||`${p.name} ${p.cat||''}`.toLowerCase().includes(q));if(f)a=a.filter(p=>landedCostStatus(recordFor(p.name)).status===f);document.querySelector('#lcGrid').innerHTML=a.length?a.map(row).join(''):'<div class="empty">Nu există produse pentru filtrul selectat.</div>';const rec=products.map(p=>({p,r:recordFor(p.name)}));document.querySelector('#kConfirmed').textContent=rec.filter(x=>landedCostStatus(x.r).status==='CONFIRMAT').length;document.querySelector('#kSimulated').textContent=rec.filter(x=>landedCostStatus(x.r).status==='SIMULAT').length;document.querySelector('#kIncomplete').textContent=rec.filter(x=>landedCostStatus(x.r).status==='INCOMPLET').length;const confirmed=rec.filter(x=>landedCostStatus(x.r).status==='CONFIRMAT'&&calculateLandedCost(x.r).perUnit);document.querySelector('#kAvg').textContent=confirmed.length?money(confirmed.reduce((s,x)=>s+calculateLandedCost(x.r).perUnit,0)/confirmed.length):'—';}
function openEditor(name){const p=products.find(x=>x.name===name);if(!p)return;editing=name;const r=recordFor(name),set=(id,v)=>document.querySelector(id).value=v||'';document.querySelector('#lcProduct').textContent=`${name} • cost radar ${money(p.landed)}`;set('#lcCurrency',r.currency);set('#lcFx',r.fxRate);set('#lcUnitForeign',r.unitPriceForeign);set('#lcQty',r.quantity);set('#lcIntlFreight',r.internationalFreight);set('#lcDutyRate',r.customsDutyRate);set('#lcCustomsFixed',r.customsFixed);set('#lcBrokerage',r.brokerage);set('#lcDomestic',r.domesticFreight);set('#lcInspection',r.inspection);set('#lcLabels',r.labelsPackaging);set('#lcOther',r.otherFixed);document.querySelector('#lcConfirmed').checked=r.confirmed;document.querySelector('#lcNotes').value=r.notes;updatePreview();document.querySelector('#lcDialog').showModal();}
function collect(){const g=id=>document.querySelector(id)?.value;return normalizeLandedRecord({currency:g('#lcCurrency'),fxRate:g('#lcFx'),unitPriceForeign:g('#lcUnitForeign'),quantity:g('#lcQty'),internationalFreight:g('#lcIntlFreight'),customsDutyRate:g('#lcDutyRate'),customsFixed:g('#lcCustomsFixed'),brokerage:g('#lcBrokerage'),domesticFreight:g('#lcDomestic'),inspection:g('#lcInspection'),labelsPackaging:g('#lcLabels'),otherFixed:g('#lcOther'),confirmed:document.querySelector('#lcConfirmed')?.checked,notes:g('#lcNotes')});}
function updatePreview(){const c=calculateLandedCost(collect());document.querySelector('#lcPreview').innerHTML=`<b>${c.perUnit?money(c.perUnit):'—'} / buc.</b><span>Marfă ${money(c.goodsRon)} • transport ${money(c.internationalFreight)} • vamă ${money(c.duty)} • costuri fixe ${money(c.fixed)} • total ${money(c.total)}</span>`;}
if(typeof document!=='undefined'){document.querySelector('#lcSearch')?.addEventListener('input',render);document.querySelector('#lcFilter')?.addEventListener('change',render);document.querySelector('#lcGrid')?.addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(b)openEditor(decodeURIComponent(b.dataset.edit));});document.querySelector('#lcForm')?.addEventListener('input',updatePreview);document.querySelector('#lcForm')?.addEventListener('submit',e=>{e.preventDefault();if(!editing)return;saveRecord(editing,collect());document.querySelector('#lcDialog').close();render();});document.querySelector('#lcCancel')?.addEventListener('click',()=>document.querySelector('#lcDialog').close());loadProducts();}
