import {installCloudAutosync} from './cloud-sync.js';
import {evaluateLandedCostEvidence} from './landed-cost-evidence.js';
import {attachCanonicalCommercialIdentity,readCommercialRecord,writeCanonicalCommercialRecord} from './commercial-identity-v1.js';
import {isCanonicalProductId} from './domain-contracts-v1.js';
import {activeMarketProfile} from './market-profiles-v1.js';
import {calculateFreightCost} from './freight-chargeable-v1.js';
await installCloudAutosync();
const LANDED_KEY='megaRadarLandedCostRecordsV1';
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const hasValue=v=>v!==null&&v!==undefined&&!(typeof v==='string'&&v.trim()==='');
const keyOf=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>`${n(v).toLocaleString('ro-RO',{maximumFractionDigits:2})} lei`;
const NUMERIC_FIELDS=['fxRate','unitPriceForeign','quantity','internationalFreight','customsDutyRate','customsFixed','brokerage','domesticFreight','inspection','labelsPackaging','otherFixed'];
const MARKET=activeMarketProfile();
function providedMap(v={}){
  const legacy=!v.provided||typeof v.provided!=='object';
  return Object.fromEntries(NUMERIC_FIELDS.map(field=>{
    if(!legacy)return[field,v.provided[field]===true];
    const raw=v[field];
    return[field,hasValue(raw)&&Number.isFinite(Number(raw))&&Number(raw)>0];
  }));
}
function productIdentity(p={}){return{canonicalProductId:p.canonicalProductId||p.canonical_product_id||null,productName:p.name||p.productName||null};}
function productToken(p={}){const id=productIdentity(p).canonicalProductId;return isCanonicalProductId(id)?`canonical:${id.toLowerCase()}`:`legacy:${keyOf(p.name||p.productName||'')}`;}
export function normalizeLandedRecord(v={}){
  const provided=providedMap(v);
  const canonicalProductId=isCanonicalProductId(v.canonicalProductId||v.canonical_product_id)?String(v.canonicalProductId||v.canonical_product_id).toLowerCase():null;
  const decisionEligible=canonicalProductId?Boolean(v.decisionEligible??true):false;
  const base={canonicalProductId,productName:String(v.productName||'').trim()||null,identityStatus:canonicalProductId?'CANONICAL':'LEGACY_LABEL_ONLY',decisionEligible,marketCode:String(v.marketCode||MARKET.code).toUpperCase(),currency:['CNY','USD','EUR','RON'].includes(String(v.currency||'').toUpperCase())?String(v.currency).toUpperCase():'CNY',fxRate:Math.max(0,n(v.fxRate)),unitPriceForeign:Math.max(0,n(v.unitPriceForeign)),quantity:Math.max(0,Math.round(n(v.quantity))),internationalFreight:Math.max(0,n(v.internationalFreight)),freightMode:String(v.freightMode||'QUOTE_TOTAL').toUpperCase(),cartonLengthCm:Math.max(0,n(v.cartonLengthCm)),cartonWidthCm:Math.max(0,n(v.cartonWidthCm)),cartonHeightCm:Math.max(0,n(v.cartonHeightCm)),cartons:Math.max(1,Math.round(n(v.cartons)||1)),actualGrossWeightKg:Math.max(0,n(v.actualGrossWeightKg)),volumetricDivisor:Math.max(0,n(v.volumetricDivisor)),freightRateRonPerKg:Math.max(0,n(v.freightRateRonPerKg)),freightRateRonPerCbm:Math.max(0,n(v.freightRateRonPerCbm)),customsDutyRate:Math.max(0,n(v.customsDutyRate)),customsFixed:Math.max(0,n(v.customsFixed)),brokerage:Math.max(0,n(v.brokerage)),domesticFreight:Math.max(0,n(v.domesticFreight)),inspection:Math.max(0,n(v.inspection)),labelsPackaging:Math.max(0,n(v.labelsPackaging)),otherFixed:Math.max(0,n(v.otherFixed)),importVatRatePct:Math.max(0,n(v.importVatRatePct)||MARKET.importVatRatePct),importVatRecoverable:v.importVatRecoverable===true,provided,fxSource:String(v.fxSource||'').trim(),fxVerifiedAt:String(v.fxVerifiedAt||'').trim(),customsStatus:String(v.customsStatus||'').trim(),customsClassificationRef:String(v.customsClassificationRef||'').trim(),importVatTreatment:String(v.importVatTreatment||'').trim(),vatCostReference:String(v.vatCostReference||'').trim(),freightEvidenceRef:String(v.freightEvidenceRef||'').trim(),supplierQuoteRef:String(v.supplierQuoteRef||'').trim(),manualVerifiedBy:String(v.manualVerifiedBy||'').trim(),manualVerifiedAt:String(v.manualVerifiedAt||'').trim(),confirmationRequested:Boolean(v.confirmationRequested??v.confirmed),notes:String(v.notes||'').trim(),updatedAt:String(v.updatedAt||'').trim()};
  if(base.freightMode!=='QUOTE_TOTAL'){
    const freightCalc=calculateFreightCost({
      mode:base.freightMode,lengthCm:base.cartonLengthCm,widthCm:base.cartonWidthCm,heightCm:base.cartonHeightCm,cartons:base.cartons,
      actualGrossWeightKg:base.actualGrossWeightKg,divisor:base.volumetricDivisor,
      rateRonPerChargeableKg:base.freightRateRonPerKg,rateRonPerCbm:base.freightRateRonPerCbm
    });
    if(freightCalc.status==='CALCULATED'){
      base.internationalFreight=freightCalc.costRon;
      base.provided={...base.provided,internationalFreight:true};
    }
  }
  const evidence=evaluateLandedCostEvidence(base);
  return{...base,evidence,confirmed:base.decisionEligible===true&&base.confirmationRequested&&evidence.readyForManualConfirmation===true};
}
export function calculateLandedCost(v={}){
  const r=normalizeLandedRecord(v),qty=r.quantity,goodsRon=r.unitPriceForeign*r.fxRate*qty;
  const freightCalc=calculateFreightCost({
    mode:r.freightMode,
    quotedFreightRon:r.internationalFreight,
    lengthCm:r.cartonLengthCm,widthCm:r.cartonWidthCm,heightCm:r.cartonHeightCm,cartons:r.cartons,
    actualGrossWeightKg:r.actualGrossWeightKg,divisor:r.volumetricDivisor,
    rateRonPerChargeableKg:r.freightRateRonPerKg,rateRonPerCbm:r.freightRateRonPerCbm
  });
  const freight=freightCalc.status==='CALCULATED'?freightCalc.costRon:r.internationalFreight;
  const customsBase=goodsRon+freight;
  const duty=customsBase*(r.customsDutyRate/100);
  const importVatBase=customsBase+duty+r.customsFixed+r.brokerage;
  const importVat=importVatBase*(r.importVatRatePct/100);
  const fixed=r.customsFixed+r.brokerage+r.domesticFreight+r.inspection+r.labelsPackaging+r.otherFixed;
  const cashTotal=goodsRon+freight+duty+importVat+fixed;
  const economicTotal=cashTotal-(r.importVatRecoverable?importVat:0);
  const cashPerUnit=qty?cashTotal/qty:0,perUnit=qty?economicTotal/qty:0;
  return{...r,freightCalc,internationalFreight:freight,goodsRon,customsBase,duty,importVatBase,importVat,fixed,cashTotal,economicTotal,total:economicTotal,cashPerUnit,perUnit,valid:r.provided.fxRate&&r.provided.unitPriceForeign&&r.provided.quantity&&qty>0&&r.fxRate>0&&r.unitPriceForeign>0};
}
export function landedCostStatus(v={}){const c=calculateLandedCost(v);if(!c.valid)return{status:'INCOMPLET',reason:'Completează explicit prețul, cursul și cantitatea.'};if(!c.decisionEligible)return{status:'SIMULAT',reason:'Calcul disponibil, dar Economics Gate este blocat până când produsul are canonicalProductId.',evidence:c.evidence,identityBlocked:true};if(!c.confirmed){const missing=c.evidence?.blockers||[];return{status:'SIMULAT',reason:c.confirmationRequested&&missing.length?`Confirmarea este blocată: ${missing.slice(0,3).join(' · ')}`:'Calcul disponibil, dar landed cost nu este confirmat din dovezi complete.',evidence:c.evidence};}return{status:'CONFIRMAT',reason:'Costurile și dovezile au fost verificate manual pentru produsul canonic; zero-urile sunt explicite.',evidence:c.evidence};}
function loadJson(key){try{return JSON.parse(localStorage.getItem(key)||'{}')||{};}catch{return{};}}
function allRecords(){return loadJson(LANDED_KEY);}
function recordFor(product){const identity=productIdentity(product),hit=readCommercialRecord(allRecords(),identity);return normalizeLandedRecord(hit.record?{...hit.record,decisionEligible:hit.decisionEligible}:attachCanonicalCommercialIdentity({},identity));}
function saveRecord(product,record){const all=allRecords(),identity=productIdentity(product),clean=normalizeLandedRecord({...record,...identity}),calc=calculateLandedCost({...clean,...identity});clean.updatedAt=new Date().toISOString();clean.productName=identity.productName;clean.canonicalProductId=isCanonicalProductId(identity.canonicalProductId)?String(identity.canonicalProductId).toLowerCase():null;clean.identityStatus=clean.canonicalProductId?'CANONICAL':'LEGACY_LABEL_ONLY';clean.decisionEligible=Boolean(clean.canonicalProductId);clean.confirmed=clean.decisionEligible&&clean.confirmationRequested&&clean.evidence?.readyForManualConfirmation===true;clean.landedPerUnit=calc.valid?calc.perUnit:0;clean.totalLandedCost=calc.valid?calc.total:0;clean.costStatus=landedCostStatus(clean).status;let next;if(clean.canonicalProductId){next=writeCanonicalCommercialRecord(all,identity,clean);}else{const legacyKey=keyOf(identity.productName);clean.confirmed=false;clean.decisionEligible=false;next={...all,[legacyKey]:attachCanonicalCommercialIdentity(clean,identity)};}localStorage.setItem(LANDED_KEY,JSON.stringify(next));return clean;}
let products=[],editingToken='';
async function loadProducts(){let data=null;try{const r=await fetch(`radar-live.json?t=${Date.now()}`,{cache:'no-store'});if(r.ok)data=await r.json();}catch{}if(!Array.isArray(data?.products)){const r=await fetch(`products.json?t=${Date.now()}`,{cache:'no-store'});data={products:await r.json()};}products=(data.products||[]).filter(p=>p&&p.name);render();}
function row(p){const r=recordFor(p),c=calculateLandedCost(r),s=landedCostStatus(r),delta=c.perUnit&&n(p.landed)?c.perUnit-n(p.landed):0,has=Boolean(r.quantity||r.unitPriceForeign||r.fxRate||r.confirmationRequested),identityNote=r.decisionEligible?'CANONICAL':'IDENTITY PENDING';return `<article class="lc-card"><div class="lc-top"><div><h3>${esc(p.name)}</h3><small>${esc(p.cat||'')} · ${identityNote}</small></div><span class="badge ${s.status==='CONFIRMAT'?'ok':s.status==='SIMULAT'?'sim':''}">${s.status}</span></div><div class="metrics"><div><small>Cost estimat de radar</small><b>${money(p.landed)}</b></div><div><small>Cost total calculat</small><b>${c.perUnit?money(c.perUnit):'—'}</b></div><div><small>Diferență</small><b>${c.perUnit?`${delta>=0?'+':''}${money(delta)}`:'—'}</b></div><div><small>Total lot</small><b>${c.total?money(c.total):'—'}</b></div></div><p>${esc(s.reason)}</p><button data-edit="${encodeURIComponent(productToken(p))}">${has?'Editează costul':'Calculează costul de import'}</button></article>`;}
function render(){const q=(document.querySelector('#lcSearch')?.value||'').trim().toLowerCase(),f=document.querySelector('#lcFilter')?.value||'';let a=products.filter(p=>!q||`${p.name} ${p.cat||''}`.toLowerCase().includes(q));if(f)a=a.filter(p=>landedCostStatus(recordFor(p)).status===f);document.querySelector('#lcGrid').innerHTML=a.length?a.map(row).join(''):'<div class="empty">Nu există produse pentru filtrul selectat.</div>';const rec=products.map(p=>({p,r:recordFor(p)}));document.querySelector('#kConfirmed').textContent=rec.filter(x=>landedCostStatus(x.r).status==='CONFIRMAT').length;document.querySelector('#kSimulated').textContent=rec.filter(x=>landedCostStatus(x.r).status==='SIMULAT').length;document.querySelector('#kIncomplete').textContent=rec.filter(x=>landedCostStatus(x.r).status==='INCOMPLET').length;const confirmed=rec.filter(x=>landedCostStatus(x.r).status==='CONFIRMAT'&&calculateLandedCost(x.r).perUnit);document.querySelector('#kAvg').textContent=confirmed.length?money(confirmed.reduce((s,x)=>s+calculateLandedCost(x.r).perUnit,0)/confirmed.length):'—';}
function productByToken(token){return products.find(p=>productToken(p)===token)||null;}
function openEditor(token){const p=productByToken(token);if(!p)return;editingToken=token;const r=recordFor(p),set=(id,v)=>{const el=document.querySelector(id);if(el)el.value=v??'';};document.querySelector('#lcProduct').textContent=`${p.name} • cost radar ${money(p.landed)} • ${r.decisionEligible?'canonical identity':'identity pending — confirmarea este blocată'}`;set('#lcCurrency',r.currency);set('#lcFx',r.provided.fxRate?r.fxRate:'');set('#lcUnitForeign',r.provided.unitPriceForeign?r.unitPriceForeign:'');set('#lcQty',r.provided.quantity?r.quantity:'');set('#lcFreightMode',r.freightMode);set('#lcIntlFreight',r.freightMode==='QUOTE_TOTAL'&&r.provided.internationalFreight?r.internationalFreight:'');set('#lcCartonL',r.cartonLengthCm||'');set('#lcCartonW',r.cartonWidthCm||'');set('#lcCartonH',r.cartonHeightCm||'');set('#lcCartons',r.cartons||1);set('#lcGrossKg',r.actualGrossWeightKg||'');set('#lcVolDivisor',r.volumetricDivisor||'');set('#lcRateKg',r.freightRateRonPerKg||'');set('#lcRateCbm',r.freightRateRonPerCbm||'');set('#lcVatRate',r.importVatRatePct||MARKET.importVatRatePct);document.querySelector('#lcVatRecoverable').checked=r.importVatRecoverable===true;set('#lcDutyRate',r.provided.customsDutyRate?r.customsDutyRate:'');set('#lcCustomsFixed',r.provided.customsFixed?r.customsFixed:'');set('#lcBrokerage',r.provided.brokerage?r.brokerage:'');set('#lcDomestic',r.provided.domesticFreight?r.domesticFreight:'');set('#lcInspection',r.provided.inspection?r.inspection:'');set('#lcLabels',r.provided.labelsPackaging?r.labelsPackaging:'');set('#lcOther',r.provided.otherFixed?r.otherFixed:'');set('#lcFxSource',r.fxSource);set('#lcFxVerifiedAt',r.fxVerifiedAt?String(r.fxVerifiedAt).slice(0,16):'');set('#lcCustomsStatus',r.customsStatus);set('#lcCustomsRef',r.customsClassificationRef);set('#lcVatTreatment',r.importVatTreatment);set('#lcVatRef',r.vatCostReference);set('#lcFreightRef',r.freightEvidenceRef);set('#lcQuoteRef',r.supplierQuoteRef);set('#lcVerifiedBy',r.manualVerifiedBy);set('#lcVerifiedAt',r.manualVerifiedAt?String(r.manualVerifiedAt).slice(0,16):'');document.querySelector('#lcConfirmed').checked=r.confirmationRequested&&r.decisionEligible;document.querySelector('#lcConfirmed').disabled=!r.decisionEligible;document.querySelector('#lcNotes').value=r.notes;updatePreview();document.querySelector('#lcDialog').showModal();}
function collect(){const g=id=>document.querySelector(id)?.value??'',provided=Object.fromEntries([['fxRate','#lcFx'],['unitPriceForeign','#lcUnitForeign'],['quantity','#lcQty'],['internationalFreight','#lcIntlFreight'],['customsDutyRate','#lcDutyRate'],['customsFixed','#lcCustomsFixed'],['brokerage','#lcBrokerage'],['domesticFreight','#lcDomestic'],['inspection','#lcInspection'],['labelsPackaging','#lcLabels'],['otherFixed','#lcOther']].map(([field,id])=>[field,String(g(id)).trim()!=='']));return normalizeLandedRecord({marketCode:'RO',currency:g('#lcCurrency'),fxRate:g('#lcFx'),unitPriceForeign:g('#lcUnitForeign'),quantity:g('#lcQty'),freightMode:g('#lcFreightMode'),internationalFreight:g('#lcIntlFreight'),cartonLengthCm:g('#lcCartonL'),cartonWidthCm:g('#lcCartonW'),cartonHeightCm:g('#lcCartonH'),cartons:g('#lcCartons'),actualGrossWeightKg:g('#lcGrossKg'),volumetricDivisor:g('#lcVolDivisor'),freightRateRonPerKg:g('#lcRateKg'),freightRateRonPerCbm:g('#lcRateCbm'),importVatRatePct:g('#lcVatRate'),importVatRecoverable:document.querySelector('#lcVatRecoverable')?.checked,customsDutyRate:g('#lcDutyRate'),customsFixed:g('#lcCustomsFixed'),brokerage:g('#lcBrokerage'),domesticFreight:g('#lcDomestic'),inspection:g('#lcInspection'),labelsPackaging:g('#lcLabels'),otherFixed:g('#lcOther'),provided,fxSource:g('#lcFxSource'),fxVerifiedAt:g('#lcFxVerifiedAt'),customsStatus:g('#lcCustomsStatus'),customsClassificationRef:g('#lcCustomsRef'),importVatTreatment:g('#lcVatTreatment'),vatCostReference:g('#lcVatRef'),freightEvidenceRef:g('#lcFreightRef'),supplierQuoteRef:g('#lcQuoteRef'),manualVerifiedBy:g('#lcVerifiedBy'),manualVerifiedAt:g('#lcVerifiedAt'),confirmationRequested:document.querySelector('#lcConfirmed')?.checked,notes:g('#lcNotes')});}
function updatePreview(){const product=productByToken(editingToken)||{},c=calculateLandedCost({...collect(),...productIdentity(product)}),e=c.evidence||{},identityMessage=c.decisionEligible?'':' · IDENTITY_BLOCKED';document.querySelector('#lcPreview').innerHTML=`<b>${c.perUnit?money(c.perUnit):'—'} / buc. economic</b><span>Marfă ${money(c.goodsRon)} • transport ${money(c.internationalFreight)} • vamă ${money(c.duty)} • TVA import ${money(c.importVat)} • costuri fixe ${money(c.fixed)} • cash total ${money(c.cashTotal)}</span><span>Transport: ${esc(c.freightCalc?.basis||'UNKNOWN')} ${c.freightCalc?.chargeableWeight?.chargeableKg?`• greutate taxabilă ${c.freightCalc.chargeableWeight.chargeableKg} kg`:''} ${c.freightCalc?.volume?.volumeM3?`• ${c.freightCalc.volume.volumeM3} m³`:''}</span><span class="${e.readyForManualConfirmation&&c.decisionEligible?'good':'warn'}">${e.readyForManualConfirmation&&c.decisionEligible?'EVIDENCE_COMPLETE — poate fi confirmat manual':'EVIDENCE/IDENTITY INCOMPLETE — '+esc((e.blockers||[]).slice(0,5).join(' · '))+identityMessage}</span>`;}
if(typeof document!=='undefined'){document.querySelector('#lcSearch')?.addEventListener('input',render);document.querySelector('#lcFilter')?.addEventListener('change',render);document.querySelector('#lcGrid')?.addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(b)openEditor(decodeURIComponent(b.dataset.edit));});document.querySelector('#lcForm')?.addEventListener('input',updatePreview);document.querySelector('#lcForm')?.addEventListener('submit',e=>{e.preventDefault();const product=productByToken(editingToken);if(!product)return;saveRecord(product,collect());document.querySelector('#lcDialog').close();render();});document.querySelector('#lcCancel')?.addEventListener('click',()=>document.querySelector('#lcDialog').close());loadProducts();}
