import {SAAS_CONFIG,isSaasConfigured} from './saas-config.js';
import {getCurrentSession,resetPassword,signInWithPassword,signUp} from './supabase-client.js';
const $=s=>document.querySelector(s);function status(text,kind=''){const el=$('#status');el.textContent=text;el.dataset.kind=kind;}
function loginCredentials(){const email=$('#email').value.trim(),password=$('#password').value;if(!email.includes('@'))throw new Error('Introdu un email valid.');if(!password)throw new Error('Introdu parola.');return{email,password};}
function signupCredentials(){const {email,password}=loginCredentials();if(password.length<12)throw new Error('Parola trebuie să aibă minimum 12 caractere.');if(!/[a-z]/.test(password)||!/[A-Z]/.test(password)||!/[0-9]/.test(password)||!/[\W_]/.test(password))throw new Error('Parola trebuie să conțină literă mică, literă mare, cifră și simbol.');if(!$('#acceptBeta')?.checked)throw new Error('Pentru crearea contului trebuie să confirmi testarea profesională și să accepți documentele beta.');return{email,password};}
function destination(){const next=new URLSearchParams(location.search).get('next')||'';return /^[a-z0-9][a-z0-9._-]*\.html(?:\?.*)?$/i.test(next)?next:'home.html';}
if(isSaasConfigured(SAAS_CONFIG))$('#foundation').hidden=true;
getCurrentSession().then(s=>{if(s)location.href=destination();});
$('#login').addEventListener('click',async()=>{try{status('Autentificare...');const {email,password}=loginCredentials();await signInWithPassword(email,password);location.href=destination();}catch(e){status(e.message,'error');}});
$('#signup').addEventListener('click',async()=>{try{status('Creare cont...');const {email,password}=signupCredentials();const data=await signUp(email,password,{betaPurpose:'professional',termsVersion:'2026-09-02',privacyVersion:'2026-09-02',freeBetaOnly:true});status(data.session?'Cont creat. Redirecționare...':'Cont creat. Verifică emailul pentru confirmare.','ok');if(data.session)location.href=destination();}catch(e){status(e.message,'error');}});
$('#reset').addEventListener('click',async()=>{try{const email=$('#email').value.trim();if(!email.includes('@'))throw new Error('Introdu emailul contului.');await resetPassword(email);status('Dacă există un cont pentru această adresă, vei primi instrucțiunile de resetare.','ok');}catch(e){status('Cererea de resetare nu a putut fi procesată momentan.','error');}});
