const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const safe=u=>{try{const x=new URL(u);return['http:','https:'].includes(x.protocol)?x.href:'#'}catch{return'#'}};
const phraseMap=[
  [/pet stain\s*&?\s*odor remover/gi,'soluție pentru pete și mirosuri de animale'],[/dog stain\s*&?\s*odor remover/gi,'soluție pentru pete și mirosuri de câine'],[/enzyme cleaner/gi,'soluție enzimatică'],[/enzymatic cleaner/gi,'soluție enzimatică'],[/carpet cleaner/gi,'soluție pentru curățarea covoarelor'],[/hard floor/gi,'pardoseală dură'],[/spray bottle/gi,'flacon spray'],[/heavy traffic foam/gi,'spumă pentru zone intens circulate'],[/urine destroyer/gi,'soluție pentru eliminarea petelor de urină'],[/problem solver/gi,'soluție practică'],[/food storage/gi,'depozitare alimente'],[/space saving/gi,'economisire spațiu'],[/home workout/gi,'antrenament acasă'],[/makeup accessory/gi,'accesoriu machiaj'],[/hair accessory/gi,'accesoriu pentru păr'],[/stroller accessory/gi,'accesoriu cărucior'],[/kids learning activity/gi,'activitate educațională pentru copii'],[/travel accessory/gi,'accesoriu de călătorie'],[/car accessory/gi,'accesoriu auto']
];
const wordMap=[['car','auto'],['headrest','tetieră'],['holder','suport'],['organizer','organizator'],['storage','depozitare'],['travel','călătorie'],['kitchen','bucătărie'],['home','casă'],['kids','copii'],['baby','bebe'],['pet','animale'],['dog','câine'],['cat','pisică'],['foldable','pliabil'],['portable','portabil'],['adjustable','reglabil'],['magnetic','magnetic'],['wall','perete'],['drawer','sertar'],['bag','geantă'],['clip','clemă'],['rack','suport'],['tray','tavă'],['hook','cârlig'],['set','set'],['new','nou'],['cleaner','soluție de curățare'],['remover','îndepărtare'],['stain','pete'],['odor','miros'],['floor','podea'],['bottle','flacon'],['spray','spray'],['accessory','accesoriu'],['learning','educațional'],['activity','activitate'],['recovery','recuperare'],['fitness','fitness'],['gadget','dispozitiv']];
function roName(name){let s=String(name||'').replace(/&#x27;|&#39;/gi,"'");for(const [re,b] of phraseMap)s=s.replace(re,b);for(const [a,b] of wordMap)s=s.replace(new RegExp(`\\b${a}\\b`,'gi'),b);s=s.replace(/\s+/g,' ').trim();return s.charAt(0).toUpperCase()+s.slice(1)}
function imageOk(u){const s=String(u||'');return /^https?:\/\//i.test(s)&&!/\.svg(?:$|\?)/i.test(s)&&!/01rrzVoKd5L|sprite|transparent|pixel|spacer/i.test(s)}
let data={feed:[],products:[]},filter='ALL';
function fmtDelta(v){return v===null||v===undefined?'istoric în formare':v>0?`+${v} poziții`:v<0?`${v} poziții`:'fără schimbare'}
function card(p){const title=roName(p.name),img=imageOk(p.image)?`<img class="thumb" src="${esc(safe(p.image))}" alt="${esc(title)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.replaceWith(Object.assign(document.createElement('div'),{className:'thumb placeholder',textContent:'Imagine indisponibilă încă'}))">`:`<div class="thumb placeholder">Imagine indisponibilă încă</div>`;const rev=p.reviewCount===null?'necunoscut':Math.trunc(Number(p.reviewCount));return `<article class="rise-card card">${img}<div><div class="topline"><div><div class="section-kicker">${esc(p.signal||'DE URMĂRIT')}</div><h3>${esc(title)}</h3><div class="cat">${esc(p.category||'')} • ${esc(p.sourceMarket||'')}</div></div><div class="score-pill"><b>${Number(p.organicRiseScore||0)}</b><small>URCARE</small></div></div><div class="meta-grid"><div class="metric"><small>Poziție organică</small><b>#${Number(p.organicRank||0)} / pag. ${Number(p.organicPage||0)}</b></div><div class="metric"><small>Review-uri</small><b>${esc(rev)}</b></div><div class="metric"><small>Selleri observați</small><b>${Number(p.observedSellerCount||0)}</b></div><div class="metric"><small>Competiție RO</small><b>${Number(p.romaniaCompetition||0)}</b></div><div class="metric"><small>Evoluție</small><b>${esc(fmtDelta(p.rankDelta))}</b></div><div class="metric"><small>Marketplace-uri</small><b>${Number(p.crossMarketCount||0)}</b></div></div><div class="validation">${esc(p.validation||'')}</div>${p.sourceUrl?`<a class="secondary-link source" href="${esc(safe(p.sourceUrl))}" target="_blank" rel="noopener">Deschide produsul sursă</a>`:''}</div></article>`}
function apply(){let list=[...(data.feed||[])];if(filter==='STRONG')list=list.filter(p=>Number(p.organicRiseScore||0)>=80);if(filter==='LOWREV')list=list.filter(p=>p.reviewCount!==null&&Number(p.reviewCount)<=10);if(filter==='LOWRO')list=list.filter(p=>Number(p.romaniaCompetition||0)<=3);$('#riseGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty card">Nu există încă produse care să treacă filtrul selectat. Motorul continuă să construiască istoric.</div>';$('#kFeed').textContent=(data.feed||[]).length;$('#kStrong').textContent=(data.feed||[]).filter(p=>Number(p.organicRiseScore||0)>=80).length;$('#kObserved').textContent=Number(data.totalObserved||0);$('#kCategory').textContent=data.category||'—'}
async function load(){try{const r=await fetch(`organic-rising-live.json?t=${Date.now()}`,{cache:'no-store'});if(r.ok)data=await r.json()}catch{}apply()}
document.querySelectorAll('[data-f]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-f]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.f;apply()}));load();