const PURCHASE_KEY='megaRadarPurchaseRecordsV1',SUPPLIER_KEY='megaRadarSupplierRecordsV1';
export const PURCHASE_STATUSES=['DE VERIFICAT','SAMPLE COMANDAT','APROBAT','READY TO ORDER','COMANDAT'];
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const keyOf=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>`${n(v).toLocaleString('ro-RO',{maximumFractionDigits:2})} lei`;
export function normalizePurchaseRecord(v={}){const status=PURCHASE_STATUSES.includes(String(v.status||''))?String(v.status):'DE VERIFICAT';return{status,quantity:Math.max(0,Math.round(n(v.quantity))),targetUnitCost:Math.max(0,n(v.targetUnitCost)),sampleOrdered:Boolean(v.sampleOrdered),sampleApproved:Boolean(v.sampleApproved),complianceDocs:Boolean(v.complianceDocs),packagingConfirmed:Boolean(v.packagingConfirmed),landedCostConfirmed:Boolean(v.landedCostConfirmed),paymentTermsConfirmed:Boolean(v.paymentTermsConfirmed),orderNumber:String(v.orderNumber||'').trim(),notes:String(v.notes||'').trim(),updatedAt:String(v.updatedAt||'').trim(),orderedAt:String(v.orderedAt||'').trim()};}
export function supplierReady(s={}){const certs=Array.isArray(s.certifications)?s.certifications:[];return Boolean((s.supplierName||s.url)&&n(s.moq)>0&&n(s.rating)>=4.3&&n(s.years)>=2&&(s.tradeAssurance===true||certs.length>0));}
export function purchaseBlockers(record={},supplier={}){const r=normalizePurchaseRecord(record),b=[];if(!supplierReady(supplier))b.push('Furnizorul nu este SUPPLIER OK');if(n(supplier.moq)>0&&r.quantity<n(supplier.moq))b.push(`Cantitatea este sub MOQ (${Math.round(n(supplier.moq))})`);if(!r.sampleOrdered)b.push('Sample-ul nu este comandat');if(!r.sampleApproved)b.push('Sample-ul nu este aprobat');if(!r.complianceDocs)b.push('Documentele/compliance nu sunt confirmate');if(!r.packagingConfirmed)b.push('Ambalarea nu este confirmată');if(!r.landedCostConfirmed)b.push('Landed cost-ul nu este confirmat');if(!r.paymentTermsConfirmed)b.push('Condițiile de plată nu sunt confirmate');return b;}
export function highestAllowedStatus(record={},supplier={}){const r=normalizePurchaseRecord(record);if(!r.sampleOrdered)return'DE VERIFICAT';if(!r.sampleApproved)return'SAMPLE COMANDAT';const blockers=purchaseBlockers(r,supplier);if(blockers.length)return'APROBAT';return r.orderNumber||r.orderedAt?'COMANDAT':'READY TO ORDER';}
export function purchaseEconomics(product={},record={},supplier={}){const r=normalizePurchaseRecord(record),unit=r.targetUnitCost||n(product.landed),qty=r.quantity,orderValue=unit*qty,revenue=n(product.sell)*qty;return{unitCost:unit,quantity:qty,orderValue,revenue,grossSpread:revenue-orderValue};}
function loadJson(key){try{return JSON.parse(localStorage.getItem(key)||'{}')||{};}catch{return{};}}
function allPurchaseRecords(){return loadJson(PURCHASE_KEY);}
function allSupplierRecords(){return loadJson(SUPPLIER_KEY);}
function recordFor(name){return normalizePurchaseRecord(allPurchaseRecords()[keyOf(name)]||{});}
function supplierFor(name){return allSupplierRecords()[keyOf(name)]||{};}
function saveRecord(name,record){const all=allPurchaseRecords(),clean=normalizePurchaseRecord(record);clean.updatedAt=new Date().toISOString();if(clean.status==='COMANDAT'&&!clean.orderedAt)clean.orderedAt=clean.updatedAt;all[keyOf(name)]=clean;localStorage.setItem(PURCHASE_KEY,JSON.stringify(all));return clean;}
let products=[],filter='ACTIVE',editing='';
async function loadProducts(){let data=null;try{const r=await fetch(`radar-live.json?t=${Date.now()}`,{cache:'no-store'});if(r.ok)data=await r.json();}catch{}if(!Array.isArray(data?.products)){const r=await fetch(`products.json?t=${Date.now()}`,{cache:'no-store'});data={products:await r.json()};}products=(data.products||[]).filter(p=>p&&p.name);render();}
function row(p){const r=recordFor(p.name),s=supplierFor(p.name),econ=purchaseEconomics(p,r,s),blockers=purchaseBlockers(r,s),allowed=highestAllowedStatus(r,s),hasData=Boolean(r.quantity||r.sampleOrdered||r.sampleApproved||r.orderNumber||r.notes),supplierName=s.supplierName||'Furnizor neales';return `<article class="purchase-card"><div class="pc-top"><div><h3>${esc(p.name)}</h3><small>${esc(p.cat||'')} • ${esc(supplierName)}</small></div><span class="status ${r.status==='COMANDAT'?'done':r.status==='READY TO ORDER'?'ready':''}">${esc(r.status)}</span></div><div class="pc-metrics"><div><small>MOQ</small><b>${n(s.moq)||'—'}</b></div><div><small>Cantitate</small><b>${r.quantity||'—'}</b></div><div><small>Valoare plan</small><b>${money(econ.orderValue)}</b></div><div><small>Preț vânzare</small><b>${money(p.sell)}</b></div></div><div class="progress"><span>Maxim permis acum: <b>${esc(allowed)}</b></span>${blockers.length?`<em>${esc(blockers.slice(0,3).join(' • '))}</em>`:'<em class="ok">Checklist complet pentru comandă.</em>'}</div><div class="checks"><span>${r.sampleOrdered?'✓':'○'} Sample comandat</span><span>${r.sampleApproved?'✓':'○'} Sample aprobat</span><span>${r.complianceDocs?'✓':'○'} Compliance</span><span>${r.landedCostConfirmed?'✓':'○'} Landed cost</span></div><button class="edit" data-edit="${encodeURIComponent(p.name)}">${hasData?'Editează achiziția':'Pornește achiziția'}</button></article>`;}
function render(){const q=(document.querySelector('#purchaseSearch')?.value||'').trim().toLowerCase();let a=products.filter(p=>!q||`${p.name} ${p.cat||''}`.toLowerCase().includes(q));if(filter==='READY')a=a.filter(p=>highestAllowedStatus(recordFor(p.name),supplierFor(p.name))==='READY TO ORDER');else if(filter==='SAMPLES')a=a.filter(p=>recordFor(p.name).sampleOrdered&&!recordFor(p.name).sampleApproved);else if(filter==='ORDERED')a=a.filter(p=>recordFor(p.name).status==='COMANDAT');else if(filter==='ACTIVE')a=a.filter(p=>{const r=recordFor(p.name);return r.quantity||r.sampleOrdered||r.sampleApproved||r.status!=='DE VERIFICAT';});document.querySelector('#purchaseGrid').innerHTML=a.length?a.map(row).join(''):'<div class="empty">Nu există produse în această etapă.</div>';const records=products.map(p=>({p,r:recordFor(p.name),s:supplierFor(p.name)}));document.querySelector('#kActive').textContent=records.filter(x=>x.r.quantity||x.r.sampleOrdered||x.r.status!=='DE VERIFICAT').length;document.querySelector('#kSamples').textContent=records.filter(x=>x.r.sampleOrdered&&!x.r.sampleApproved).length;document.querySelector('#kReady').textContent=records.filter(x=>highestAllowedStatus(x.r,x.s)==='READY TO ORDER').length;document.querySelector('#kOrdered').textContent=records.filter(x=>x.r.status==='COMANDAT').length;document.querySelector('#kCapital').textContent=money(records.reduce((sum,x)=>sum+purchaseEconomics(x.p,x.r,x.s).orderValue,0));}
function openEditor(name){const p=products.find(x=>x.name===name);if(!p)return;editing=name;const r=recordFor(name),s=supplierFor(name);document.querySelector('#pmProduct').textContent=name;document.querySelector('#pmSupplier').textContent=s.supplierName?`${s.supplierName} • MOQ ${n(s.moq)||'—'} • rating ${n(s.rating)||'—'}`:'Nu există furnizor verificat în 4.2.';document.querySelector('#pmStatus').value=r.status;document.querySelector('#pmQty').value=r.quantity||'';document.querySelector('#pmUnit').value=r.targetUnitCost||'';document.querySelector('#pmSampleOrdered').checked=r.sampleOrdered;document.querySelector('#pmSampleApproved').checked=r.sampleApproved;document.querySelector('#pmCompliance').checked=r.complianceDocs;document.querySelector('#pmPackaging').checked=r.packagingConfirmed;document.querySelector('#pmLanded').checked=r.landedCostConfirmed;document.querySelector('#pmPayment').checked=r.paymentTermsConfirmed;document.querySelector('#pmOrder').value=r.orderNumber;document.querySelector('#pmNotes').value=r.notes;document.querySelector('#purchaseDialog').showModal();}
function collect(){return normalizePurchaseRecord({status:document.querySelector('#pmStatus').value,quantity:document.querySelector('#pmQty').value,targetUnitCost:document.querySelector('#pmUnit').value,sampleOrdered:document.querySelector('#pmSampleOrdered').checked,sampleApproved:document.querySelector('#pmSampleApproved').checked,complianceDocs:document.querySelector('#pmCompliance').checked,packagingConfirmed:document.querySelector('#pmPackaging').checked,landedCostConfirmed:document.querySelector('#pmLanded').checked,paymentTermsConfirmed:document.querySelector('#pmPayment').checked,orderNumber:document.querySelector('#pmOrder').value,notes:document.querySelector('#pmNotes').value});}
if(typeof document!=='undefined'){document.querySelector('#purchaseSearch')?.addEventListener('input',render);document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render();}));document.querySelector('#purchaseGrid')?.addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(b)openEditor(decodeURIComponent(b.dataset.edit));});document.querySelector('#purchaseForm')?.addEventListener('submit',e=>{e.preventDefault();if(!editing)return;const s=supplierFor(editing),requested=collect(),allowed=highestAllowedStatus(requested,s),requestedIndex=PURCHASE_STATUSES.indexOf(requested.status),allowedIndex=PURCHASE_STATUSES.indexOf(allowed);if(requestedIndex>allowedIndex)requested.status=allowed;saveRecord(editing,requested);document.querySelector('#purchaseDialog').close();render();});document.querySelector('#pmCancel')?.addEventListener('click',()=>document.querySelector('#purchaseDialog').close());loadProducts();}
