import fs from 'node:fs/promises';
import { discoveryScore, suggestedDiscoveryStage } from '../discovery-engine.js';
import { appendHistoryPoint, discoveryTrendWindows } from '../discovery-history.js';
import { reviewEvidenceSummary } from '../review-intelligence.js';

const CATALOGUE_FILE='discovery-catalogue.json',THEMES_FILE='discovery-themes.json',LIVE_FILE='discovery-live.json',HISTORY_FILE='discovery-history.json',RADAR_FILE='radar-live.json',MAX_SCAN=10,MAX_INBOX=160;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const clean=s=>String(s||'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const slug=s=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const n=(v,min=0,max=10000)=>{const x=Number(v);return Number.isFinite(x)?Math.max(min,Math.min(max,x)):0};
async function readJson(path,fallback){try{return JSON.parse(await fs.readFile(path,'utf8'));}catch{return fallback;}}
function landedEstimate(p){if(!n(p.chinaMin)&&!n(p.chinaMax))return 0;const mid=(n(p.chinaMin)+n(p.chinaMax))/2;return Math.round((mid+Math.max(12,mid*.55)+3)*100)/100;}
function unwrapDdg(href=''){try{const u=new URL(href.startsWith('//')?`https:${href}`:href,'https://duckduckgo.com');return u.searchParams.get('uddg')||u.href;}catch{return href;}}
function parseResults(html=''){const links=[];const anchor=/<a[^>]+class="[^"]*result__a[^"]*"[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=anchor.exec(html))&&links.length<5)links.push({url:unwrapDdg(m[1]),title:clean(m[2])});const snippets=[];const snip=/<(?:a|div)[^>]+class="[^"]*result__snippet[^"]*"[^>]*>([\s\S]*?)<\/(?:a|div)>/gi;while((m=snip.exec(html))&&snippets.length<5)snippets.push(clean(m[1]));return{links,snippets};}
async function ddgSearch(query){const searchUrl=`https://html.duckduckgo.com/html/?q=${encodeURIComponent(query)}`,controller=new AbortController(),timer=setTimeout(()=>controller.abort(),7000);try{const res=await fetch(searchUrl,{signal:controller.signal,headers:{'user-agent':'Mozilla/5.0 MegaProductRadarDiscovery/6.0','accept-language':'en-US,en;q=0.8'}});if(!res.ok)return{ok:false,present:false,resultCount:0,status:res.status,searchUrl,links:[],snippets:[]};const html=await res.text(),parsed=parseResults(html),rawCount=(html.match(/result__a/g)||[]).length;return{ok:true,present:parsed.links.length>0||rawCount>0,resultCount:Math.min(10,Math.max(parsed.links.length,rawCount)),searchUrl,...parsed};}catch(error){return{ok:false,present:false,resultCount:0,error:String(error?.message||error).slice(0,120),searchUrl,links:[],snippets:[]};}finally{clearTimeout(timer);}}
async function siteQuery(term,market,extra=''){return ddgSearch(`site:${market.domain} ${term} ${extra}`.trim());}
function sourcingLinks(name){const q=encodeURIComponent(name);return[{market:'Alibaba',url:`https://www.alibaba.com/trade/search?SearchText=${q}`,verified:false},{market:'1688',url:`https://s.1688.com/selloffer/offer_search.htm?keywords=${q}`,verified:false},{market:'Made-in-China',url:`https://www.made-in-china.com/productdirectory.do?word=${q}`,verified:false},{market:'Global Sources',url:`https://www.globalsources.com/search?query=${q}`,verified:false}];}
const markets=[
  {key:'amazonUS',domain:'amazon.com',kind:'foreign',label:'Amazon US'},
  {key:'amazonDE',domain:'amazon.de',kind:'foreign',label:'Amazon DE'},
  {key:'amazonIT',domain:'amazon.it',kind:'foreign',label:'Amazon IT'},
  {key:'amazonFR',domain:'amazon.fr',kind:'foreign',label:'Amazon FR'},
  {key:'allegroPL',domain:'allegro.pl',kind:'foreign',label:'Allegro PL'},
  {key:'trendyolTR',domain:'trendyol.com',kind:'foreign',label:'Trendyol TR'},
  {key:'etsy',domain:'etsy.com',kind:'foreign',label:'Etsy'},
  {key:'temu',domain:'temu.com',kind:'foreign',label:'Temu'},
  {key:'aliexpress',domain:'aliexpress.com',kind:'foreign',label:'AliExpress'},
  {key:'kickstarter',domain:'kickstarter.com',kind:'early',label:'Kickstarter'},
  {key:'indiegogo',domain:'indiegogo.com',kind:'early',label:'Indiegogo'},
  {key:'emagRO',domain:'emag.ro',kind:'romania',label:'eMAG RO'},
  {key:'alibabaCN',domain:'alibaba.com',kind:'china',label:'Alibaba'},
  {key:'1688CN',domain:'1688.com',kind:'china',label:'1688'},
  {key:'madeInChina',domain:'made-in-china.com',kind:'china',label:'Made-in-China'},
  {key:'globalSources',domain:'globalsources.com',kind:'china',label:'Global Sources'},
  {key:'tiktok',domain:'tiktok.com',kind:'social',label:'TikTok'},
  {key:'facebook',domain:'facebook.com',kind:'social',label:'Meta/Facebook'},
  {key:'pinterest',domain:'pinterest.com',kind:'social',label:'Pinterest'},
  {key:'youtube',domain:'youtube.com',kind:'social',label:'YouTube'}
];
const reviewMarkets=[{domain:'amazon.com',label:'Amazon US review search'},{domain:'amazon.de',label:'Amazon DE review search'},{domain:'reddit.com',label:'Reddit review search'},{domain:'youtube.com',label:'YouTube review search'}];
const bannedTitle=/amazon|allegro|trendyol|temu|aliexpress|ebay|best seller|bestseller|price|review|test|vergleich|kaufen|shop|official|\.com|\.de/i;
function titleCandidate(title,theme){let value=clean(title).split(/\s+[|–—]\s+|\s+-\s+/)[0].replace(/\([^)]*\)/g,'').replace(/\[[^\]]*\]/g,'').trim();const words=value.split(/\s+/);if(words.length<3||words.length>12||bannedTitle.test(value)||/[€$£]/.test(value)||value.length<14||value.length>90)return null;return{name:value,cat:theme.cat,chinaMin:0,chinaMax:0,sellTarget:0,pricingStatus:'UNKNOWN',sourceType:'OPEN_WEB_DISCOVERY'};}
async function discoverOpenSeeds(themes,day,radarNames,oldNames){if(!themes.length)return[];const theme=themes[day%themes.length],sources=[markets[0],markets[1],markets[4],markets[5],markets[9],markets[10]],found=[];for(const market of sources){const r=await siteQuery(theme.query,market);for(const link of r.links||[]){const seed=titleCandidate(link.title,theme);if(!seed)continue;const key=slug(seed.name);if(!key||radarNames.has(key)||oldNames.has(key)||found.some(x=>slug(x.name)===key))continue;found.push({...seed,openDiscovery:{theme:theme.query,market:market.label,url:link.url,title:link.title,discoveredAt:new Date().toISOString()}});if(found.length>=3)return found;}await delay(100);}return found;}

const catalogue=await readJson(CATALOGUE_FILE,[]),themes=await readJson(THEMES_FILE,[]),radar=await readJson(RADAR_FILE,{products:[]}),old=await readJson(LIVE_FILE,{products:[]}),history=await readJson(HISTORY_FILE,{version:'6.0',products:{}}),radarNames=new Set((radar.products||[]).map(p=>slug(p.name))),oldByName=new Map((old.products||[]).map(p=>[slug(p.name),p])),day=Math.floor(Date.now()/86400000);
const openSeeds=await discoverOpenSeeds(themes,day,radarNames,new Set(oldByName.keys()));
const pool=[...catalogue,...old.products,...openSeeds].filter(p=>p?.name&&!radarNames.has(slug(p.name))),dedup=new Map();for(const p of pool)if(!dedup.has(slug(p.name)))dedup.set(slug(p.name),p);const ordered=[...dedup.values()].sort((a,b)=>slug(a.name).localeCompare(slug(b.name))),start=ordered.length?(day*Math.max(1,MAX_SCAN-3))%ordered.length:0,selected=[];for(const seed of openSeeds)selected.push(seed);for(let i=0;selected.length<Math.min(MAX_SCAN,ordered.length)&&i<ordered.length;i++){const candidate=ordered[(start+i)%ordered.length];if(!selected.some(x=>slug(x.name)===slug(candidate.name)))selected.push(candidate);}
let successfulChecks=0,reviewChecks=0;
for(const seed of selected){const term=clean(seed.name),results=await Promise.all(markets.map(m=>siteQuery(term,m))),signals={};let checks=0,foreignPresence=0,romaniaPresence=0,chinaPresence=0,socialPresence=0,earlyPresence=0,foreignResults=0,romaniaResults=0,chinaResults=0,socialResults=0,earlyResults=0;
  results.forEach((r,i)=>{const m=markets[i];signals[m.key]={label:m.label,ok:!!r.ok,present:!!r.present,resultCount:Number(r.resultCount||0),searchUrl:r.searchUrl,links:(r.links||[]).slice(0,3)};if(r.ok){checks++;successfulChecks++;}if(r.present){if(m.kind==='foreign')foreignPresence++;else if(m.kind==='romania')romaniaPresence++;else if(m.kind==='china')chinaPresence++;else if(m.kind==='social')socialPresence++;else if(m.kind==='early')earlyPresence++;}if(m.kind==='foreign')foreignResults+=Number(r.resultCount||0);else if(m.kind==='romania')romaniaResults+=Number(r.resultCount||0);else if(m.kind==='china')chinaResults+=Number(r.resultCount||0);else if(m.kind==='social')socialResults+=Number(r.resultCount||0);else if(m.kind==='early')earlyResults+=Number(r.resultCount||0);});
  const reviewResults=await Promise.all(reviewMarkets.map(m=>siteQuery(term,m,'review OR reviews')));const reviewSources=reviewResults.map((r,i)=>{if(r.ok)reviewChecks++;return{label:reviewMarkets[i].label,present:!!r.present,searchUrl:r.searchUrl,links:(r.links||[]).slice(0,3),snippets:(r.snippets||[]).slice(0,4)};}),reviewIntel={sources:reviewSources,...reviewEvidenceSummary({sources:reviewSources}),validation:'Review intelligence is derived from review-search result snippets/links, not a verified review count or full review corpus.'};
  const seedPricing=n(seed.sellTarget)>0&&(n(seed.chinaMin)>0||n(seed.chinaMax)>0),candidate={...seed,pricingStatus:seedPricing?(seed.pricingStatus||'SEED_ESTIMATE'):'UNKNOWN',landedEstimate:seedPricing?landedEstimate(seed):0,checkedAt:new Date().toISOString(),checks,foreignPresence,romaniaPresence,chinaPresence,socialPresence,earlyPresence,foreignResults,romaniaResults,chinaResults,socialResults,earlyResults,signals,sourcing:sourcingLinks(seed.name),reviewIntel,sourceType:seed.sourceType||'GLOBAL_DISCOVERY_NETWORK + LIVE WEB VALIDATION',validation:'Counts are web-search proxies. Sales, seller counts, supplier terms, MOQ, certifications and exact prices are not verified.'};
  const analysis=discoveryScore(candidate);candidate.discoveryAnalysis=analysis;candidate.suggestedStage=suggestedDiscoveryStage(candidate);candidate.sourceStatus=analysis.quality.level==='LIVE'?'WEB_SIGNAL':'PARTIAL';candidate.evidence=`${foreignPresence} piețe externe • ${earlyPresence} early-signal • ${chinaPresence} sourcing China • ${romaniaPresence} semnal RO • ${socialPresence} social • ${reviewIntel.sourceCount} review-search. Proxy web, nu volum de vânzări.`;
  const key=slug(seed.name),points=history.products?.[key]?.points||[],point={at:candidate.checkedAt,score:analysis.score,quality:analysis.quality.level,foreignPresence,romaniaPresence,chinaPresence,socialPresence,earlyPresence,reviewSources:reviewIntel.sourceCount},nextPoints=appendHistoryPoint(points,point);history.products=history.products||{};history.products[key]={name:candidate.name,points:nextPoints};candidate.trendWindows=discoveryTrendWindows(nextPoints);
  oldByName.set(key,{...(oldByName.get(key)||{}),...candidate,firstDiscoveredAt:oldByName.get(key)?.firstDiscoveredAt||candidate.openDiscovery?.discoveredAt||candidate.checkedAt});await delay(150);
}
history.version='6.0';history.updatedAt=new Date().toISOString();const products=[...oldByName.values()].filter(p=>!radarNames.has(slug(p.name))).sort((a,b)=>Number(b.discoveryAnalysis?.score||0)-Number(a.discoveryAnalysis?.score||0)).slice(0,MAX_INBOX),payload={version:'6.0',engine:'Global Product Discovery Network 6.0',updatedAt:new Date().toISOString(),scanSize:selected.length,openDiscovered:openSeeds.length,successfulChecks,reviewChecks,network:{markets:markets.map(({key,label,kind})=>({key,label,kind})),sourceCount:markets.length,reviewSourceCount:reviewMarkets.length},validation:'Discovery combines rotating seeds with a global open-web network. Search counts and snippets are evidence proxies, not verified sales/review volume.',products};
await Promise.all([fs.writeFile(LIVE_FILE,JSON.stringify(payload,null,2)+'\n'),fs.writeFile(HISTORY_FILE,JSON.stringify(history,null,2)+'\n')]);
console.log(`Global Discovery 6.0: scanned ${selected.length}, open ${openSeeds.length}, market checks ${successfulChecks}, review checks ${reviewChecks}, inbox ${products.length}.`);
