create table if not exists public.raw_product_candidates (
  id bigint generated by default as identity primary key,
  fingerprint text not null unique,
  title text not null,
  category text,
  status text not null default 'RAW' check (status in ('RAW','SHORTLISTED','PROMOTED','REJECTED')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  seen_count integer not null default 1 check (seen_count >= 1),
  checked_at timestamptz,
  foreign_presence integer not null default 0,
  romania_presence integer not null default 0,
  china_presence integer not null default 0,
  social_presence integer not null default 0,
  foreign_results integer not null default 0,
  romania_results integer not null default 0,
  china_results integer not null default 0,
  social_results integer not null default 0,
  source_url text,
  image_url text,
  source_label text,
  raw_payload jsonb not null default '{}'::jsonb,
  promoted_product_id uuid references public.canonical_products(id) on delete set null,
  updated_at timestamptz not null default now()
);

create index if not exists raw_product_candidates_status_last_seen_idx
  on public.raw_product_candidates(status,last_seen_at desc);
create index if not exists raw_product_candidates_signal_idx
  on public.raw_product_candidates(foreign_presence desc,china_presence desc,romania_presence asc,last_seen_at desc);

alter table public.raw_product_candidates enable row level security;
revoke all on public.raw_product_candidates from anon, authenticated;
grant select,insert,update,delete on public.raw_product_candidates to service_role;
grant usage,select on sequence public.raw_product_candidates_id_seq to service_role;
