-- Romania refresh consumer v1
-- Atomic claim + evidence persistence + fail-closed completion for the 100-product Romania benchmark.

create table if not exists public.romania_surface_observations (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.canonical_products(id) on delete cascade,
  surface text not null check (surface in ('EMAG_RO','TRENDYOL_RO','RETAIL_WEB_RO')),
  observed_at timestamptz not null,
  evidence_class text not null,
  freshness_class text not null,
  source_url text,
  search_query text,
  product_link_lower_bound integer,
  declared_result_count_candidate integer,
  declared_result_count_trusted boolean not null default false,
  seller_count integer,
  comparable_scope_confirmed boolean not null default false,
  market_wide_competition_ready boolean not null default false,
  sales_evidence_class text not null default 'NOT_VERIFIED_SALES',
  comparability_confidence numeric,
  collector_version text not null,
  raw_evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(product_id, surface, observed_at, collector_version)
);

create index if not exists romania_surface_observations_product_surface_observed_idx
  on public.romania_surface_observations(product_id, surface, observed_at desc);

alter table public.romania_surface_observations enable row level security;

create or replace function public.claim_romania_refresh_jobs_v1(
  p_owner text,
  p_limit integer default 10,
  p_lease_seconds integer default 600
)
returns table (
  id bigint,
  product_id uuid,
  target_surface text,
  evidence_kind text,
  tier text,
  priority_score numeric,
  attempt_count integer,
  title text,
  category text,
  canonical_key text
)
language plpgsql
security definer
set search_path = public
as $function$
begin
  if nullif(btrim(p_owner),'') is null then
    raise exception 'LEASE_OWNER_REQUIRED';
  end if;
  if p_limit < 1 or p_limit > 25 then
    raise exception 'LEASE_LIMIT_OUT_OF_RANGE';
  end if;
  if p_lease_seconds < 60 or p_lease_seconds > 1800 then
    raise exception 'LEASE_SECONDS_OUT_OF_RANGE';
  end if;

  return query
  with picked as (
    select q.id
    from public.refresh_queue q
    where q.state = 'PENDING'
      and q.due_at <= now()
      and q.target_surface in ('EMAG_RO','TRENDYOL_RO','RETAIL_WEB_RO')
      and q.evidence_kind = 'ROMANIA_MARKET_PRESENCE'
      and coalesce(q.estimated_cost_eur,0) = 0
      and coalesce((q.provider_policy->>'paid_calls_allowed')::boolean,false) = false
      and coalesce((q.provider_policy->>'purchase_authorized')::boolean,false) = false
    order by coalesce(q.priority_score,0) desc, q.due_at asc, q.id asc
    for update skip locked
    limit p_limit
  ), leased as (
    update public.refresh_queue q
    set state = 'LEASED',
        lease_owner = p_owner,
        lease_expires_at = now() + make_interval(secs => p_lease_seconds),
        attempt_count = coalesce(q.attempt_count,0) + 1,
        last_error = null
    from picked
    where q.id = picked.id
    returning q.*
  )
  select l.id, l.product_id, l.target_surface, l.evidence_kind, l.tier,
         l.priority_score, l.attempt_count, p.title, p.category, p.canonical_key
  from leased l
  join public.canonical_products p on p.id = l.product_id
  order by coalesce(l.priority_score,0) desc, l.id asc;
end;
$function$;

create or replace function public.finish_romania_refresh_job_v1(
  p_job_id bigint,
  p_owner text,
  p_outcome text,
  p_evidence jsonb default '{}'::jsonb,
  p_error text default null,
  p_retry_after_seconds integer default 21600
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  q public.refresh_queue%rowtype;
  outcome text := upper(coalesce(p_outcome,''));
  observed_at timestamptz;
  surface text;
  inserted_observation_id bigint;
begin
  select * into q
  from public.refresh_queue
  where id = p_job_id
  for update;

  if not found then raise exception 'JOB_NOT_FOUND'; end if;
  if q.state <> 'LEASED' then raise exception 'JOB_NOT_LEASED'; end if;
  if q.lease_owner is distinct from p_owner then raise exception 'LEASE_OWNER_MISMATCH'; end if;
  if q.lease_expires_at is null or q.lease_expires_at < now() then raise exception 'LEASE_EXPIRED'; end if;
  if q.target_surface not in ('EMAG_RO','TRENDYOL_RO','RETAIL_WEB_RO') then raise exception 'SURFACE_NOT_ALLOWED'; end if;

  if outcome = 'COMPLETED' then
    surface := coalesce(p_evidence->>'surface','');
    if surface <> q.target_surface then raise exception 'EVIDENCE_SURFACE_MISMATCH'; end if;
    if coalesce((p_evidence->>'paidCallsTriggered')::integer,0) <> 0 then raise exception 'PAID_CALLS_NOT_ALLOWED'; end if;
    if coalesce((p_evidence->>'purchaseAuthorized')::boolean,false) <> false then raise exception 'PURCHASE_NOT_ALLOWED'; end if;
    if coalesce(p_evidence->>'salesEvidenceClass','') <> 'NOT_VERIFIED_SALES' then raise exception 'SALES_EVIDENCE_CLASS_INVALID'; end if;
    observed_at := coalesce((p_evidence->>'observedAt')::timestamptz, now());

    insert into public.romania_surface_observations(
      product_id,surface,observed_at,evidence_class,freshness_class,source_url,search_query,
      product_link_lower_bound,declared_result_count_candidate,declared_result_count_trusted,
      seller_count,comparable_scope_confirmed,market_wide_competition_ready,sales_evidence_class,
      comparability_confidence,collector_version,raw_evidence
    ) values (
      q.product_id,q.target_surface,observed_at,
      coalesce(nullif(p_evidence->>'evidenceClass',''),'DIAGNOSTIC_ONLY'),
      coalesce(nullif(p_evidence->>'freshnessClass',''),'UNKNOWN'),
      nullif(p_evidence->>'sourceUrl',''),nullif(p_evidence->>'searchQuery',''),
      nullif(p_evidence->>'productLinkLowerBound','')::integer,
      nullif(p_evidence->>'declaredResultCountCandidate','')::integer,
      coalesce((p_evidence->>'declaredResultCountTrusted')::boolean,false),
      nullif(p_evidence->>'sellerCount','')::integer,
      coalesce((p_evidence->>'comparableScopeConfirmed')::boolean,false),
      coalesce((p_evidence->>'marketWideCompetitionReady')::boolean,false),
      'NOT_VERIFIED_SALES',
      nullif(p_evidence->>'comparabilityConfidence','')::numeric,
      coalesce(nullif(p_evidence->>'collectorVersion',''),'romania-refresh-consumer-v1'),
      p_evidence
    )
    on conflict (product_id,surface,observed_at,collector_version) do nothing
    returning id into inserted_observation_id;

    update public.refresh_queue
    set state='COMPLETED', completed_at=now(), lease_owner=null, lease_expires_at=null, last_error=null
    where id=p_job_id;
  elsif outcome in ('DEFERRED','FAILED') then
    if p_retry_after_seconds < 300 or p_retry_after_seconds > 604800 then
      raise exception 'RETRY_SECONDS_OUT_OF_RANGE';
    end if;
    update public.refresh_queue
    set state='PENDING',
        due_at=now()+make_interval(secs => p_retry_after_seconds),
        lease_owner=null,
        lease_expires_at=null,
        last_error=left(coalesce(p_error,outcome),500)
    where id=p_job_id;
  else
    raise exception 'OUTCOME_NOT_ALLOWED';
  end if;

  return jsonb_build_object(
    'ok',true,
    'jobId',p_job_id,
    'outcome',outcome,
    'surface',q.target_surface,
    'observationId',inserted_observation_id,
    'paidCallsTriggered',0,
    'providerSpendEur',0,
    'purchaseAuthorized',false,
    'salesEvidenceClass','NOT_VERIFIED_SALES'
  );
end;
$function$;

revoke all on function public.claim_romania_refresh_jobs_v1(text,integer,integer) from public, anon, authenticated;
revoke all on function public.finish_romania_refresh_job_v1(bigint,text,text,jsonb,text,integer) from public, anon, authenticated;
grant execute on function public.claim_romania_refresh_jobs_v1(text,integer,integer) to service_role;
grant execute on function public.finish_romania_refresh_job_v1(bigint,text,text,jsonb,text,integer) to service_role;
